# <font color = yellow><b> Implementation of FOMC text RAG system as seperate agent for relevant text retrieval to answer user query.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
## Loading updated FOMC dataset generated during EDA(data_load_fomc.ipynb).

import contextlib
import io
from google.colab import drive

with contextlib.redirect_stdout(io.StringIO()):
    drive.mount('/content/drive')

path = "/content/FOMC_updated_dataset.xlsx"

fomc_df = pd.read_excel(path)

In [3]:
fomc_df.head()

,Date,Release Date,Type,Text,Release Year,Date Difference
0,2025-12-10,2025-12-30,Minute,Minutes of the Federal Open Market Committee\n...,2025,20
1,2025-12-10,2025-12-10,Statement,Available indicators suggest that economic act...,2025,0
2,2025-10-29,2025-10-29,Statement,Available indicators suggest that economic act...,2025,0
3,2025-10-29,2025-11-19,Minute,Minutes of the Federal Open Market Committee\n...,2025,21
4,2025-09-17,2025-09-17,Statement,Recent indicators suggest that growth of econo...,2025,0

#### FOMC dataset consists of six columns : Date, Release Date, Type, Text, Release Year, Date Difference.

#### Step 2: Transfomration of dataset.

In [4]:
## Copy FOMC uploaded dataset to different dataset for preprocessing.
fomc_new_df = fomc_df.copy()

In [5]:
## Keep 3required columns release date, type, text and release year
fomc_new_df = fomc_new_df[['Date','Release Date', 'Type', 'Text']]
fomc_new_df.head()

,Date,Release Date,Type,Text
0,2025-12-10,2025-12-30,Minute,Minutes of the Federal Open Market Committee\n...
1,2025-12-10,2025-12-10,Statement,Available indicators suggest that economic act...
2,2025-10-29,2025-10-29,Statement,Available indicators suggest that economic act...
3,2025-10-29,2025-11-19,Minute,Minutes of the Federal Open Market Committee\n...
4,2025-09-17,2025-09-17,Statement,Recent indicators suggest that growth of econo...

In [6]:
fomc_new_df.isna().sum()  ## To cehck if any null values present

Date            0
Release Date    0
Type            0
Text            0
dtype: int64

#### There are no missing records.

In [7]:
## Modify release date type to datetime if it is not datetime.

fomc_new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          458 non-null    datetime64[ns]
 1   Release Date  458 non-null    datetime64[ns]
 2   Type          458 non-null    object
 3   Text          458 non-null    object
dtypes: datetime64[ns](2), object(2)
memory usage: 14.4+ KB

#### Release Date column is already a datetime type

In [8]:
## Add a new column doc_id with format M_actualmeetimgdate(yymmdd) for Minutes and S_actualmeetingdate(yymmdd) for Statements.
## doc_id is used to identify individual FOMC text.


for i in fomc_new_df.index:
  if fomc_new_df.iloc[i]['Type']=='Statement':
    fomc_new_df.loc[i,'doc_id'] = 'S_'+fomc_new_df.iloc[i]['Date'].strftime("%y%m%d")
  else:
    fomc_new_df.loc[i,'doc_id'] = 'M_'+fomc_new_df.iloc[i]['Date'].strftime("%y%m%d")

In [9]:
fomc_new_df.head(10)

,Date,Release Date,Type,Text,doc_id
0,2025-12-10,2025-12-30,Minute,Minutes of the Federal Open Market Committee\n...,M_251210
1,2025-12-10,2025-12-10,Statement,Available indicators suggest that economic act...,S_251210
2,2025-10-29,2025-10-29,Statement,Available indicators suggest that economic act...,S_251029
3,2025-10-29,2025-11-19,Minute,Minutes of the Federal Open Market Committee\n...,M_251029
4,2025-09-17,2025-09-17,Statement,Recent indicators suggest that growth of econo...,S_250917
5,2025-09-17,2025-10-08,Minute,Minutes of the Federal Open Market Committee\n...,M_250917
6,2025-07-30,2025-07-30,Statement,Although swings in net exports continue to aff...,S_250730
7,2025-07-30,2025-08-20,Minute,Minutes of the Federal Open Market Committee\n...,M_250730
8,2025-06-18,2025-06-18,Statement,Although swings in net exports have affected t...,S_250618
9,2025-06-18,2025-07-09,Minute,Minutes of the Federal Open Market Committee\n...,M_250618

### Doc_id indexes individual documents based on its type and release date for easy understanding of document indexing.

In [10]:
## Clean categorical column (type) by stripping spaces left and right.
fomc_new_df['Type'] = fomc_new_df['Type'].str.strip()

### Step 3: Cleaning of Text by removing header and short sentences not relevant for FOMC RAG implementation.

In [11]:
## Create adiitional column 'Text_Clean' and copy 'Text' column for cleaning of text.
fomc_new_df['Text_Clean'] = fomc_new_df['Text']

In [12]:
## Checking few sample Minutes.
from IPython.display import display
display(fomc_new_df[fomc_new_df.Type=='Minute'].Text.iloc[1])

'Minutes of the Federal Open Market Committee\n                                                \n                    \n                    \n                    \n                    October 28â\x80\x9329, 2025\nA joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, October 28, 2025, at 9:00 a.m. and continued on Wednesday, October 29, 2025, at 9:00 a.m.1\n\nDevelopments in Financial Markets and Open Market Operations\nThe manager turned first to an overview of broad market developments during the intermeeting period. Market participants left their macroeconomic outlooks little changed, and they appeared to continue to interpret data made available over the period as consistent with a resilient economy. In line with the stable outlook, investors\' expectations for the path of the policy rate, whether market based or survey based, were virtually unchanged over the period. Investors expected a 25 basis point lowering in the target range for the federal funds rate at the October meeting and another 25 basis point lowering at the December meeting, although some uncertainty around the December meeting was evident in responses to the Open Market Desk\'s Survey of Market Expectations (Desk survey) as well as in market prices.\n\nThe manager turned next to developments in Treasury markets and market-based measures of inflation compensation. Treasury yields were little changed, on net, over the period, consistent with stable expectations for the policy rate. Inflation compensation moved lower over the period, particularly for shorter tenors, with staff models attributing these recent movements to temporary factors.\n\nBroad equity indexes continued to rise over the period, with the largest technology companies performing strongly on market participants\' optimism about artificial intelligence (AI). The manager noted that rising stock prices were consistent with expectations for continued robust growth in earnings. Corporate bond spreads increased a bit this period but remained low in absolute terms. A couple of well-publicized bankruptcies, as well as some credit losses reported by some banks, led to increased investor scrutiny of credit markets, with investors reportedly closely tracking the riskiest segments of credit markets for signs of weakening and noting the possibility of future losses.\n\nRegarding international developments, the manager noted that the trade-weighted dollar index rose somewhat over the period. Despite its recent appreciation, the dollar remained weaker against all major currencies since the beginning of the year, and outside forecasters continued to expect that the dollar would depreciate modestly over the medium term.\n\nThe manager highlighted that recent changes in money market conditions indicated that the level of reserves could be approaching ample. Rates on Treasury repurchase agreements (repo) moved notably higher relative to the interest rate on reserve balances (IORB). Investors attributed this movement to a decline in available liquidity amid ongoing balance sheet runoff and continued large Treasury debt issuance. Higher repo rates induced a fairly rapid increase in the effective federal funds rate (EFFR) relative to the IORB, with signs that the EFFR might increase further. The manager noted this increase was widespread, with many participants paying higher rates in the federal funds market regardless of their reasons for borrowing. Consistent with the move higher in repo rates, the overnight reverse repurchase agreement (ON RRP) facility had seen usage fall to de minimis levels. Meanwhile, the standing repo facility (SRF) was used more frequently over the period, albeit not in large volumes. Pressures in money markets resulted in notable movements in some other indicators of reserve ampleness. For example, payments by banks shifted to later in the day, suggesting that banks may have been economizing on reserves. In addition, the share of domestic banks borrowing in the federal funds market increased. The estimated elasticity of the EFFR with respect to changes in the supply of reserves was stable during the period. That outcome, however, was likely due to the aftereffects of the debt ceiling resolution, which likely affected the estimated elasticity. A related concept, the elasticity of repo rates to changes in repo volumes, increased significantly since late August.\n\nThe manager recommended that the Committee consider stopping the runoff of the System Open Market Account (SOMA) portfolio soon. Continuing runoff would imply that volatility in money markets likely would continue to intensify. He noted that excessive money market rate volatility would pose risks to both the control of the policy rate and the stability of funding in the repo market, which in turn could affect the stability of the U.S. Treasury market. The manager also noted that further reductions in the size of the portfolio may prove short lived because they would bring forward the time when the Desk would need to restart purchases of securities to maintain ample reserves.\n\nThe manager next discussed the expected trajectory of the balance sheet. Respondents to the Desk survey had come to expect an earlier date for the end of portfolio runoff. Market outreach suggested further revisions to expectations in the week after the survey concluded, and the staff estimated that if respondents had been asked more recently, almost half would have said they expected the Committee to announce an end to runoff at this meeting.\n\nIn the absence of material take-up at the ON RRP facility, and assuming balance sheet runoff would end, the staff estimated that reserves would continue to gradually decline amid projected increases in other Federal Reserve liabilities. At times, such as during quarter- and year-ends and tax dates, reserves were projected to dip to quite low levels. Against this backdrop, the staff would continue to monitor indicators of reserve conditions closely.\n\nThe manager noted that the Desk would begin using a new trading platform in the near future to conduct its repo and reverse repo operations, with other operations to follow in coming quarters. In addition, he informed the Committee that there were no intervention operations in foreign currencies for the SOMA during the intermeeting period.\n\nBy unanimous vote, the Committee ratified the Desk\'s domestic transactions over the intermeeting period.\n\nSpecial Topic: The Standing Repo Facility\nThe staff provided background on the SRF, including potential benefits and costs of central clearing for SRF transactions. The main potential benefit mentioned was greater effectiveness of the SRF in helping to maintain control of the federal funds rate. Central clearing could increase counterparties\' willingness to use the SRF when there is upward pressure on repo rates, which would damp pressures on the federal funds rate. The main potential costs mentioned were increased systemic importance of providers of central clearing, the potential for central clearing of the SRF to enable greater nonbank leverage in the Treasury market, and the expansion of the Federal Reserve\'s footprint in financial markets.\n\nMost participants commented on the potential for central clearing of SRF transactions.2 Among those who commented, almost all noted that the SRF supports the effective implementation and transmission of monetary policy as well as smooth market functioning, and that central clearing of SRF transactions could improve the effectiveness of the facility. A few participants raised concerns about risks associated with centrally clearing the SRF, including increased systemic importance of providers of central clearing. Participants who commented generally supported further study of central clearing of SRF transactions.\n\nSpecial Topic: Balance Sheet Issues\nThe FOMC\'s "Plans for Reducing the Size of the Federal Reserve\'s Balance Sheet," announced in May 2022, indicated that the Committee intended to cease balance sheet runoff when reserve balances are judged to be somewhat above a level consistent with ample reserves. Since then, the size of the Federal Reserve\'s balance sheet had declined substantially. In addition, money market conditions had tightened recently, which suggested that reserve balances may be moving closer to ample. In light of these developments, participants discussed whether to stop balance sheet runoff soon and what the maturity composition of the SOMA Treasury portfolio (SOMA portfolio) should be in the longer run. Views on the latter would guide the investment of principal payments received on the Federal Reserve\'s holdings of agency securities as well as the composition of securities to be purchased once reserve management purchases would be needed. Consequently, participants agreed that their discussions at this meeting would help inform the Committee\'s future decisions regarding the long-run composition of the SOMA portfolio.\n\nThe participants\' discussion was preceded by a staff presentation. The staff reviewed the composition of the SOMA portfolio and provided some considerations regarding the SOMA portfolio\'s long-run composition, including issues related to market functioning, potential macroeconomic implications, interactions with the Treasury\'s management of the federal debt, monetary policy implementation, and the Federal Reserve\'s net income. The presentation noted that the current share of Treasury bills in the SOMA portfolio was smaller than the bill share of total Treasury securities outstanding. The staff also noted that if the Committee preferred a SOMA portfolio with a proportional or greater share of Treasury bills relative to total outstanding, policymakers could wait to make that decision because the current share of Treasury bills in the portfolio was small and the monthly amounts of principal payments received on the Federal Reserve\'s holdings of agency securities that would need to be reinvested once balance sheet runoff stopped were modest.\n\nParticipants agreed that the recent tightening in money market conditions indicated that it would soon be appropriate to end balance sheet runoff and that reinvestments of principal payments received on agency securities holdings should be directed into Treasury bills. Various participants highlighted the need to continue to monitor money market conditions. Participants also agreed that a larger share of Treasury bills than the current portfolio allocation would be desirable in the long run. A larger share of Treasury bills would shift the SOMA portfolio composition toward that of Treasury securities outstanding. Many participants indicated that a greater share of Treasury bills could provide the Federal Reserve with more flexibility to accommodate changes in the demand for reserves or changes in nonreserve liabilities and thereby help to maintain an ample level of reserves. Several participants also noted that a greater share of Treasury bills could increase flexibility for future monetary policy accommodation without having to raise the level of reserves. The majority of participants indicated that a larger share of Treasury bills would also reduce Federal Reserve income volatility.\n\nSome participants indicated that during a transition phase, purchases to reach a larger share of Treasury bills in the SOMA portfolio could reduce the availability of short-term Treasury securities to the private sector and potentially affect market functioning. They thus favored a measured approach to purchasing Treasury bills. A couple of other participants noted the absence of market functioning problems in past episodes when purchases focused on Treasury bills. A number of participants noted that the expected pace of paydowns of agency securities in the near term was around only $15 billion to $20 billion per month, and that redirecting these proceeds into Treasury bills once balance sheet runoff ended likely would not adversely affect market functioning.\n\nOverall, most participants favored a long-run composition of the SOMA portfolio that matched the composition of Treasury securities outstanding, indicating that a proportional allocation would provide enough flexibility and may be simpler to communicate. Some participants indicated that they favored a larger-than-proportional share of Treasury bills, citing the benefits of having even greater flexibility than available under a proportional allocation. Various participants noted that it was not necessary to decide on the long-run composition of the SOMA portfolio at this time, as the shift toward a long-run composition would take place over a number of years.\n\nStaff Review of the Economic Situation\nThe information available at the time of the meeting indicated that growth of real gross domestic product (GDP) had moderated over the first half of the year. Information on the labor market was limited by the federal government shutdown; however, available indicators were consistent with a continued gradual cooling in the labor market without any evidence of a sharp deterioration. Consumer price inflation had moved up since earlier in the year and remained somewhat elevated.\n\nTotal consumer price inflationâ\x80\x94as measured by the 12-month change in the price index for personal consumption expenditures (PCE)â\x80\x94was estimated to have been 2.8 percent in September based on data from the consumer price index. Core PCE price inflation, which excludes changes in consumer energy prices and many consumer food prices, was also estimated to have been 2.8 percent in September. These estimates implied that total PCE price inflation had risen 0.5 percentage point relative to a year ago and that core PCE inflation was unchanged from its year-earlier rate.\n\nReal GDP posted a strong gain in the second quarter following a decline in the first quarter, although the average increase over the first half of the year was slower than the average pace seen over 2024. Real private domestic final purchases (PDFP)â\x80\x94which comprises PCE and private fixed investment and which often provides a better signal of underlying economic momentum than GDPâ\x80\x94had risen faster than GDP over the first half but had also slowed relative to its 2024 rate of increase. PDFP growth appeared to have continued at a solid pace in the third quarter, though the government shutdown had reduced the amount of data that was available to gauge third-quarter economic activity. Available data suggested that net exports positively contributed to GDP growth in the third quarter. After falling sharply in the second quarter and then rising somewhat in July, real imports of goods appeared to have resumed falling in August. U.S. real goods exports appeared to have declined moderately in August after having increased modestly in the first half of the year. The government shutdown was expected to reduce GDP growth for as long as it continued, with a corresponding boost to growth once the government reopened and government production and purchases returned to normal levels.\n\nRecent activity indicators suggested that foreign real GDP growth slowed in the third quarter relative to the first half of the year. Growth in China softened amid fading fiscal stimulus and a persistent property-sector downturn, while indicators in Europe continued to point to subdued activity. Slower foreign growth was driven in part by weaker exports due to reduced U.S. demand and lower investment due to elevated uncertainty, likely reflecting the effects of the U.S. tariffs. Growth in some foreign economies, especially in Mexico and parts of Asia, was supported by continued strong demand for high-tech products, originating primarily from the U.S.\n\nHeadline inflation was near central banks\' targets in many foreign economies, aided by declines in global energy prices. However, core inflation remained elevated in some economies, notably Brazil, Mexico, and the U.K. By contrast, inflation in China continued to be subdued. In response to lackluster economic activity, some foreign central banksâ\x80\x94including the Bank of Canada, the Sveriges Riksbank, and the Bank of Mexicoâ\x80\x94cut their policy rates further over the intermeeting period.\n\nStaff Review of the Financial Situation\nOver the intermeeting period, both the market-implied expected path of the federal funds rate through the end of 2026 and nominal Treasury yields were little changed on net. At short maturities, real yields rose somewhat as measures of inflation compensation decreased amid declines in oil prices. At longer maturities, real yields and inflation compensation were little changed on net.\n\nBroad equity price indexes increased moderately, boosted by technology firms with positive earnings news and AI-related investor optimism. Credit spreads were little changed, on net, and remained very low by historical standards. The one-month option-implied volatility on the S&P 500 index was largely unchanged, on net, and remained near the median of its historical distribution.\n\nRisk appetite in foreign financial markets was generally strong. On net, foreign equity indexes were moderately higher, and technology stocks outperformed in several economies, largely reflecting continued investor optimism regarding AI. Market-based policy expectations and longer-term yields declined in most major advanced foreign economies, in part because of weak economic data. By contrast, yields in Japan rose amid political developments that led to expectations for increased fiscal spending. The broad dollar index increased modestly, primarily driven by the relative strength of U.S. economic data.\n\nConditions in U.S. short-term funding markets tightened materially over the intermeeting period but remained orderly. Late in the period, the spread between the EFFR and the IORB reached the narrowest level since the runoff of the Federal Reserve\'s balance sheet began in 2022. The Secured Overnight Financing Rate occasionally printed above the minimum bid rate at the SRF, and SRF take-up occurred on several days. The average usage of the ON RRP facility fell to its lowest level since 2021. Taken together, these developments suggested that reserve balances were moving closer to ample levels.\n\nIn domestic credit markets, borrowing costs of businesses, households, and municipalities remained significantly lower than the highs observed in 2023 but elevated relative to their average postâ\x80\x93Global Financial Crisis levels. Yields on corporate bonds and leveraged loans edged down. Rates on 30-year fixed-rate conforming residential mortgages were little changed on net. Yields on commercial mortgage-backed securities (CMBS) moved up modestly. Interest rates on credit card accounts edged up a touch in August.\n\nCredit remained generally available but relatively tight for small businesses. Issuance of corporate bonds, leveraged loans, and private credit was robust in recent months. Core loans on banks\' books continued to increase in the third quarter, driven primarily by strong growth in commercial and industrial (C&I) lending. In the residential mortgage market, credit remained easily available for high-credit-score borrowers but less so for low-score borrowers. Consumer credit remained generally available for most households.\n\nBanks in the October Senior Loan Officer Opinion Survey on Bank Lending Practices reported, on net, an easing in bank lending conditions on C&I loans for large firms and those with low exposures to international trade. Banks also eased standards for commercial real estate loans, credit cards, and auto loans over the third quarter. The overall level of bank lending standards aggregated across all loan categories was estimated to be around the median level observed since 2011.\n\nCredit quality was generally stable at levels

In [13]:
txt=fomc_new_df[fomc_new_df.Type=='Minute'].Text.iloc[90].split('\n')
txt

['Minutes of the Federal Open Market Committee',
 '                                                ',
 '                    ',
 '                    ',
 '                    ',
 '                    December 16-17, 2014',
 '',
 'A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 16, 2014, at 1:00 p.m. and continued on Wednesday, December 17, 2014, at 9:00 a.m.',
 '',
 'PRESENT:',
 '',
 'Janet L. Yellen, Chair',
 'William C. Dudley, Vice Chairman',
 'Lael Brainard',
 'Stanley Fischer',
 'Richard W. Fisher',
 'Narayana Kocherlakota',
 'Loretta J. Mester',
 'Charles I. Plosser',
 'Jerome H. Powell',
 'Daniel K. Tarullo',
 '',
 'Christine Cumming, Charles L. Evans, Jeffrey M. Lacker, Dennis P. Lockhart, and John C. Williams, Alternate Members of the Federal Open Market Committee',
 '',
 'James Bullard, Esther L. George, and Eric Rosengren, Presidents of the Federal Reserve Banks of St. Louis, Kansas City, and Boston, respectively',
 '',
 'William B. English, Secretary and Economist',
 'Matthew M. Luecke, Deputy Secretary',
 'Michelle A. Smith, Assistant Secretary',
 'Scott G. Alvarez, General Counsel',
 'Steven B. Kamin, Economist',
 'David W. Wilcox, Economist',
 '',
 'James A. Clouse, Thomas A. Connors, Evan F. Koenig, Thomas Laubach, Michael P. Leahy, Paolo A. Pesenti, Samuel Schulhofer-Wohl, Mark E. Schweitzer, and William Wascher, Associate Economists',
 '',
 'Simon Potter, Manager, System Open Market Account',
 '',
 'Lorie K. Logan, Deputy Manager, System Open Market Account',
 '',
 'Robert deV. Frierson,1 Secretary of the Board, Office of the Secretary, Board of Governors',
 '',
 'Michael S. Gibson, Director, Division of Banking Supervision and Regulation, Board of Governors',
 '',
 'Stephen A. Meyer and William R. Nelson, Deputy Directors, Division of Monetary Affairs, Board of Governors',
 '',
 'Andreas Lehnert, Deputy Director, Office of Financial Stability Policy and Research, Board of Governors',
 '',
 'Andrew Figura, David Reifschneider, and Stacey Tevlin, Special Advisers to the Board, Office of Board Members, Board of Governors',
 '',
 'Trevor A. Reeve, Special Adviser to the Chair, Office of Board Members, Board of Governors',
 '',
 'Linda Robertson, Assistant to the Board, Office of Board Members, Board of Governors',
 '',
 'Christopher J. Erceg, Senior Associate Director, Division of International Finance, Board of Governors',
 '',
 'Michael T. Kiley, Senior Adviser, Division of Research and Statistics, and Senior Associate Director, Office of Financial Stability Policy and Research, Board of Governors',
 '',
 'Ellen E. Meade and Joyce K. Zickler, Senior Advisers, Division of Monetary Affairs, Board of Governors',
 '',
 'Daniel M. Covitz, Eric M. Engen, and Diana Hancock, Associate Directors, Division of Research and Statistics, Board of Governors',
 '',
 'David Lopez-Salido, Deputy Associate Director, Division of Monetary Affairs, Board of Governors; John J. Stevens, Deputy Associate Director, Division of Research and Statistics, Board of Governors',
 '',
 'Stephanie R. Aaronson, Assistant Director, Division of Research and Statistics, Board of Governors',
 '',
 'Robert J. Tetlow, Adviser, Division of Monetary Affairs, Board of Governors',
 '',
 'Elizabeth Klee, Section Chief, Division of Monetary Affairs, Board of Governors',
 '',
 'Katie Ross,1 Manager, Office of the Secretary, Board of Governors',
 '',
 'Achilles Sangster II, Information Management Analyst, Division of Monetary Affairs, Board of Governors',
 '',
 'Kelly J. Dubbert, First Vice President, Federal Reserve Bank of Kansas City',
 '',
 'David Altig and Alberto G. Musalem, Executive Vice Presidents, Federal Reserve Banks of Atlanta and New York, respectively',
 '',
 'Michael Dotsey, Geoffrey Tootell, and Christopher J. Waller, Senior Vice Presidents, Federal Reserve Banks of Philadelphia, Boston, and St. Louis, respectively',
 '',
 'Hesna Genay, Douglas Tillett, Robert G. Valletta, and Alexander L. Wolman, Vice Presidents, Federal Reserve Banks of Chicago, Chicago, San Francisco, and Richmond, respectively',
 '',
 'Willem Van Zandweghe, Assistant Vice President, Federal Reserve Bank of Kansas City',
 '',
 "Developments in Financial Markets and the Federal Reserve's Balance Sheet",
 "In a joint session of the Federal Open Market Committee (FOMC) and the Board of Governors of the Federal Reserve System, the manager of the System Open Market Account (SOMA) reported on developments in domestic and foreign financial markets as well as System open market operations conducted during the period since the Committee met on October 28-29, 2014. In addition, the manager reviewed the implications of recent foreign central bank policy actions for the international portion of the SOMA portfolio. The manager also provided an update on staff work related to potential arrangements that would allow depository institutions to pledge funds held in a segregated account at the Federal Reserve as collateral in borrowing transactions with private creditors and which could potentially provide an additional supplementary tool during policy normalization. After further review, staff analysis suggested that such accounts involved a number of operational, regulatory, and policy issues. These issues raised questions about these accounts' possible effectiveness that would be difficult to resolve in a timely fashion. It was therefore decided that further work to implement such accounts would be shelved for now.",
 '',
 "The deputy manager followed with a discussion of the outcomes of recent tests of supplementary normalization tools, namely the Term Deposit Facility (TDF) and term and overnight reverse repurchase agreements (term RRPs and ON RRPs, respectively). Regarding the TDF testing, the introduction of an early withdrawal option led to significant increases in the number of participating depository institutions and in take-up relative to earlier operations without this feature. As expected, both participation and take-up in the operations continued to be sensitive to the offering rate and maximum individual award amount. The Open Market Desk successfully conducted the first two of four preannounced term RRP operations extending across the end of the year to help address expected downward pressures on short-term rates. Commentary from market participants suggested that these operations may help alleviate some of the volatility in short-term rates that would otherwise be expected around the year-end. Regarding the ON RRP testing--during which the offered rate was varied between 3 and 10 basis points--increases in offered rates appeared to put some upward pressure on unsecured money market rates, as anticipated, and the offered rate continued to provide a soft floor for secured rates. Changes in the spread between the rate paid on reserves and the ON RRP offered rate did not appear to affect the volume of activity in the federal funds market. While the tests of ON RRPs had been informative, the staff suggested that additional testing could further improve understanding of how this supplementary tool could be used to achieve greater control of the federal funds rate during policy normalization. Accordingly, participants discussed a draft resolution to extend the Desk's authority to conduct the ON RRP exercise for 12 months beyond the expiration of the current authorization on January 30, 2015. It was noted that a one-year extension to what had been a one-year testing program was a practical step and signaled nothing about either the timing of the start of policy normalization or how long an ON RRP facility might be needed.",
 '',
 'Following the discussion of the extension of ON RRP test operations, the Committee unanimously approved the following resolution:',
 '',
 '"The Federal Open Market Committee (FOMC) authorizes the Federal Reserve Bank of New York to conduct a series of overnight reverse repurchase operations involving U.S. government securities for the purpose of further assessing the appropriate structure of such operations in supporting the implementation of monetary policy during normalization. The reverse repurchase operations authorized by this resolution shall be (i) conducted at an offering rate that may vary from zero to five basis points; (ii) for an overnight term or such longer term as is warranted to accommodate weekend, holiday, and similar trading conventions; (iii) subject to a per-counterparty limit of up to $30 billion per day; (iv) subject to an overall size limit of up to $300 billion per day; and (v) awarded to all submitters (A) at the specified offering rate if the sum of the bids received is less than or equal to the overall size limit, or (B) at the stop-out rate, determined by evaluating bids in ascending order by submitted rate up to the point at which the total quantity of bids equals the overall size limit, with all bids below this rate awarded in full at the stop-out rate and all bids at the stop-out rate awarded on a pro rata basis, if the sum of the counterparty offers received is greater than the overall size limit. The Chair must approve any change in the offering rate within the range specified in (i) and any changes to the per-counterparty and overall size limits subject to the limits specified in (iii) and (iv). The System Open Market Account manager will notify the FOMC in advance about any changes to the offering rate, per-counterparty limit, or overall size limit applied to operations. These operations shall be authorized for one additional year beyond the previously authorized end date--that is, through January 29, 2016."',
 '',
 "By unanimous vote, the Committee ratified the Desk's domestic transactions over the intermeeting period. There were no intervention operations in foreign currencies for the System's account over the intermeeting period.",
 '',
 "The Board meeting concluded at the end of the discussion of developments in financial markets and the Federal Reserve's balance sheet.",
 '',
 'Staff Review of the Economic Situation',
 "The information reviewed for the December 16-17 meeting suggested that economic activity was increasing at a moderate pace in the fourth quarter and that labor market conditions had improved further. Consumer price inflation continued to run below the FOMC's longer-run objective of 2\xa0percent, partly restrained by declining energy prices. Market-based measures of inflation compensation moved lower, but survey measures of longer-run inflation expectations remained stable.",
 '',
 'Total nonfarm payroll employment expanded in October and November at a faster pace than in the third quarter. The unemployment rate edged down to 5.8\xa0percent in October and remained at that level in November. Both the labor force participation rate and the employment-to-population ratio rose slightly, and the share of workers employed part time for economic reasons declined. The rate of private-sector job openings stayed, on balance, at its recent elevated level in September and October, and the rates of hiring and of quits stepped up on net.',
 '',
 "Industrial production rose in October and November, led by strong increases in manufacturing output. Automakers' schedules indicated that the pace of light motor vehicle assemblies would move up somewhat in the first quarter, and broader indicators of manufacturing production, such as the readings on new orders from the national and regional manufacturing surveys, were generally consistent with solid gains in factory output over the near term.",
 '',
 "Real personal consumption expenditures (PCE) appeared to be rising robustly in the fourth quarter. The components of the nominal retail sales data used to construct estimates of PCE rose strongly in October and November, and light motor vehicle sales increased noticeably. Key factors that influence household spending pointed toward further solid PCE growth. Real disposable income rose further in October, energy prices continued to decline, households' net worth likely increased as home values advanced, and consumer sentiment in early December from the Thomson Reuters/University of Michigan Surveys of Consumers was at its highest level since before the most recent recession.",
 '',
 'The pace of activity in the housing sector generally\xa0remained slow. Both starts and permits of new single-family homes increased only a little, on balance, in October and November. Starts of multifamily units declined, on net, over the past two months. Sales of new and existing homes rose modestly in October.',
 '',
 "Real private expenditures for business equipment and intellectual property appeared to be decelerating in the fourth quarter. Nominal orders and shipments of nondefense capital goods excluding aircraft declined in October. However, new orders for these capital goods remained above the level of shipments, and other forward-looking indicators, such as national and regional surveys of business conditions, were generally consistent with modest near-term gains in business equipment spending. Firms' nominal spending for nonresidential structures edged down in October after rising slightly in the third quarter.",
 '',
 'Data for October and November pointed toward a decline in real federal government purchases in the fourth quarter after a surprisingly large third-quarter increase. Real state and local government purchases appeared to be rising modestly in the fourth quarter as their payrolls and construction expenditures increased a little in recent months.',
 '',
 'The U.S. international trade deficit was little changed in October, as exports and imports both rose. The gains in exports were concentrated in aircraft and other capital goods, and the increase in imports reflected a pickup in purchases of automotive products and computers. But with the October deficit remaining wider than the monthly average in the third quarter, real net exports looked to be declining in the fourth quarter.',
 '',
 "Both total U.S. consumer price inflation, as measured by the PCE price index, and core inflation, as measured by PCE prices excluding food and energy, were about 1-1/2 percent over the 12\xa0months ending in October; consumer energy prices declined, while consumer food prices rose more than overall prices. Over the 12 months ending in November, total inflation as measured by the consumer price index (CPI) was 1 1/4 percent, partly reflecting the further decline in energy prices, while core CPI inflation was 1-3/4 percent. Measures of expected long-run inflation from a variety of surveys, including the Michigan survey, the Blue Chip Economic Indicators, the Survey of Professional Forecasters, and the Desk's Survey of Primary Dealers, remained stable. In contrast, market-based measures of inflation compensation moved lower.\xa0",
 '',
 'Labor compensation continued to increase only a little faster than consumer prices. Compensation per hour in the nonfarm business sector rose about 2 percent over the year ending in the third quarter. Similar rates of increase were observed for the employment cost index over the same year-long period and for average hourly earnings for all employees over the 12 months ending in November.',
 '',
 'Overall growth in foreign real gross domestic product (GDP) remained subdued in the third quarter. In the advanced foreign economies, real GDP contracted for a second consecutive quarter in Japan, rose only slightly in the euro area, but continued to expand moderately in Canada and the United Kingdom. In the emerging market economies, economic growth slowed in Mexico in the third quarter and remained sluggish in Brazil; economic growth in China likely slowed moderately in the fourth quarter. Oil prices continued to decline, likely reflecting favorable supply developments as well as some weakening in global demand. Inflation in the advanced foreign economies remained quite low during the intermeeting period, partly because of the fall in oil prices. Declining oil prices had a smaller effect on inflation in the emerging market economies, reflecting the greater prevalence of administered energy prices.\xa0',
 '',
 'Staff Review of the Financial Situation',
 'Over the intermeeting period, market participants became a bit more optimistic about U.S. economic prospects while also responding to economic and policy developments abroad. The sharp decline in oil prices weighed on inflation compensation and left a mixed imprint on other asset markets. On net, yields on longer-term Treasury securities fell, corporate bond spreads widened, equity prices were little changed, and the foreign exchange value of the dollar appreciated.',
 '',
 'Economic data releases reinforced the views of market participants that the U.S. economic recovery continued to gain momentum. In addition, investors appeared to read the October FOMC statement as suggesting a slightly less accommodative path for future monetary policy than they had previously expected.',
 '',
 "Results from the December Survey of Primary Dealers indicated that the dealers' expectations for the timing of the first increase in the federal funds target range and the subsequent policy path were little changed from the October survey. The average probability distribution of the expected date of liftoff continued to imply that the most likely date would be around the middle of 2015, with the distribution having narrowed slightly compared with the previous survey.",
 '',
 'Longer-term nominal Treasury yields declined significantly, on balance, over the intermeeting period. Measures of inflation compensation based on Treasury Inflation-Protected Securities and on inflation swaps decreased, reportedly reflecting, in part, the decline in oil prices and increased concerns about global economic growth.',
 '',
 'Broad U.S. equity price indexes were about unchanged over the intermeeting period. Option-implied volatility for one-month returns on the S&P 500 index--the VIX--rose sharply late in the period to levels close to those in mid-October. Investment- and speculative-grade corporate bond spreads widened over the period. Spreads on speculative-grade bonds for energy-related firms rose substantially because of the pronounced decline in oil prices.',
 '',
 "Business financing flows were robust over the intermeeting period. Gross bond issuance by nonfinancial corporations was the strongest in more than a year. Nonfinancial commercial paper outstanding expanded noticeably in November, more than compensating for a slowdown in October. Commercial and industrial loans on banks' books continued to expand briskly. In addition, issuance of both leveraged loans and collateralized loan obligations were strong in October and November.",
 '',
 "Financing for commercial real estate (CRE) remained broadly available. CRE loans on banks' books expanded at a moderate pace in October and November, and issuance of commercial mortgage-backed securities (CMBS) was strong. According to the December Senior Credit Officer Opinion Survey on Dealer Financing Terms, broker-dealers had eased somewhat all of the terms on which they finance CMBS for most-favored clients.",
 '',
 'Measures of residential mortgage lending conditions were little changed over the intermeeting period. Credit conditions for mortgages remained tight for borrowers with less-than-pristine credit. Interest rates on 30-year fixed-rate mortgages declined, consistent with the moves in longer-term Treasury yields. Refinancing activity was subdued.',
 '',
 'Financing conditions in consumer credit markets generally stayed accommodative. Auto and student loan balances expanded robustly in October, and revolving credit balances increased at a moderate pace. Issuance of consumer asset-backed securities was strong in the fourth quarter.',
 '',

### Minutes startes with header sentences and details of the meeting location and timestamp. It also contains board members name. These details do not add any meaning for analysis and hence need to be removed as part of text cleaning.

In [14]:
## To check first few sentences in Minutes
txt=[]
minutes_df=fomc_new_df[fomc_new_df.Type=='Minute']
for m in range(len(minutes_df)):
  txt.append(minutes_df.Text.iloc[m].split('\n'))  ## Splitting

## Observation:<br>
1. In minutes there are many sentences including header of meeting, participants name and meeting location are present which does not add any meaning to the minutes content. These needs to be removed.
2. Below are few samples sentences<br>
   'Minutes of the Federal Open Market Committee'<br>
   'A meeting of the Federal Open Market Committee was held in the offices....'<br>
   'PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. Lockhart Mr. WarshMs. Yellen'<br>
   'Ms. Cumming, Mr. Fisher, Ms. Pianalto, and Messrs. Plosser and Stern, Alternate Members of the Federal Open Market Committee'

### These unneccessary sentences can be removed by direct delete and by using reular expression.

In [15]:
## Checking first sentrence of all minutes
for lst in txt:
  print(lst[0])

Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, December 13, 2011, at 8:30 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, December 13, 2011, at 8:30 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, November 1, 2011, at 10:30 a.m. and continued on Wednesday, November 2, 2011, at 8:30 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, September 20, 2011, at 10:30 a.m., and continued on Wednesday, September 21, 2011, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, August 9, 2011, at 8:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, August 9, 2011, at 8:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, June 21, 2011, at 10:30 a.m. and continued on Wednesday, June 22, 2011, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, April 26, 2011, at 10:30 a.m. and continued on Wednesday, April 27, 2011, at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, March 15, 2011, at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, January 25, 2011, at 1:00 p.m. and continued on Wednesday, January 26, 2011, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, December 14, 2010, at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, November 2, 2010, at 1:00 p.m. and continued on Wednesday, November 3, 2010, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, November 2, 2010, at 1:00 p.m. and continued on Wednesday, November 3, 2010, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, September 21, 2010, at 8:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, August 10, 2010, at 8:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, June 22, 2010, at 2:00 p.m. and continued on Wednesday, June 23, 2010, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, June 22, 2010, at 2:00 p.m. and continued on Wednesday, June 23, 2010, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, April 27, 2010, at 2:00 p.m. and continued on Wednesday, April 28, 2010, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, March 16, 2010, at 8:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, January 26, 2010, at 2:00 p.m. and continued on Wednesday, January 27, 2010, at 8:30 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, December 15, 2009, at 2:00 p.m. and continued on Wednesday, December 16, 2009, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, November 3, 2009, at 2:00 p.m. and continued on Wednesday, November 4, 2009, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, September 22, 2009, at 2:00 p.m. and continued on Wednesday, September 23, 2009, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, August 11, 2009, at 2:00 p.m. and continued on Wednesday, August 12, 2009, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, June 23, 2009, at 1:00 p.m. and continued on Wednesday, June 24, 2009, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, June 23, 2009, at 1:00 p.m. and continued on Wednesday, June 24, 2009, at 9:00 a.m.
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors in Washington, D.C., on Tuesday, April 28, 2009, at 2:00 p.m. and continued on Wednesday, April 29, 2009, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 17, 2009, at 2:00 p.m. and continued on Wednesday, March 18, 2009, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 17, 2009, at 2:00 p.m. and continued on Wednesday, March 18, 2009, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 27, 2009, at 1:30 p.m. and continued on Wednesday, January 28, 2009, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 27, 2009, at 1:30 p.m. and continued on Wednesday, January 28, 2009, at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Monday, December 15, 2008 at 2:00 p.m. and continued on Tuesday, December 16, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 28, 2008 at 2:00 p.m. and continued on Wednesday, October 29, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 28, 2008 at 2:00 p.m. and continued on Wednesday, October 29, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 28, 2008 at 2:00 p.m. and continued on Wednesday, October 29, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 16, 2008 at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, August 5, 2008 at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, August 5, 2008 at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 24, 2008 at 2:00 p.m. and continued on Wednesday, June 25, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, April 29, 2008 at 2:00 p.m. and continued on Wednesday, April 30, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 18, 2008 at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 18, 2008 at 8:30 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 29, 2008 at 2:00 p.m. and continued on Wednesday, January 30, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 29, 2008 at 2:00 p.m. and continued on Wednesday, January 30, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 29, 2008 at 2:00 p.m. and continued on Wednesday, January 30, 2008 at 9:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 11, 2007, at 8:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 11, 2007, at 8:00 a.m.
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 30, 2007 at 2:00 p.m. and continued on Wednesday, October 31, 2007 at 9:00 a.m.
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee
Minutes of the Federal Open Market Committee

#### Delete first default header of minutes.

In [16]:
## To delete first sentence of minutes as these are header of meetings.

txt_new = [lst[1:] for lst in txt]

## Re-checking post deletion of header
for lst in txt_new:
  print(lst[0])

PRESENT:Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT:Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT:Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT:Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. LockhartMr. Tarullo Mr. WarshMs. Yellen
PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. Lockhart Mr. WarshMs. Yellen
PRESENT: Mr. Bernanke, ChairmanMr. Dudley, Vice ChairmanMs. DukeMr. EvansMr. KohnMr. LackerMr. Lockhart Mr. WarshMs. Yellen
PRESENT:Mr. Bernanke, ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMs. Pianalto Mr. PlosserMr. SternMr. Warsh
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT:Mr. Bernanke, ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT: Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT: Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT:
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. EvansMr. HoenigMr. KohnMr. KrosznerMr. MishkinMr. PooleMr. RosengrenMr. Warsh Ms. Cumming, Mr. Fisher, Ms. Pianalto, and Messrs. Plosser and Stern, Alternate Members of the Federal Open Market CommitteeMessrs. Lacker and Lockhart, and Ms. Yellen, Presidents of the Federal Reserve Banks of Richmond, Atlanta, and San Francisco, respectively
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. EvansMr. HoenigMr. KohnMr. KrosznerMr. MishkinMr. PooleMr. RosengrenMr. Warsh Ms. Cumming, Mr. Fisher, Ms. Pianalto, and Messrs. Plosser and Stern, Alternate Members of the Federal Open Market CommitteeMessrs. Lacker and Lockhart, and Ms. Yellen, Presidents of the Federal Reserve Banks of Richmond, Atlanta, and San Francisco, respectively
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. EvansMr. HoenigMr. KohnMr. KrosznerMr. MishkinMr. PooleMr. RosengrenMr. Warsh

#### To remove white spaces and empty lines

In [17]:
## Removing white spaces and empty lines
for i in range(len(txt_new)):
  txt_new[i] = [sent.strip() for sent in txt_new[i] if sent.strip()]
## Re-checking post removal of empty lines and spaces
for lst in txt_new:
  print(lst[1])

A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 9, 2025, at 9:00 a.m. and continued on Wednesday, December 10, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, October 28, 2025, at 9:00 a.m. and continued on Wednesday, October 29, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 16, 2025, at 10:30 a.m. and continued on Wednesday, September 17, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 29, 2025, at 9:00 a.m. and continued on Wednesday, July 30, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 17, 2025, at 9:00 a.m. and continued on Wednesday, June 18, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, May 6, 2025, at 8:30 a.m. and continued on Wednesday, May 7, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 18, 2025, at 9:00 a.m. and continued on Wednesday, March 19, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on January 28, 2025, at 8:30 a.m. and continued on Wednesday, January 29, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 17, 2024, at 10:30 a.m. and continued on Wednesday, December 18, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Wednesday, November 6, 2024, at 10:00 a.m. and continued on Thursday, November 7, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 17, 2024, at 10:30 a.m. and continued on Wednesday, September 18, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 30, 2024, at 10:00 a.m. and continued on Wednesday, July 31, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 11, 2024, at 10:30 a.m. and continued on Wednesday, June 12, 2024, at 9:15 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, April 30, 2024, at 10:00 a.m. and continued on Wednesday, May 1, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 19, 2024, at 9:00 a.m. and continued on Wednesday, March 20, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, January 30, 2024, at 10:00 a.m. and continued on Wednesday, January 31, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 12, 2023, at 10:30 a.m. and continued on Wednesday, December 13, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, October 31, 2023, at 10:00 a.m. and continued on Wednesday, November 1, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 19, 2023, at 10:30 a.m. and continued on Wednesday, September 20, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 25, 2023, at 10:00 a.m. and continued on Wednesday, July 26, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 13, 2023, at 10:30 a.m. and continued on Wednesday, June 14, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, May 2, 2023, at 10:00 a.m. and continued on Wednesday, May 3, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 21, 2023, at 10:00 a.m. and continued on Wednesday, March 22, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, January 31, 2023, at 10:00 a.m. and continued on Wednesday, February 1, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 13, 2022, at 10:00 a.m. and continued on Wednesday, December 14, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, November 1, 2022, at 10:30 a.m. and continued on Wednesday, November 2, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 20, 2022, at 1:00 p.m. and continued on Wednesday, September 21, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 26, 2022, at 10:30 a.m. and continued on Wednesday, July 27, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 14, 2022, at 11:00 a.m. and continued on Wednesday, June 15, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, May 3, 2022, at 10:00 a.m. and continued on Wednesday, May 4, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 15, 2022, at 9:00 a.m. and continued on Wednesday, March 16, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, January 25, 2022, at 9:00 a.m. and continued on Wednesday, January 26, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, December 14, 2021, at 9:00 a.m. and continued on Wednesday, December 15, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, November 2, 2021, at 1:00 p.m. and continued on Wednesday, November 3, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, September 21, 2021, at 1:00 p.m. and continued on Wednesday, September 22, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, July 27, 2021, at 9:00 a.m. and continued on Wednesday, July 28, 2021, at 9:00 a.m.1
PRESENT:
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, April 27, 2021, at 9:30 a.m. and continued on Wednesday, April 28, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, March 16, 2021, at 11:00 a.m. and continued on Wednesday, March 17, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, January 26, 2021, at 1:00 p.m. and continued on Wednesday, January 27, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, December 15, 2020, at 1:00 p.m. and continued on Wednesday, December 16, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Wednesday, November 4, 2020, at 9:00 a.m. and continued on Thursday, November 5, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, September 15, 2020, at 11:00 a.m. and continued on Wednesday, September 16, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, July 28, 2020, at 10:00 a.m. and continued on Wednesday, July 29, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, June 9, 2020, at 10:00 a.m. and continued on Wednesday, June 10, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by conference call on Tuesday, April 28, 2020, at 1:00 p.m. and continued on Wednesday, April 29, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Sunday, March 15, 2020, at 10:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Sunday, March 15, 2020, at 10:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 28, 2020, at 10:00 a.m. and continued on Wednesday, January 29, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 10, 2019, at 10:00 a.m. and continued on Wednesday, December 11, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 29, 2019, at 9:00 a.m. and continued on Wednesday, October 30, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 29, 2019, at 9:00 a.m. and continued on Wednesday, October 30, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 17, 2019, at 10:15 a.m. and continued on Wednesday, September 18, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 30, 2019, at 10:00 a.m. and continued on Wednesday, July 31, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 18, 2019, at 10:30 a.m. and continued on Wednesday, June 19, 2019, at 9:00 a.m.1
PRESENT:
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 19, 2019, at 10:00 a.m. and continued on Wednesday, March 20, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 29, 2019, at 10:00 a.m. and continued on Wednesday, January 30, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 18, 2018, at 1:00 p.m. and continued on Wednesday, December 19, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Wednesday, November 7, 2018, at 1:00 p.m. and continued on Thursday, November 8, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 25, 2018, at 2:00 p.m. and continued on Wednesday, September 26, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 31, 2018, at 10:00 a.m. and continued on Wednesday, August 1, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 12, 2018, at 1:00 p.m. and continued on Wednesday, June 13, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, May 1, 2018, at 1:00 p.m. and continued on Wednesday, May 2, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 20, 2018, at 1:00 p.m. and continued on Wednesday, March 21, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 30, 2018, at 10:00 a.m. and continued on Wednesday, January 31, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 12, 2017, at 1:00 p.m. and continued on Wednesday, December 13, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 31, 2017, at 1:30 p.m. and continued on Wednesday, November 1, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 19, 2017, at 1:00 p.m. and continued on Wednesday, September 20, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 25, 2017, at 1:00 p.m. and continued on Wednesday, July 26, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 13, 2017, at 1:00 p.m. and continued on Wednesday, June 14, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, May 2, 2017, at 1:00 p.m. and continued on Wednesday, May 3, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 14, 2017, at 10:00 a.m. and continued on Wednesday, March 15, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 31, 2017, at 1:00 p.m. and continued on Wednesday, February 1, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 13, 2016, at 1:00 p.m. and continued on Wednesday, December 14, 2016, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, November 1, 2016, at 10:00 a.m. and continued on Wednesday, November 2, 2016, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 20, 2016, at 1:00 p.m. and continued on Wednesday, September 21, 2016, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 26, 2016, at 10:00 a.m. and continued on Wednesday, July 27, 2016, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 14, 2016, at 1:00 p.m. and continued on Wednesday, June 15, 2016, at 9:00 a.m.1

### Using regular expression to remove sentences starting with 'A joint meeting of the Federal Open Market Committee and the Board of Governors'

In [18]:
## Checking few samples of sentences starting with 'A joint meeting of the Federal Open Market Committee and the Board of Governors'
cnt=0
for i in range(len(txt_new)):
  for sent in txt_new[i]:
    if sent.lower().startswith('a joint meeting of the federal open market committee and the board of governors'):
      cnt+=1
      print(sent)
print(cnt)

A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 9, 2025, at 9:00 a.m. and continued on Wednesday, December 10, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, October 28, 2025, at 9:00 a.m. and continued on Wednesday, October 29, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 16, 2025, at 10:30 a.m. and continued on Wednesday, September 17, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 29, 2025, at 9:00 a.m. and continued on Wednesday, July 30, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 17, 2025, at 9:00 a.m. and continued on Wednesday, June 18, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, May 6, 2025, at 8:30 a.m. and continued on Wednesday, May 7, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 18, 2025, at 9:00 a.m. and continued on Wednesday, March 19, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on January 28, 2025, at 8:30 a.m. and continued on Wednesday, January 29, 2025, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 17, 2024, at 10:30 a.m. and continued on Wednesday, December 18, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Wednesday, November 6, 2024, at 10:00 a.m. and continued on Thursday, November 7, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 17, 2024, at 10:30 a.m. and continued on Wednesday, September 18, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 30, 2024, at 10:00 a.m. and continued on Wednesday, July 31, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 11, 2024, at 10:30 a.m. and continued on Wednesday, June 12, 2024, at 9:15 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, April 30, 2024, at 10:00 a.m. and continued on Wednesday, May 1, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 19, 2024, at 9:00 a.m. and continued on Wednesday, March 20, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, January 30, 2024, at 10:00 a.m. and continued on Wednesday, January 31, 2024, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 12, 2023, at 10:30 a.m. and continued on Wednesday, December 13, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, October 31, 2023, at 10:00 a.m. and continued on Wednesday, November 1, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 19, 2023, at 10:30 a.m. and continued on Wednesday, September 20, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 25, 2023, at 10:00 a.m. and continued on Wednesday, July 26, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 13, 2023, at 10:30 a.m. and continued on Wednesday, June 14, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, May 2, 2023, at 10:00 a.m. and continued on Wednesday, May 3, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 21, 2023, at 10:00 a.m. and continued on Wednesday, March 22, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, January 31, 2023, at 10:00 a.m. and continued on Wednesday, February 1, 2023, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, December 13, 2022, at 10:00 a.m. and continued on Wednesday, December 14, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, November 1, 2022, at 10:30 a.m. and continued on Wednesday, November 2, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, September 20, 2022, at 1:00 p.m. and continued on Wednesday, September 21, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, July 26, 2022, at 10:30 a.m. and continued on Wednesday, July 27, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, June 14, 2022, at 11:00 a.m. and continued on Wednesday, June 15, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, May 3, 2022, at 10:00 a.m. and continued on Wednesday, May 4, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, March 15, 2022, at 9:00 a.m. and continued on Wednesday, March 16, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, January 25, 2022, at 9:00 a.m. and continued on Wednesday, January 26, 2022, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, December 14, 2021, at 9:00 a.m. and continued on Wednesday, December 15, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on Tuesday, November 2, 2021, at 1:00 p.m. and continued on Wednesday, November 3, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, September 21, 2021, at 1:00 p.m. and continued on Wednesday, September 22, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held by videoconference on Tuesday, July 27, 2021, at 9:00 a.m. and continued on Wednesday, July 28, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, June 15, 2021, at 9:00 a.m. and continued on Wednesday, June 16, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, April 27, 2021, at 9:30 a.m. and continued on Wednesday, April 28, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, March 16, 2021, at 11:00 a.m. and continued on Wednesday, March 17, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, January 26, 2021, at 1:00 p.m. and continued on Wednesday, January 27, 2021, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, December 15, 2020, at 1:00 p.m. and continued on Wednesday, December 16, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Wednesday, November 4, 2020, at 9:00 a.m. and continued on Thursday, November 5, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, September 15, 2020, at 11:00 a.m. and continued on Wednesday, September 16, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, July 28, 2020, at 10:00 a.m. and continued on Wednesday, July 29, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Tuesday, June 9, 2020, at 10:00 a.m. and continued on Wednesday, June 10, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by conference call on Tuesday, April 28, 2020, at 1:00 p.m. and continued on Wednesday, April 29, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Sunday, March 15, 2020, at 10:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held by videoconference on Sunday, March 15, 2020, at 10:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 28, 2020, at 10:00 a.m. and continued on Wednesday, January 29, 2020, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 10, 2019, at 10:00 a.m. and continued on Wednesday, December 11, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 29, 2019, at 9:00 a.m. and continued on Wednesday, October 30, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 29, 2019, at 9:00 a.m. and continued on Wednesday, October 30, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 17, 2019, at 10:15 a.m. and continued on Wednesday, September 18, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 30, 2019, at 10:00 a.m. and continued on Wednesday, July 31, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 18, 2019, at 10:30 a.m. and continued on Wednesday, June 19, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, April 30, 2019, at 10:00 a.m. and continued on Wednesday, May 1, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 19, 2019, at 10:00 a.m. and continued on Wednesday, March 20, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 29, 2019, at 10:00 a.m. and continued on Wednesday, January 30, 2019, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 18, 2018, at 1:00 p.m. and continued on Wednesday, December 19, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Wednesday, November 7, 2018, at 1:00 p.m. and continued on Thursday, November 8, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 25, 2018, at 2:00 p.m. and continued on Wednesday, September 26, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 31, 2018, at 10:00 a.m. and continued on Wednesday, August 1, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 12, 2018, at 1:00 p.m. and continued on Wednesday, June 13, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, May 1, 2018, at 1:00 p.m. and continued on Wednesday, May 2, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 20, 2018, at 1:00 p.m. and continued on Wednesday, March 21, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 30, 2018, at 10:00 a.m. and continued on Wednesday, January 31, 2018, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 12, 2017, at 1:00 p.m. and continued on Wednesday, December 13, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, October 31, 2017, at 1:30 p.m. and continued on Wednesday, November 1, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 19, 2017, at 1:00 p.m. and continued on Wednesday, September 20, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, July 25, 2017, at 1:00 p.m. and continued on Wednesday, July 26, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, June 13, 2017, at 1:00 p.m. and continued on Wednesday, June 14, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, May 2, 2017, at 1:00 p.m. and continued on Wednesday, May 3, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, March 14, 2017, at 10:00 a.m. and continued on Wednesday, March 15, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, January 31, 2017, at 1:00 p.m. and continued on Wednesday, February 1, 2017, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, December 13, 2016, at 1:00 p.m. and continued on Wednesday, December 14, 2016, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, November 1, 2016, at 10:00 a.m. and continued on Wednesday, November 2, 2016, at 9:00 a.m.1
A joint meeting of the Federal Open Market Committee and the Board of Governors was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., on Tuesday, September 20, 2016, at 1:00 p.m. and continued on Wednesday, September 21, 2016, at 9:00 a.m.1

In [19]:
## Removing all the baove sentences starting with 'A joint meeting of the Federal Open Market Committee and the Board of Governors'

for i in range(len(txt_new)):
    txt_new[i] = [sent for sent in txt_new[i] if not sent.lower().startswith('a joint meeting of the federal open market committee and the board of governors')]

## Verify sentence post removal
cnt=0
for i in range(len(txt_new)):
  for sent in txt_new[i]:
    if sent.lower().startswith('a joint meeting of the federal open market committee and the board of governors'):
      cnt+=1
      print(sent)
print(cnt)

0

#### Using regular expression to remove sentences starting with 'A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors'

In [20]:
## Removing all the sentences starting with 'A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors'

for i in range(len(txt_new)):
    txt_new[i] = [sent for sent in txt_new[i] if not sent.lower().startswith('a meeting of the federal open market committee was held in the offices of the board of governors')]

## Verify sentence post removal
cnt=0
for i in range(len(txt_new)):
  for sent in txt_new[i]:
    if sent.lower().startswith('a meeting of the federal open market committee was held in the offices of the board of governors'):
      cnt+=1
      print(sent)
print(cnt)

0

#### Using regular expression to remove senetnces with strings 'A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors' post meeting date.

In [21]:
## Removing all the sentences having string 'A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors'
## post meeting date.

string = 'a meeting of the federal open market committee was held in the offices of the board of governors'

for i in range(len(txt_new)):
    txt_new[i] = [sent for sent in txt_new[i] if string not in sent.lower()]


cnt=0
for i in range(len(txt_new)):
  for sent in txt_new[i]:
    if string in sent.lower():
      cnt+=1
      print(sent)
print(cnt)

0

In [22]:
## To check the paragraphs that starts with 'PRESENT' or 'ATTENDANCE' or sentences with participants name.

import re
pattern=re.compile(r"^(ms|mr|messrs|chair|vice chair|governer|secretary|deputy secretary|assistant secretary|general counsel|deputy general counsel|economist|manager|deputy manager)\b")
cnt=0
sent_remove=[]
for i in range(len(txt_new)):
  for sent in txt_new[i]:
    if sent.lower().startswith(('present','attendance')):
      cnt+=1
      # print(sent)
      sent_remove.append(sent)
    elif bool(pattern.search(sent.lower())):
      ## To retain sentences that have Secretary's note and Mr. Lacker actions as these are relevant content.
      if len(sent.split())<50 and not sent.lower().startswith(("secretary's note","mr. lacker dissented because")):
        cnt+=1
        # print(sent)
        sent_remove.append(sent)

print('\n'.join(sent_remove[700:900]))  ## Sample check to verfiy that relevant content are not removed.
print(cnt)

Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Mr. Gagnon, Visiting Associate Director, Division of Monetary Affairs, Board of Governors
Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Oliner, Senior Adviser, Division of Research and Statistics, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Mr. Carlson, Economist, Division of Monetary Affairs, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Mr. Moore, First Vice President, Federal Reserve Bank of San Francisco
Mr. Judd, Executive Vice President, Federal Reserve Bank of San Francisco
Mr. Altig, Ms. Baum, Messrs. Rasche, Schweitzer, Sellon, and Tootell, Senior Vice Presidents, Federal Reserve Banks of Atlanta, New York, St. Louis, Cleveland, Kansas City, and Boston, respectively
Mr. Krane, Vice President, Federal Reserve Bank of Chicago
Mr. Chatterjee, Senior Economic Adviser, Federal Reserve Bank of Philadelphia
Mr. Wolman, Senior Economist, Federal Reserve Bank of Richmond
Ms. Cumming voted as the alternate for Mr. Geithner.
PRESENT: Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Bullard, Hoenig, and Rosengren, Presidents of the Federal Reserve Banks of St. Louis, Kansas City, and Boston, respectively
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Ashton, Assistant General CounselMr. Sheets, Economist
Messrs. Connors, English, Kamin, Sniderman, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Ms. Bailey, Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Ms. Liang, Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Levin, Deputy Associate Director, Division of Monetary Affairs, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Ms. Wei, Economist, Division of Monetary Affairs, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Mr. Connolly, First Vice President, Federal Reserve Bank of Boston
Messrs. Fuhrer and Judd, Executive Vice Presidents, Federal Reserve Banks of Boston and San Francisco, respectively
Messrs. Altig, Hakkio, Rasche, and Sullivan, Senior Vice Presidents, Federal Reserve Banks of Atlanta, Kansas City, St. Louis, and Chicago, respectively
Messrs. Danzig and Duca, Vice Presidents, Federal Reserve Banks of New York and Dallas, respectively
Mr. Weber, Senior Research Officer, Federal Reserve Bank of Minneapolis
Mr. Hetzel, Senior Economist, Federal Reserve Bank of Richmond
Mr. Sill, Economic Advisor, Federal Reserve Bank of Philadelphia
Mr. Del Negro, Officer, Federal Reserve Bank of New York
PRESENT: Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMs. DukeMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Bullard, Hoenig, and Rosengren, Presidents of the Federal Reserve Banks of St. Louis, Kansas City, and Boston, respectively
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Ashton, Assistant General CounselMr. Sheets, Economist
Messrs. Connors, English, Kamin, Sniderman, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Ms. Bailey, Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Ms. Liang, Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Levin, Deputy Associate Director, Division of Monetary Affairs, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Ms. Wei, Economist, Division of Monetary Affairs, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Mr. Connolly, First Vice President, Federal Reserve Bank of Boston
Messrs. Fuhrer and Judd, Executive Vice Presidents, Federal Reserve Banks of Boston and San Francisco, respectively
Messrs. Altig, Hakkio, Rasche, and Sullivan, Senior Vice Presidents, Federal Reserve Banks of Atlanta, Kansas City, St. Louis, and Chicago, respectively
Messrs. Danzig and Duca, Vice Presidents, Federal Reserve Banks of New York and Dallas, respectively
Mr. Weber, Senior Research Officer, Federal Reserve Bank of Minneapolis
Mr. Hetzel, Senior Economist, Federal Reserve Bank of Richmond
Mr. Sill, Economic Advisor, Federal Reserve Bank of Philadelphia
Mr. Del Negro, Officer, Federal Reserve Bank of New York
PRESENT:
Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Ms. Cumming, Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Bullard, Hoenig, and Rosengren, Presidents of the Federal Reserve Banks of St. Louis, Kansas City, and Boston, respectively
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Baxter, Deputy General CounselMr. Sheets, Economist Mr. Stockton, Economist
Messrs. Connors, English, and Kamin, Ms. Mester, Messrs. Rolnick, Rosenblum, Slifman, Tracy, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Ms. J. Johnson,1 Secretary, Office of the Secretary, Board of Governors
Mr. Cole, Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Mr. Frierson,1 Deputy Secretary, Office of the Secretary, Board of Governors
Ms. Bailey,1 Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Clouse, Deputy Director, Division of Monetary Affairs, Board of Governors
Mr. Parkinson,1 Deputy Director, Division of Research and Statistics, Board of Governors
Ms. Barger,1 Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Stehm,1 Associate Director, Division of Reserve Bank Operations and Payment Systems, Board of Governors
Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Gagnon,2 Visiting Associate Director, Division of Monetary Affairs, Board of Governors
Mr. Wright, Deputy Associate Director, Division of Monetary Affairs, Board of Governors
Mr. Zakrajek, Assistant Director, Division of Monetary Affairs, Board of Governors
Mr. Erceg,2 Assistant Director, Division of International Finance, Board of Governors
Mr. Oliner, Senior Adviser, Division of Research and Statistics, Board of Governors
Mr. Gross,1 Special Assistant to the Board, Office of Board Members, Board of Governors
Ms. Tevlin,2 Senior Economist, Division of Research and Statistics, Board of Governors
Mr. Ammer,2 Senior Economist, Division of International Finance, Board of Governors
Ms. Beechey, Economist, Division of Monetary Affairs, Board of Governors
Ms. Dykes, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Ms. Beattie,1 Assistant to the Secretary, Office of the Secretary, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Ms. Hughes,1 Staff Assistant, Office of the Secretary, Board of Governors
Mr. Barron, First Vice President, Federal Reserve Bank of Atlanta
Mr. Fuhrer, Executive Vice President, Federal Reserve Bank of Boston
Messrs. Altig, Angulo,1 Rasche, Schweitzer, Sellon, and Weinberg, Senior Vice Presidents, Federal Reserve Banks of Atlanta, New York, St. Louis, Cleveland, Kansas City, and Richmond, respectively
Messrs. Fernald and Fisher, and Ms. McLaughlin, Vice Presidents, Federal Reserve Banks of San Francisco, Chicago, and New York, respectively
PRESENT:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Ms. Cumming, Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Bullard, Hoenig, and Rosengren, Presidents of the Federal Reserve Banks of St. Louis, Kansas City, and Boston, respectively
Mr. Lyon, First Vice President, Federal Reserve Bank of Minneapolis
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Baxter, Deputy General CounselMr. Sheets, Economist Mr. Stockton, Economist
Messrs. Connors, English, and Kamin, Ms. Mester, Messrs. Rosenblum, Slifman, Sniderman, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Ms. J. Johnson,1 Secretary, Office of the Secretary, Board of Governors
Ms. Roseman,1 Director, Division of Reserve Bank Operations and Payment Systems, Board of Governors
Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Mr. Frierson,1 Deputy Secretary, Office of the Secretary, Board of Governors
Ms. Bailey, Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Clouse, Deputy Director, Division of Monetary Affairs, Board of Governors
Messrs. Hammond1 and Marquardt,1 Deputy Directors, Division of Reserve Bank Operations and Payment Systems, Board of Governors
Ms. Edwards,1 Associate Director, Division of Monetary Affairs, Board of Governors
Ms. Shanks,1 Associate Secretary, Office of the Secretary, Board of Governors
Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Gagnon, Visiting Associate Director, Division of Monetary Affairs, Board of GovernorsMs. Martin,1 Associate General Counsel, Legal Division, Board of Governors
Mr. Carpenter,1 Assistant Director, Division of Monetary Affairs, Board of Governors
Mr. Dale, Senior Adviser, Division of Monetary Affairs, Board of Governors
Mr. Oliner, Senior Adviser, Division of Research and Statistics, Board of Governors
Ms. Allison,1 Senior Counsel, Legal Division, Board of Governors
Mr. Gross,1 Special Assistant to the Board, Office of Board Members, Board of Governors
Ms. Weinbach, Adviser, Division of Monetary Affairs, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Ms. Beattie,1 Assistant to the Secretary, Office of the Secretary, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Ms. Hughes,1 Staff Assistant, Office of the Secretary, Board of Governors
Mr. Fuhrer, Executive Vice President, Federal Reserve Bank of Boston
Messrs. Hilton, McAndrews,1 Rasche, Rudebusch, Steindel, Sullivan, and Weinberg, Senior Vice Presidents, Federal Reserve Banks of New York, New York, St. Louis, San Francisco, New York, Chicago, and Richmond, respectively
Messrs. Clark and Meyer,1 Vice Presidents, Federal Reserve Banks of Kansas City and Philadelphia, respectively
Mr. Weber, Senior Research Officer, Federal Reserve Bank of Minneapolis
Mr. Roberds, Policy Adviser, Federal Reserve Bank of Atlanta
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Hoenig and Rosengren, Presidents of the Federal Reserve Banks of Kansas City and Boston, respectively
Mr. Sapenaro, First Vice President, Federal Reserve Bank of St. Louis
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Ashton, Assistant General CounselMr. Sheets, Economist Mr. Stockton, Economist
Messrs. Connors, English, and Kamin, Ms. Mester, Messrs. Rolnick, Rosenblum, Slifman, Sniderman, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Mr. Parkinson, Deputy Director, Division of Research and Statistics, Board of Governors
Ms. Bailey, Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Clouse, Deputy Director, Division of Monetary Affairs, Board of Governors
Ms. Liang and Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Gagnon, Visiting Associate Director, Division of Monetary Affairs, Board of Governors
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Mr. Carpenter, Assistant Director, Division of Monetary Affairs, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Mr. Judd, Executive Vice President, Federal Reserve Bank of San Francisco
Messrs. Altig, Rasche, Sellon, and Sullivan, Senior Vice Presidents, Federal Reserve Banks of Atlanta, St. Louis, Kansas City, and Chicago, respectively
Mr. Olivei, Vice President, Federal Reserve Bank of Boston
Mr. Pesenti, Assistant Vice President, Federal Reserve Bank of New York
Mr. Hetzel, Senior Economist, Federal Reserve Bank of Richmond
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. Pianalto Mr. PlosserMr. SternMr. Warsh
Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Hoenig and Rosengren, Presidents of the Federal Reserve Banks of Kansas City and Boston, respectively
Mr. Sapenaro, First Vice President, Federal Reserve Bank of St. Louis
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Ashton, Assistant General CounselMr. Sheets, Economist Mr. Stockton, Economist
Messrs. Connors, English, and Kamin, Ms. Mester, Messrs. Rolnick, Rosenblum, Slifman, Sniderman, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Mr. Struckmeyer, Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Mr. Parkinson, Deputy Director, Division of Research and Statistics, Board of Governors
Ms. Bailey, Deputy Director, Division of Banking Supervision and Regulation, Board of Governors
Mr. Clouse, Deputy Director, Division of Monetary Affairs, Board of Governors
Ms. Liang and Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Mr. Gagnon, Visiting Associate Director, Division of Monetary Affairs, Board of Governors
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Mr. Carpenter, Assistant Director, Division of Monetary Affairs, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Luecke, Section Chief, Division of Monetary Affairs, Board of Governors
Ms. Low, Open Market Secretariat Specialist, Division of Monetary Affairs, Board of Governors
Mr. Judd, Executive Vice President, Federal Reserve Bank of San Francisco
Messrs. Altig, Rasche, Sellon, and Sullivan, Senior Vice Presidents, Federal Reserve Banks of Atlanta, St. Louis, Kansas City, and Chicago, respectively
Mr. Olivei, Vice President, Federal Reserve Bank of Boston
Mr. Pesenti, Assistant Vice President, Federal Reserve Bank of New York
Mr. Hetzel, Senior Economist, Federal Reserve Bank of Richmond
Present:Mr. Bernanke, ChairmanMr. Geithner, Vice ChairmanMr. FisherMr. KohnMr. KrosznerMr. MishkinMs. PianaltoMr. PlosserMr. SternMr. Warsh
Messrs. Evans, Lacker, and Lockhart, and Ms. Yellen, Alternate Members of the Federal Open Market Committee
Messrs. Hoenig, Poole, and Rosengren, Presidents of the Federal Reserve Banks of Kansas City, St. Louis, and Boston, respectively
Mr. Madigan, Secretary and EconomistMs. Danker, Deputy SecretaryMr. Skidmore, Assistant SecretaryMs. Smith, Assistant SecretaryMr. Alvarez, General CounselMr. Baxter, Deputy General CounselMr. Sheets, EconomistMr. Stockton, Economist
Messrs. Connors, English, and Kamin, Ms. Mester, Messrs. Rosenblum, Slifman, Sniderman, Tracy, and Wilcox, Associate Economists
Mr. Dudley, Manager, System Open Market Account
Mr. Struckmeyer,1 Deputy Staff Director, Office of Staff Director for Management, Board of Governors
Mr. Parkinson,2 Deputy Director, Division of Research and Statistics, Board of Governors
Mr. Clouse, Senior Associate Director, Division of Monetary Affairs, Board of Governors
Ms. Liang and Messrs. Reifschneider and Wascher, Associate Directors, Division of Research and Statistics, Board of Governors
Ms. Barger2 and Mr. Greenlee,2 Associate Directors, Division of Banking Supervision and Regulation, Board of Governors
Mr. Gibson,2 Deputy Associate Director, Division of Research and Statistics, Board of Governors
Mr. Dale, Senior Adviser, Division of Monetary Affairs, Board of Governors
Mr. Oliner, Senior Adviser, Division of Research and Statistics, Board of Governors
Messrs. Durham and Perli, Assistant Directors, Division of Monetary Affairs, Board of Governors
Mr. Blanchard, Assistant to the Board, Office of Board Members, Board of Governors
Mr. Small, Project Manager, Division of Monetary Affairs, Board of Governors
Mr. Bassett,3 Senior Economist, Division of Monetary Affairs, Board of Governors
Mr. Doyle,3 Senior Economist, Division of International Finance, Board of Governors
Ms. Kusko, 3 Senior Economist, Division of Research and Statistics, Board of Governors
Mr. Luecke, Senior Financial Analyst, Division of Monetary Affairs, Board of Governors
Mr. Driscoll, Economist, Division of Monetary Affairs, Board of Governors
3696

#### Using regular expression to remove participants name from Minutes and other irrelevant content from Minutes. There are total 3696 such sentences that needs to be removed.

In [23]:
## To remove the paragraphs that starts with 'PRESENT' or 'ATTENDANCE' or sentences with participants name.

pattern=re.compile(r"^(ms|mr|messrs|chair|vice chair|governer|secretary|deputy secretary|assistant secretary|general counsel|deputy general counsel|economist|manager|deputy manager)\b")
txt_new_final = [None] * len(txt_new)
for i in range(len(txt_new)):
  cleaned_txt=[]
  for sent in txt_new[i]:
    if sent.lower().startswith(('present','attendance')):
      continue
    elif bool(pattern.search(sent.lower())):
      if len(sent.split())<50 and not sent.lower().startswith(("secretary's note","mr. lacker dissented because")):
        continue
    cleaned_txt.append(sent)
  txt_new_final[i]=cleaned_txt

## To verify that cleaned text corpus does not have above mentioned irrelevant data.

cnt=0
sent_remove=[]
for i in range(len(txt_new_final)):
  for sent in txt_new_final[i]:
    if sent.lower().startswith(('present','attendance')):
      cnt+=1
      sent_remove.append(sent)
    elif bool(pattern.search(sent.lower())):
      ## To retain sentences that have Secretary's note and Mr. Lacker actions as these are relevant content.
      if len(sent.split())<50 and not sent.lower().startswith(("secretary's note","mr. lacker dissented because")):
        cnt+=1
        sent_remove.append(sent)
print(cnt)

0

In [24]:
## Minutes from July 2024 till Jan 2026 now contains cleaned content.
## However, documents previous to July 2024 still have participants name as they don't have initials and hence not removed in previous step.

ptrn1=re.compile(r"^([A-Z][a-z]+(?:\s+[A-Z]\.)?(?:\s+[A-Z][a-z]+)?)"
    r"(?:\s*,\s*(?:and\s+)?[A-Z][a-z]+(?:\s+[A-Z]\.)?(?:\s+[A-Z][a-z]+)?)+")

cnt=0
sent_remove=[]
for i in range(len(txt_new_final)):
  for sent in txt_new_final[i]:
    if bool(ptrn1.search(sent)):
      cnt+=1
      sent_remove.append(sent)
print(cnt)

4407

#### There are total 4407 sentences that have participants name without initials which are to be removed using regex.

In [25]:
## To remove the paragraphs that have participants name.

ptrn1=re.compile(r"^([A-Z][a-z]+(?:\s+[A-Z]\.)?(?:\s+[A-Z][a-z]+)?)"
    r"(?:\s*,\s*(?:and\s+)?[A-Z][a-z]+(?:\s+[A-Z]\.)?(?:\s+[A-Z][a-z]+)?)+")


txt_new_finalversion = [None] * len(txt_new_final)
for i in range(len(txt_new_final)):
  cleaned_txt=[]
  for sent in txt_new_final[i]:
    if bool(ptrn1.search(sent)):
      continue
    cleaned_txt.append(sent)
  txt_new_finalversion[i]=cleaned_txt

## To verify that cleaned text corpus does not have above mentioned irrelevant data.

cnt=0
sent_remove=[]
for i in range(len(txt_new_finalversion)):
  for sent in txt_new_finalversion[i]:
    if bool(ptrn1.search(sent)):
      cnt+=1
      sent_remove.append(sent)
print(cnt)

0

In [26]:
txt_new_finalversion[200] ## Randomly checking contents of minutes

['August 12, 2003',
 'By unanimous vote, Charles L. Evans and Brian F. Madigan were elected as Associate Economists of the Committee to serve until the election of their successors at the first regularly scheduled meeting of the Committee after December 31, 2003, with the understanding that in the event of the discontinuance of their official connection with the Board of Governors or with a Federal Reserve Bank, they would cease to have any official connection with the Federal Open Market Committee.',
 "The Manager of the System Open Market Account reported on recent developments in foreign exchange markets.  There were no open market operations in foreign currencies for the System's account in the period since the previous meeting.",
 'The Manager also reported on developments in domestic financial markets and on System open market transactions in government securities and securities issued or fully guaranteed by federal agencies during the period May 6, 2003, through June 24, 2003.  By unanimous vote, the Committee ratified these transactions.',
 'The information reviewed at this meeting suggested that economic activity was mixed in late spring and early summer.  The labor market remained weak, and industrial production improved only slightly.  Consumer spending, however, advanced further, with brisk growth in expenditures on autos and other durables and more modest expansion in other categories.  Homebuilding continued at a robust rate, business spending improved somewhat, and federal government expenditures remained elevated, but these gains were partially offset by fiscal restraint at the state and local government levels.  Despite a recent uptick in consumer prices, year-over-year consumer inflation remained at a very low level.',
 'Private nonfarm payroll employment fell in both June and July.  Notable losses occurred in manufacturing over the two months, continuing the trend of previous months.  Wholesale and retail trade, transportation and utilities, as well as information sectors also reduced their workforces further, while the construction, financial activities, and temporary help sectors continued to add jobs.  The average workweek edged down, on net, over June and July.  After rising to 6.4 percent in June, the unemployment rate fell to 6.2 percent in July.',
 'Industrial production edged up again in June, with gains in manufacturing offset to some extent by significant weather-related declines in utility production.  Available data for July indicated advances in motor vehicle assemblies and in iron and steel output, and also a surge in energy production that was due to abnormally warm weather. Overall industry capacity utilization was about unchanged in June as higher usage in manufacturing and mining was balanced by a sharp decrease at utilities.',
 'Real personal consumption expenditures grew in June and in the second quarter as a whole, largely reflecting a brisk rise in purchases of motor vehicles and other durable goods.  Consumption of other goods rose more moderately.  Declines in spending on energy in June held down growth in services expenditures.  Real disposable income posted a modest gain in the second quarter, and likely was lifted further in July by reduced tax withholding and by refund checks that were mailed out.  Consumer confidence readings were mixed in June and July but remained well above their lows earlier in the year.',
 'Boosted by declining mortgage rates, housing construction and sales were robust through June.  Single-family housing starts rose in June to one of the highest levels in the past twenty-five years, and new permit issuance was also strong.  Multifamily housing starts stayed at about the average level of the previous year and a half.  New home sales surged in June, but existing home sales edged down.',
 'Business outlays on equipment and software jumped in the second quarter following a lackluster performance over the preceding half year.  Spending on computers and software accelerated sharply, and purchases of communications equipment increased considerably.  The transportation category, by contrast, contracted as business spending on motor vehicles stagnated and investment in aircraft decreased.  Data on orders and shipments for nondefense capital goods in June pointed to growth in nearly all categories.  Expenditures on nonresidential structures turned up in the second quarter as increases in spending on institutional and other structures more than offset declines in expenditures for office and industrial buildings.  Office building vacancy rates changed little in the second quarter, while vacancies in industrial buildings rose to record levels.',
 'Nonfarm inventories shrank in the second quarter, with notable declines in manufacturing and wholesale stocks.  Inventories relative to shipments and sales were at low levels by historical standards.',
 'The U.S. international trade deficit edged up in May as imports of goods and services increased slightly more than exports.  Recent data generally indicated that growth in foreign industrial countries was weak in the second quarter.  The economies of Japan and the euro area appeared to have remained stagnant. Canadian economic growth was held back by both the SARS outbreak and the discovery of mad cow disease, although a rebound in employment in June suggested that the weakness was temporary.  GDP growth in the United Kingdom showed a moderate rebound in the second quarter.',
 'Overall consumer prices rose a bit in June, led by increases in the volatile food and energy categories.  Core consumer prices, however, were unchanged for the month.  Over the twelve-month period ending in June, the increase in core consumer prices as measured by both the consumer price index and the chain-type personal consumption expenditure index was notably lower than the rise of the previous year.  Higher energy costs pushed up the producer price index in June, but core producer prices ticked down for the month, leaving them slightly below their levels twelve months prior.  With regard to labor costs, July average hourly earnings of production or nonsupervisory workers on private nonfarm payrolls advanced at about the same rate as in June.  The employment cost index for hourly compensation of private industry workers rose less in the second quarter than in the first quarter.  The twelve-month increase was somewhat lower than that for the previous year.',
 'At its meeting on June 24-25, the Committee adopted a directive that called for lowering the target for the intended federal funds rate 25 basis points, to 1 percent.  In reaching this decision, the Committee members generally perceived the upside and downside risks to the attainment of sustainable growth for the next few quarters as roughly equal; however, they viewed the probability, though minor, of a substantial and unwelcome fall in inflation as exceeding that of a pickup in inflation from its already low level.  On balance, the Committee believed that the concern about appreciable disinflation was likely to predominate for the foreseeable future.',
 "Longer-term interest rates began to back up after the announcement of the Committee's decision, as market participants had placed substantial odds on a larger policy move and, perhaps, even the release of details on potential unconventional policy actions.  Ten-year Treasury yields rose dramatically over the following weeks.  The increase appeared to be based on a number of factors, including investors' interpretation of the Chairman's congressional testimony, the release of Committee members' relatively bullish economic projections, and incoming news regarding the economy and corporate earnings that was seen as signaling a more likely upturn in economic growth.  In these circumstances, substantial further disinflation probably would not materialize, and the need for further reductions in the federal funds rate or unconventional policy measures would thus be obviated.  Yields on high-grade corporate bonds moved up roughly in line with those on Treasury securities, leaving spreads about unchanged.  Rates on low-grade corporate bonds rose much less, and spreads over Treasuries on such obligations narrowed significantly.  Despite the sharp step-up in Treasury yields, broad equity indexes advanced over the intermeeting period, supported by positive earning reports, strong profit forecasts, and increased confidence regarding economic prospects.",
 'The exchange value of the dollar, as measured by the major foreign currencies index, rose over the intermeeting period as long-term interest rate differentials moved sharply in favor of dollar-denominated assets.  Yields on longer-dated government debt of major foreign economies also increased as did many foreign equity indexes.',
 'M2 continued to grow briskly in June and July, reflecting in large part the near-zero opportunity cost of holding money, the effects of mortgage refinancing activity, and the reduction in personal income tax withholdings.',
 'The staff forecast prepared for this meeting continued to suggest that the economic expansion would strengthen substantially as the year progressed.  Accommodative financial conditions, recent additional fiscal stimulus, and robust gains in structural productivity would provide significant impetus to business and consumer spending over the months ahead.  Concurrently, household expenditures, buoyed by recent tax cuts, were expected to be well maintained.  Inventory levels had been substantially reduced, and business capital stocks apparently had continued to move closer to acceptable levels.  As a consequence, improving sales and profits, low financing costs, and the temporary federal tax incentive for investment in new equipment and software were expected to boost business investment spending gradually.  Given the substantial ongoing slack in resource utilization, some downward pressure on core price inflation was considered a risk in the staff forecast.',
 "In their review of current and prospective economic developments, members commented that they were encouraged by the recent data on economic activity and the tone of related anecdotal commentary.  In their view these developments, in the context of stimulative fiscal and monetary policies, receptive financial conditions, and apparently improving business and consumer confidence, had brightened the prospects for substantial further strengthening of the economy. The members acknowledged that the magnitude of the improvement remained subject to considerable uncertainty, notably with regard to the prospects for business expenditures, and they cited both upside and downside risks to forecasts of a more vigorous expansion. Concerning the prospects for inflation, members expressed the view that even if growth somewhat above the economy's potential were to materialize over the next several quarters, which many regarded as a likely scenario, substantial excess margins of labor and other resources would remain and would continue to hold down overall inflation. Indeed, a number of members saw merit in the staff forecast that some further disinflation was a likely prospect in such circumstances.",
 'Members commented that current financial conditions remained a positive factor in the outlook for the economy even after the recent rise in long-term interest rates.  To be sure, the increase would have some restraining effect.  Indeed, mortgage refinancing activity appeared to have declined substantially according to some reports, prospectively lessening the support for some consumer and other spending fostered by the extraction of equity from housing. Even so, a number of factors suggested that the risks from higher interest rates might not be large. These included the possibility that the higher rates in part reflected growing optimism about the economic outlook that would engender a faster pace of business spending, more than offsetting the effects of the higher rates on consumer spending. Moreover, long-term interest rates were still relatively low, risk spreads had narrowed in recent months, and stock prices had held firm recently, perhaps in part as a result of several upside surprises in second-quarter profit reports.',
 'Several members reiterated that business spending was the critical factor that would',
 'govern to a substantial degree the timing and extent of the acceleration in overall economic activity.  Since the year 2000, business capital expenditures had been mostly limited to replacement demand for equipment and software and, with nonresidential construction activity displaying pronounced weakness, total business fixed investment had until recently been on a declining trend. Members were encouraged, however, by evidence in recent months that an upswing in spending for capital equipment and software might be under way, including more purchases by firms of non-high-tech equipment as well as an ongoing rise in purchases of computing equipment and related peripherals. Members also reported some signs of renewed venture capital activity. Several noted that nonresidential building appeared to have stabilized in various parts of the country after a long period of decline, and there were reports that new construction projects had been initiated in some areas. It was clear, nonetheless, that business sentiment toward capital expenditures remained exceptionally cautious. Looking ahead, much would depend on further growth in demand for business products and services and associated evidence of rising profits, building on indications of strengthening in both in recent months. For now, survey and anecdotal reports on business capital spending intentions were somewhat more encouraging than earlier but were still generally mixed, with only a small number of firms planning robust capital spending programs.  Indeed, in light of the persistence of substantial margins of underutilized capital, many business contacts indicated that they intended to meet growing demand by adding staff before increasing output capacity.',
 'The weakness in business inventories that had damped the expansion thus far this year appeared to be continuing in the current quarter according to numerous business contacts. However, cautious inventory policies generally had reduced stocks to very low levels in relation to growing sales, and members saw inventory accumulation, starting perhaps late this year, as a plausible expectation. Indeed, in the view of some members, a normal cyclical swing in the accumulation of inventories that would bring the latter into a more usual alignment with growing sales could begin relatively soon and might well be markedly more pronounced than many now anticipated.  The potential for such a development constituted a sizable upside risk to current  economic forecasts for the quarters ahead.',
 'Consumer spending, buttressed by sales of motor vehicles and other consumer durables, had accelerated in the second quarter from an already elevated level and appeared more recently to be increasing considerably further. The available data pointing to improvement in early summer were limited but were supported by anecdotal information from around the country. Positive factors mentioned with regard to the outlook for the consumer sector included the recent tax cuts, the improved performance of the stock market, the ample availability of household credit, and more generally the effects of rapidly rising productivity in sustaining growth in household incomes. A potential negative cited by some members was the possibility that a weak job market, should it persist, would at some point adversely affect overall consumer sentiment and willingness to spend.',
 'Residential housing sales and construction had remained at elevated levels, evidently stimulated to an important extent by earlier declines in mortgage rates to unusually low levels. Although the appreciable upturn in those rates since midyear appeared to have slowed mortgage refinancing activity, at least in some areas, housing demand had remained buoyant perhaps in part because many homebuyers were attempting to lock in mortgage financing while rates were still low in relation to historical norms. The potential extent of retardation in housing activity stemming from higher mortgage rates was uncertain, but demand for housing was expected to be relatively well maintained, assuming the realization of forecasts of accelerating economic activity and associated growth in personal incomes.',
 "In their comments about the outlook for the foreign sector of the economy, members referred to recent signs of some strengthening in the economies of the nation's important trading partners. However, domestic demand in most of those economies remained relatively weak, and developments abroad were likely to provide little impetus to demand for U.S. exports in the near term.  At this point, business contacts tended to emphasize the persistence of strong foreign competition that was constraining their sales in both foreign and domestic markets.",
 'In their review of the outlook for prices, members generally anticipated that key inflation measures would remain near their currently low levels for an extended period. Their assessment focused on the likely persistence of substantial margins of unemployed labor and other resources even if, in line with their expectations, business activity strengthened substantially over coming quarters. Indeed, a number of members expressed the view that some further disinflation was probable over the year ahead. To be sure, inflation would remain subject to a number of crosscurrents. Upward pressures on prices would continue to be exerted by increasing medical insurance and pension costs and, for many manufacturing firms, the rising cost of materials. At the same time, the persistence of very strong competitive pressures, including those arising from foreign competitors, was preventing most business firms from passing on higher costs by raising prices, and this lack of pricing power did not appear to be diminishing. Concurrently, however, many firms were able to maintain or even to increase their profit margins through a variety of cost-cutting and productivity-enhancing measures.',
 "In the Committee's discussion of policy for the intermeeting period ahead, all the members endorsed a proposal to maintain an unchanged policy stance involving reserve conditions consistent with a target federal funds rate of 1 percent. Members noted that the current stance of monetary policy remained quite accommodative and, given the tenor of the latest information on the performance of the economy in the context of generally favorable financial conditions, they believed that policy was appropriately positioned to foster further strengthening of the economic expansion. While the Committee could not commit itself to a particular policy course over time, many of the members referred to the likelihood that the Committee would want to keep policy accommodative for a longer period than had been the practice in past periods of accelerating economic activity. Reasons for such an approach to policy stemmed from the need to encourage progress toward closing the economy's currently wide output gap and, with inflation already near the low end of what some members regarded as an acceptable range, to resist significant further disinflation. In the view of these members, appreciable added disinflation would potentially blunt the effectiveness of further policy easing in the event of strong adverse shocks to the economy. At the same time, maintaining an accommodative policy stance was seen as involving little risk of inducing rising inflation so long as high levels of excess capacity and very competitive markets continued to characterize economic conditions.",

### Now we have cleaned FOMC minutes which can be used for chunking and embeddings.

In [27]:
len(txt_new_finalversion)

238

In [28]:
txt_new_finalversion[0]

['December 9â\x80\x9310, 2025',
 'Developments in Financial Markets and Open Market Operations',
 "The manager turned first to an overview of broad market developments during the intermeeting period. Market participants did not materially change their macroeconomic outlooks and continued to interpret data made available over the intermeeting period as consistent with a resilient economy. Investors' expectations for the path of the policy rate, whether market based or survey based, were little changed, on net, over the period. Market participants and respondents to the Open Market Desk's Survey of Market Expectations (Desk survey) generally expected a 25 basis point reduction in the target range for the federal funds rate at the December FOMC meeting, and the modal outlook from the survey as well as from options pricing implied two additional rate cuts next year.",
 'The manager turned next to developments in Treasury markets and market-based measures of inflation compensation. Treasury yields rose a little over the intermeeting period, on net, but remained within recent ranges. Inflation compensation moved lower over the period, particularly for shorter tenors. The manager attributed the decline in inflation compensation at shorter tenors to lower energy prices as well as a reassessment by some market participants of the likely effect of tariffs on near-term inflation. In contrast to market-based measures of inflation compensation, survey- and model- based measures of inflation expectations were little changed over the intermeeting period.',
 'Broad equity price indexes were volatile but changed little, on net, over the intermeeting period. Equity prices showed sensitivity to economic data and policymaker communications. Developments regarding artificial intelligence (AI) also contributed to the volatility of the stock prices of the largest technology companies. The manager noted that capital expenditures on equipment and infrastructure related to AI by a set of large technology companies accelerated this year and that these firms were increasingly relying on debt to finance such expenditures.',
 'Regarding international developments, the trade-weighted dollar index was little changed over the intermeeting period. Outside forecasters continued to expect that the dollar would depreciate modestly next year. Many of these forecasters expected a larger reduction in policy rates in the U.S. than in other advanced-economy jurisdictions, though their confidence in this view appeared to diminish somewhat in light of the resilience of the U.S. economy.',
 'The manager noted that money market conditions continued to tighten over the intermeeting period and that the staff assessed that conditions were consistent with the level of reserves having declined to the ample region. Rates on Treasury repurchase agreements (repo) remained relatively elevated and volatile over the intermeeting period. Investors attributed firmness in repo rates to a decline in available liquidity and continued large Treasury debt issuance. Higher repo rates, along with a lower level of reserves, continued to contribute to upward pressure on the spread between the effective federal funds rate (EFFR) and the interest rate on reserve balances. The manager noted that the correlation between this spread and the level of reserve balances had risen notably over the past couple of months and that the EFFR had moved up faster than it had during the previous episode of balance sheet runoff. Consistent with elevated repo rates, usage of overnight reverse repo operations remained low, while both the frequency and volume of standing repo operations increased over the intermeeting period. Some other key indicators of reserve ampleness, such as the share of payments by banks occurring later in the day and the share of domestic banks borrowing in the federal funds market, also pointed to ample reserve conditions.',
 "The manager next discussed the expected trajectory of key components of the Federal Reserve's balance sheet. Over the next several months, seasonal fluctuations in nonreserve liabilities were projected to lead to significant declines in reserves at the end of December, in late January, and especially in mid-to-late April if securities holdings in the System Open Market Account (SOMA) were to remain unchanged. The manager noted that the projected fall in reserves in April caused by tax inflows to the Treasury General Account (TGA)â\x80\x94which is a Federal Reserve liabilityâ\x80\x94was particularly large and thus judged that reserves were likely to fall below the ample range if the size of the SOMA portfolio were to remain unchanged.",
 'In light of this projected decline in reserves as well as recent developments in money markets, the manager recommended that the Committee consider starting reserve management purchases (RMPs) this month to maintain an ample level of reserves on an ongoing basis. Because of the substantial projected decline in reserves in mid-to-late April, the manager judged that it would be prudent to start RMPs soon, maintain a somewhat elevated pace of net purchases until then, and then decrease the monthly pace substantially thereafter. Respondents to the Desk survey expected RMPs to begin soon. Over one-third of respondents expected RMPs to be announced at this meeting and begin by next month, and most respondents anticipated them to begin before the end of the first quarter of 2026. While the estimated size of expected purchases varied considerably across respondents, on average, respondents anticipated net purchases of about $220 billion over the first 12 months of purchases.',
 "The manager then turned to a discussion of standing repo operations and the essential role they play in supporting the implementation of monetary policy. While usage of these operations had increased recently, there had been days when a large volume of repo trades occurred well above the operations' minimum bid rate, suggesting reluctance by some potential participants to engage in standing repo operations. Market outreach suggested that this reluctance reflected misperceptions about the intended purpose of standing repo operations and that the effectiveness of these operations could be enhanced by Federal Reserve communications that explicitly clarified that the purpose of the operations is to support monetary policy implementation. Market participants also suggested that reluctance to use standing repo operations reflected in part specific operational features, and they offered a number of suggestions to enhance the effectiveness of the operations, such as allowing them to be centrally cleared and eliminating the aggregate limit of $500 billion per day. Given the importance of standing repo operations for monetary policy implementation, the manager proposed to clarify their intended role in official communications, convey the expectation that they would be used when economically sensible, and eliminate their aggregate limit.",
 "By unanimous vote, the Committee ratified the Desk's domestic transactions over the intermeeting period. There were no intervention operations in foreign currencies for the System's account during the intermeeting period.",
 'Special Topic: Balance Sheet Issues',
 "Participants discussed developments in money markets and whether starting RMPs was warranted to maintain reserves at levels consistent with the Committee's ample-reserves framework laid out in its 2019 Statement Regarding Monetary Policy Implementation and Balance Sheet Normalization. With the continued increases in the spreads between money market interest rates and administered rates, as well as some other indicators of tightening money market conditions, participants judged that reserve balances had declined to ample levels. Accordingly, participants assessed that it was appropriate to begin RMPs and initiate purchases of shorter-term Treasury securities to maintain an ample supply of reserves over time.",
 "The discussion was preceded by staff presentations. The staff emphasized that a range of levels of reserve balances was consistent with ample and presented indicators showing that money market conditions pointed to reserves being within the ample range. In particular, the spreads of the EFFR and of other money market rates to the interest rate on reserve balances had increased relatively quickly since mid-September. Additionally, several other indicators of liquidity in short-term funding markets, including the volatility of repo rates and their sensitivity to Treasury coupon issuance, pointed to reserves being within the ample range. The staff emphasized the role that standing repo operations had played in ensuring that the federal funds rate remained within its target range, even on days of elevated demand for nonreserve liabilities. The staff also noted the implications of reserves varying within the ample range for volatility and market functioning in money markets, the size of the Federal Reserve's balance sheet, and the use of standing repo operations.",
 "The staff noted that maintaining ample reserves over time would require the SOMA security portfolio to expand to accommodate trend growth in the demand for reserves and nonreserve liabilities. In addition, under the ample-reserves framework, the size of the SOMA portfolio would need to be sufficient to accommodate significant seasonal variation in the demand for nonreserve liabilities, such as that driven by fluctuations in TGA balances. The staff presented options for how the Desk could structure RMPs to maintain an ample supply of reserves. They noted the benefits of granting the Desk flexibility to adjust the sizes of RMPs in anticipation of or in response to swings in reserve demand and the demand for nonreserve liabilities. The staff also noted that, consistent with the goal of returning to a primarily Treasury portfolio expressed in the Committee's 2022 Principles for Reducing the Size of the Federal Reserve's Balance Sheet and a preference to shift the SOMA portfolio composition toward that of Treasury securities outstanding, RMPs could be conducted primarily in Treasury bills.",
 "Participants agreed that recent money market conditions pointed to reserves being within the ample range and that beginning RMPs would be prudent to maintain a supply of ample reserves. A couple of participants remarked that the recent increase in the spread between the EFFR and the interest rate on reserve balances had been faster than during the Federal Reserve's 2017â\x80\x9319 runoff experience, and a couple of participants observed that triparty repo rates had been averaging somewhat above the interest rate on reserve balances. Participants expressed their preferences for purchases to be in Treasury bills so that the SOMA portfolio composition would begin to shift toward that of Treasury securities outstanding, though no decision was made on the composition of the portfolio in the long run. Policymakers generally emphasized the importance of communicating that RMPs would be made solely to ensure interest rate control and smooth market functioning and had no implications for the stance of monetary policy.",
 'Participants generally agreed that providing the Desk flexibility to adjust the size and timing of RMPs was important because of the significant variation in the demand for Federal Reserve liabilities and the uncertainty surrounding projections of this demand. When discussing how to structure RMPs in light of this variation, several participants emphasized that they preferred to front-load purchases so that the total level of reserves supplied to the market would be enough to manage large anticipated seasonal swings in nonreserve liabilities without having to rely on standing repo operations. Some other participants, however, preferred to limit balance sheet size by conducting RMPs closer to periods of elevated demand for nonreserve liabilities and relying more on standing repo operations to damp upward pressure on rates. Several participants noted that aligning variation in SOMA Treasury bill holdings with variation in nonreserve liabilities would insulate reserve supply from TGA changes, citing research by the Federal Reserve staff.',
 'Participants also discussed the role of standing repo operations and commented on their importance for interest rate control in the ample-reserves regime. Some participants emphasized their preference that standing repo operations play a more active role in rate control, with material usage during periods of elevated pressures in money markets. A couple of participants added that effective standing repo operations may allow for a smaller balance sheet on average. Several participants preferred to rely more on RMPs to maintain an ample level of reserves.',
 'Various participants noted that a more precise definition of "ample" would help clarify the Committee\'s intentions in implementing an ample-reserves framework. A few participants noted the difficulties of aiming to target an appropriate level of reserves because of the potential shifts in reserve demand. Some participants offered a view that an ample-reserves definition should focus on the level of money market rates in relation to the interest rate on reserve balances, with a few of those participants highlighting that such an approach would avoid some of the challenges of targeting a particular level of reserves given potential shifts in reserve demand. A couple of participants expressed the view that a definition of "ample reserves" that resulted in a larger supply of reserves than necessary to implement the Committee\'s framework could lead to excessive risk-taking by leveraged investors.',
 'Staff Review of the Economic Situation',
 'The information available at the time of the meeting indicated that real gross domestic product (GDP) had expanded moderately over this year. The unemployment rate had edged up and the pace of payroll employment increases had slowed through September; more recent labor market indicators were consistent with these developments. Consumer price inflation had moved up since earlier in the year and remained somewhat elevated.',
 "The unemployment rate ticked up to 4.4 percent in September, continuing the gradual upward trend seen since the middle of the year. The average monthly pace of total payroll gains continued to be slower in the third quarter than early in the year. Other available labor market indicatorsâ\x80\x94such as initial claims for unemployment insurance benefits, rates of job openings and layoffs, and survey measures of households' and businesses' perceptions of the balance between labor demand and supplyâ\x80\x94were consistent with a gradual cooling in labor market conditions since September. The employment cost index for total private-sector labor compensation rose 3.5 percent over the 12 months ending in September, and average hourly earnings for all employees increased 3.8 percent over the same 12-month period. Both measures of hourly labor compensation growth were close to their year-earlier rates.",
 'Total consumer price inflationâ\x80\x94as measured by the 12â\x80\x91month change in the price index for personal consumption expenditures (PCE)â\x80\x94was 2.8 percent in September. Core PCE price inflation, which excludes changes in consumer energy prices and many consumer food prices, was also 2.8 percent in September. Both total and core PCE price inflation were somewhat higher than earlier in the year. Core services price inflation had moved down, but core goods price inflation had picked up, which the staff largely attributed to the effects of higher tariffs.',
 'The available indicators suggested that real GDP growth was solid in the third quarter, although the average rate of increase over the first three quarters of the year was moderate and slower than its 2024 pace. Real private domestic final purchasesâ\x80\x94which comprises PCE and private fixed investment spending and which often provides a better signal of underlying economic momentum than does GDPâ\x80\x94appeared to have risen faster than GDP over the first three quarters of the year but also had slowed relative to last year. Real goods imports declined in August, reversing the increase in the preceding month, while real goods exports edged down further. The federal government shutdown was expected to reduce real GDP growth around 1 percentage point in the fourth quarter, with a corresponding boost to output growth in the first quarter of 2026.',
 'Foreign economic activity continued to expand at a below-trend pace in the third quarter, with real GDP having contracted in Mexico and Japan and having grown at only a lackluster pace in Europe. By contrast, economic activity in emerging Asia remained robust amid continued strong external demand for high-tech products and Chinese firms having boosted exports to markets other than the U.S.',
 'Headline inflation continued to run near central bank targets in many foreign economies, aided by declines in global energy prices so far this year. Core inflation, however, remained persistently elevated in some economies. A few foreign central banks reduced their policy rates, including the Bank of Canada and the Bank of Mexico, with most others leaving them unchanged.',
 'Staff Review of the Financial Situation',
 'Over the intermeeting period, both the market-implied expected path of the federal funds rate and nominal Treasury yields edged up on net. Changes in nominal yields reflected increases in real yields, while inflation compensation declined a bit, especially at shorter horizons. Broad equity prices were little changed. While the one-month option-implied volatility on the S&P 500 index at one point reached its highest level since early April, it ended the period roughly unchanged. Investment- and speculative-grade corporate bond spreads increased somewhat but remained at low levels.',
 'In foreign financial markets, longer-term yields increased notably over the intermeeting period because of various country-specific factors, including stronger-than-expected employment gains in Canada and rising odds of further monetary policy tightening and fiscal expansion in Japan. In addition, in the euro area, stronger-than-expected data on economic activity and European Central Bank communications regarded as signaling less accommodative policy contributed to rising yields. Foreign equity indexes and the broad dollar index were little changed, on net, over the intermeeting period.',
 "Conditions in U.S. short-term funding markets remained orderly but were generally tighter over the intermeeting period. In secured markets, liquidity conditions were tighter, on average, amid robust Treasury issuance, declining reserve balances in recent months, and month-end pressures. Over the intermeeting period, the average level of reserve balances was around $2.9 trillion, about $500 billion lower relative to the level of reserve balances at the start of the Federal Reserve's balance sheet reductions in June 2022.",
 'In domestic credit markets, conditions for businesses, households, and municipalities were little changed on balance. Financing conditions remained somewhat restrictive for households and small businesses. Meanwhile, large and midsize businesses continued to access credit markets at a solid pace. Credit performance was largely unchanged, with delinquency rates for small businesses, commercial real estate (CRE), and consumer loans remaining elevated. Yields on corporate bonds increased somewhat. Rates on 30-year fixed-rate conforming residential mortgages, as well as yields on non-agency commercial mortgage-backed securities (CMBS), rose moderately.',

In [29]:
## Updating the cleaned Minute documents in the dataframe.

ind=fomc_new_df[fomc_new_df['Type']=='Minute'].index.to_list()

m=0
for i in ind:
  fomc_new_df.loc[i,'Text_Clean']="\n".join(txt_new_finalversion[m])
  m+=1

#### Column Text_Clean in dataframe now contains clean relevant content in Minutes.

## Chunking of FOMC documents

In [30]:
## FOMC statements and minutes consists of section header and contents and there are no tables or chart.
## Thus chunking based on section or paragraph level will be suitable for FOMC documents.

def minutes_chunks(index):
  section_header='Opening_Section'
  chunks=[]
  content=[]
  lines=fomc_new_df.iloc[index].Text_Clean.split('\n')
  for sent in lines:
    if not sent.endswith('.') and len(sent.split(' '))<25 and sum(1 for w in sent.split() if w[0].isupper())/len(sent.split())>0.7:
      if content:
        chunks.append({'section_header':section_header,'section_content':'\n'.join(content),'token_length':len(('\n'.join(content)).split(' '))})
        section_header=sent
        content=[]
      else:
        content.append(sent)
    else:
      content.append(sent)
  if content:
    chunks.append({'section_header':section_header,'section_content':'\n'.join(content),'token_length':len(('\n'.join(content)).split(' '))})
  return chunks

In [31]:
# section_chunk = list(minutes_chunks(0)[0].values())
# list(section_chunk[0].values())

section_chunk = minutes_chunks(0)
# list(section_chunk[0].values())[0]
for i in range(len(section_chunk)):
  print(list(section_chunk[i].values())[0])
  # print(lst)

Opening_Section
Developments in Financial Markets and Open Market Operations
Special Topic: Balance Sheet Issues
Staff Economic Outlook

In [32]:
fomc_new_df.head()

,Date,Release Date,Type,Text,doc_id,Text_Clean
0,2025-12-10,2025-12-30,Minute,Minutes of the Federal Open Market Committee\n...,M_251210,"December 9â10, 2025\nDevelopments in Financi..."
1,2025-12-10,2025-12-10,Statement,Available indicators suggest that economic act...,S_251210,Available indicators suggest that economic act...
2,2025-10-29,2025-10-29,Statement,Available indicators suggest that economic act...,S_251029,Available indicators suggest that economic act...
3,2025-10-29,2025-11-19,Minute,Minutes of the Federal Open Market Committee\n...,M_251029,"October 28â29, 2025\nDevelopments in Financi..."
4,2025-09-17,2025-09-17,Statement,Recent indicators suggest that growth of econo...,S_250917,Recent indicators suggest that growth of econo...

In [33]:
## Call chunking function for each minutes and store section chunks in new dataframe. For Statements, entire document is stored as one chunk as it has less words.

fomc_chunk_dict=[]
for idx in range(fomc_new_df.shape[0]):
  if fomc_new_df.iloc[idx].Type=='Minute':
    section_chunk = minutes_chunks(idx)
    for i in range(len(section_chunk)):
      fomc_chunk_dict.append({
          "doc_id":fomc_new_df.iloc[idx].doc_id,
          "meeting_date":fomc_new_df.iloc[idx].Date,
          "release_date":fomc_new_df.iloc[idx]['Release Date'],
          "doc_type":fomc_new_df.iloc[idx].Type,
          "chunk_id":f"{fomc_new_df.iloc[idx].doc_id}_chunk_{i+1}",
          "section_header":(list(section_chunk[i].values())[0]),
          "chunked_text":(list(section_chunk[i].values())[1]),
          "word_count":(list(section_chunk[i].values())[2])
        })
  else:
    fomc_chunk_dict.append({
          "doc_id":fomc_new_df.iloc[idx].doc_id,
          "meeting_date":fomc_new_df.iloc[idx].Date,
          "release_date":fomc_new_df.iloc[idx]['Release Date'],
          "doc_type":fomc_new_df.iloc[idx].Type,
          "chunk_id":f"{fomc_new_df.iloc[idx].doc_id}_chunk_1",
          "section_header":"Full Statement Doc",
          "chunked_text":fomc_new_df.iloc[idx].Text,
          "word_count":len(fomc_new_df.iloc[idx].Text.split())
        })



fomc_chunk_df=pd.DataFrame(fomc_chunk_dict)

In [34]:
fomc_chunk_df.shape  ## There are total 2354 chunks created of FOMC documents from 2000 to 2026.

(2354, 8)

In [35]:
fomc_chunk_df.head(20)

,doc_id,meeting_date,release_date,doc_type,chunk_id,section_header,chunked_text,word_count
0,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_1,Opening_Section,"December 9â10, 2025",3
1,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2,Developments in Financial Markets and Open Mar...,The manager turned first to an overview of bro...,1056
2,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3,Special Topic: Balance Sheet Issues,Participants discussed developments in money m...,2001
3,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_4,Staff Economic Outlook,Relative to the forecast prepared for the Octo...,1675
4,S_251210,2025-12-10,2025-12-10,Statement,S_251210_chunk_1,Full Statement Doc,Available indicators suggest that economic act...,402
5,S_251029,2025-10-29,2025-10-29,Statement,S_251029_chunk_1,Full Statement Doc,Available indicators suggest that economic act...,382
6,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_1,Opening_Section,"October 28â29, 2025",3
7,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_2,Developments in Financial Markets and Open Mar...,The manager turned first to an overview of bro...,904
8,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_3,Special Topic: The Standing Repo Facility,"The staff provided background on the SRF, incl...",193
9,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_4,Special Topic: Balance Sheet Issues,"The FOMC's ""Plans for Reducing the Size of the...",2169
10,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_5,Staff Economic Outlook,Relative to the forecast prepared for the Sept...,1429
11,S_250917,2025-09-17,2025-09-17,Statement,S_250917_chunk_1,Full Statement Doc,Recent indicators suggest that growth of econo...,351
12,M_250917,2025-09-17,2025-10-08,Minute,M_250917_chunk_1,Opening_Section,"September 16â17, 2025",3
13,M_250917,2025-09-17,2025-10-08,Minute,M_250917_chunk_2,Developments in Financial Markets and Open Mar...,The deputy manager turned first to an overview...,2107
14,M_250917,2025-09-17,2025-10-08,Minute,M_250917_chunk_3,Staff Economic Outlook,Compared with the staff forecast prepared for ...,2023
15,M_250917,2025-09-17,2025-10-08,Minute,M_250917_chunk_4,Committee Policy Actions,In their discussions of monetary policy for th...,678
16,S_250730,2025-07-30,2025-07-30,Statement,S_250730_chunk_1,Full Statement Doc,Although swings in net exports continue to aff...,341
17,M_250730,2025-07-30,2025-08-20,Minute,M_250730_chunk_1,Opening_Section,"July 29â30, 2025",3
18,M_250730,2025-07-30,2025-08-20,Minute,M_250730_chunk_2,"Review of Monetary Policy Strategy, Tools, and...",Participants continued their discussion relate...,101
19,M_250730,2025-07-30,2025-08-20,Minute,M_250730_chunk_3,Developments in Financial Markets and Open Mar...,The manager turned first to a review of financ...,2345

In [36]:
fomc_chunk_df[fomc_chunk_df['word_count']>1000]

,doc_id,meeting_date,release_date,doc_type,chunk_id,section_header,chunked_text,word_count
1,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2,Developments in Financial Markets and Open Mar...,The manager turned first to an overview of bro...,1056
2,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3,Special Topic: Balance Sheet Issues,Participants discussed developments in money m...,2001
3,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_4,Staff Economic Outlook,Relative to the forecast prepared for the Octo...,1675
9,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_4,Special Topic: Balance Sheet Issues,"The FOMC's ""Plans for Reducing the Size of the...",2169
10,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_5,Staff Economic Outlook,Relative to the forecast prepared for the Sept...,1429
...,...,...,...,...,...,...,...,...
2328,M_000822,2000-08-22,2000-10-05,Minute,M_000822_chunk_2,Members of the Federal Open Market Committee,Monetary Affairs and Research and Statistics r...,3840
2332,M_000628,2000-06-28,2000-08-24,Minute,M_000628_chunk_3,"and Simpson, Associate Economists",Monetary Affairs and Research and Statistics r...,3824
2336,M_000516,2000-05-16,2000-06-29,Minute,M_000516_chunk_1,Opening_Section,"May 16, 2000\nThe Manager of the System Open M...",3550
2339,M_000321,2000-03-21,2000-05-18,Minute,M_000321_chunk_1,Opening_Section,"March 21, 2000\nThe Manager of the System Open...",4045
2352,M_000202,2000-02-02,2000-03-23,Minute,M_000202_chunk_12,PROCEDURAL INSTRUCTIONS WITH RESPECT TO FOREIG...,In conducting operations pursuant to the autho...,1816

## Need to split chunks that have word length greater than 500 into '500' equal word length chunks for better performance.

In [37]:
def chunk_split_greater_than_1000(text):
  splt=[]
  for i in range(0,len(text.split()),500):
    splt.append(' '.join(text.split()[i:i+500]))
  return splt


fomc_chunk_dict_new=[]

for idx in range(fomc_chunk_df.shape[0]):
  if fomc_chunk_df.iloc[idx].word_count>500:
    split_text= chunk_split_greater_than_1000(fomc_chunk_df.iloc[idx].chunked_text)
    for i in range(len(split_text)):
      fomc_chunk_dict_new.append({
          "doc_id":fomc_chunk_df.iloc[idx].doc_id,
          "meeting_date":fomc_chunk_df.iloc[idx].meeting_date,
          "release_date":fomc_chunk_df.iloc[idx].release_date,
          "doc_type":fomc_chunk_df.iloc[idx].doc_type,
          "chunk_id":f"{fomc_chunk_df.iloc[idx].chunk_id}_{chr(96+i+1)}",
          "section_header":fomc_chunk_df.iloc[idx].section_header,
          "chunked_text":split_text[i],
          "word_count":len(split_text[i].split())
        })
  else:
    fomc_chunk_dict_new.append({
          "doc_id":fomc_chunk_df.iloc[idx].doc_id,
          "meeting_date":fomc_chunk_df.iloc[idx].meeting_date,
          "release_date":fomc_chunk_df.iloc[idx].release_date,
          "doc_type":fomc_chunk_df.iloc[idx].doc_type,
          "chunk_id":fomc_chunk_df.iloc[idx].chunk_id,
          "section_header":fomc_chunk_df.iloc[idx].section_header,
          "chunked_text":fomc_chunk_df.iloc[idx].chunked_text,
          "word_count":fomc_chunk_df.iloc[idx].word_count
        })

fomc_chunk_new_df=pd.DataFrame(fomc_chunk_dict_new)

In [38]:
fomc_chunk_new_df.head(20)

,doc_id,meeting_date,release_date,doc_type,chunk_id,section_header,chunked_text,word_count
0,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_1,Opening_Section,"December 9â10, 2025",3
1,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2_a,Developments in Financial Markets and Open Mar...,The manager turned first to an overview of bro...,500
2,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2_b,Developments in Financial Markets and Open Mar...,previous episode of balance sheet runoff. Cons...,500
3,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2_c,Developments in Financial Markets and Open Mar...,standing repo operations for monetary policy i...,64
4,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3_a,Special Topic: Balance Sheet Issues,Participants discussed developments in money m...,500
5,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3_b,Special Topic: Balance Sheet Issues,observed that triparty repo rates had been ave...,500
6,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3_c,Special Topic: Balance Sheet Issues,the pace of payroll employment increases had s...,500
7,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3_d,Special Topic: Balance Sheet Issues,"and the Bank of Mexico, with most others leavi...",500
8,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3_e,Special Topic: Balance Sheet Issues,rates had moved sideways since the beginning o...,21
9,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_4_a,Staff Economic Outlook,Relative to the forecast prepared for the Octo...,500
10,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_4_b,Staff Economic Outlook,time and had not moved closer to the 2 percent...,500
11,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_4_c,Staff Economic Outlook,the labor market remained tilted to the downsi...,500
12,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_4_d,Staff Economic Outlook,"funds rate at this meeting, while some preferr...",188
13,S_251210,2025-12-10,2025-12-10,Statement,S_251210_chunk_1,Full Statement Doc,Available indicators suggest that economic act...,402
14,S_251029,2025-10-29,2025-10-29,Statement,S_251029_chunk_1,Full Statement Doc,Available indicators suggest that economic act...,382
15,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_1,Opening_Section,"October 28â29, 2025",3
16,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_2_a,Developments in Financial Markets and Open Mar...,The manager turned first to an overview of bro...,500
17,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_2_b,Developments in Financial Markets and Open Mar...,"payments by banks shifted to later in the day,...",413
18,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_3,Special Topic: The Standing Repo Facility,"The staff provided background on the SRF, incl...",193
19,M_251029,2025-10-29,2025-11-19,Minute,M_251029_chunk_4_a,Special Topic: Balance Sheet Issues,"The FOMC's ""Plans for Reducing the Size of the...",500

In [39]:
fomc_chunk_new_df.shape

(4060, 8)

### Now we have total 4060 chunks of less than or equal to 500 word length.

### To remove chunks with word length less than 10 as these chunks are not relevant to original minute content , example board member name.

In [40]:
fomc_chunk_new_df[fomc_chunk_new_df['word_count']<10].sort_values(by='word_count',ascending=False)

,doc_id,meeting_date,release_date,doc_type,chunk_id,section_header,chunked_text,word_count
3921,M_010320,2001-03-20,2001-05-17,Minute,M_010320_chunk_3_b,Telephone Conferences,to reduce the discount rate by 50 basis points.,9
3910,M_010411,2001-04-11,2001-05-02,Minute,M_010411_chunk_3_b,Telephone Conferences,to reduce the discount rate by 50 basis points.,9
733,M_210728,2021-07-28,2021-08-18,Minute,M_210728_chunk_10,"Erin E. Ferris2 and Andrei Zlate, Principal Ec...","Isabel Cairó, Senior Economist, Division of Mo...",9
177,M_240612,2024-06-12,2024-07-03,Minute,M_240612_chunk_8,"Beth Anne Wilson, Economist","Julie Ann Remache, Deputy Manager, System Open...",9
3899,M_010418,2001-04-18,2001-05-09,Minute,M_010418_chunk_3_b,Telephone Conferences,to reduce the discount rate by 50 basis points.,9
...,...,...,...,...,...,...,...,...
1564,M_170201,2017-02-01,2017-02-22,Minute,M_170201_chunk_8,Janet L. Yellen,Chairman,1
1227,M_190130,2019-01-30,2019-02-20,Minute,M_190130_chunk_11,Jerome H. Powell,Chairman,1
2929,M_090116,2009-01-16,2009-02-06,Minute,M_090116_chunk_2,Ben S. Bernanke,Chairman,1
3439,M_050202,2005-02-02,2005-02-23,Minute,M_050202_chunk_4,Alan Greenspan,Chairman,1
3676,M_030129,2003-01-29,2003-03-20,Minute,M_030129_chunk_4,Alan Greenspan,Chairman,1

In [41]:
fomc_chunk_new_df[fomc_chunk_new_df['word_count']<10].sort_values(by='word_count',ascending=False)

,doc_id,meeting_date,release_date,doc_type,chunk_id,section_header,chunked_text,word_count
3921,M_010320,2001-03-20,2001-05-17,Minute,M_010320_chunk_3_b,Telephone Conferences,to reduce the discount rate by 50 basis points.,9
3910,M_010411,2001-04-11,2001-05-02,Minute,M_010411_chunk_3_b,Telephone Conferences,to reduce the discount rate by 50 basis points.,9
733,M_210728,2021-07-28,2021-08-18,Minute,M_210728_chunk_10,"Erin E. Ferris2 and Andrei Zlate, Principal Ec...","Isabel Cairó, Senior Economist, Division of Mo...",9
177,M_240612,2024-06-12,2024-07-03,Minute,M_240612_chunk_8,"Beth Anne Wilson, Economist","Julie Ann Remache, Deputy Manager, System Open...",9
3899,M_010418,2001-04-18,2001-05-09,Minute,M_010418_chunk_3_b,Telephone Conferences,to reduce the discount rate by 50 basis points.,9
...,...,...,...,...,...,...,...,...
1564,M_170201,2017-02-01,2017-02-22,Minute,M_170201_chunk_8,Janet L. Yellen,Chairman,1
1227,M_190130,2019-01-30,2019-02-20,Minute,M_190130_chunk_11,Jerome H. Powell,Chairman,1
2929,M_090116,2009-01-16,2009-02-06,Minute,M_090116_chunk_2,Ben S. Bernanke,Chairman,1
3439,M_050202,2005-02-02,2005-02-23,Minute,M_050202_chunk_4,Alan Greenspan,Chairman,1
3676,M_030129,2003-01-29,2003-03-20,Minute,M_030129_chunk_4,Alan Greenspan,Chairman,1

In [42]:
## To retain chunks with word length greater than 20.
fomc_chunk_new_df=fomc_chunk_new_df[fomc_chunk_new_df['word_count']>20]

In [43]:
## To remove chunk text having Footnotes.

fomc_chunk_new_df=fomc_chunk_new_df[~fomc_chunk_new_df["chunked_text"].str.contains(r"footnote", case=False, na=False)]

In [44]:
## To remove chunk text having Footnotes.

fomc_chunk_new_df=fomc_chunk_new_df[~fomc_chunk_new_df["chunked_text"].str.contains(r"footnote", case=False, na=False)]

In [45]:
## Creating new column metadata that defines the chunked document.

fomc_chunk_new_df['metadata']=fomc_chunk_new_df.apply(lambda x: {'doc_id':str(x['doc_id']),'meeting_date':str(x['meeting_date']),\
                                  'release_date':str(x['release_date']), 'doc_type':str(x['doc_type'].lower()), 'chunk_id':x['chunk_id'],\
                                                                 'meeting_year': int(pd.to_datetime(x['meeting_date']).year)},axis=1)

In [46]:
## Final check to ensure there are no missing values and duplicate entry of chunk id.

fomc_chunk_new_df.isna().sum()

doc_id            0
meeting_date      0
release_date      0
doc_type          0
chunk_id          0
section_header    0
chunked_text      0
word_count        0
metadata          0
dtype: int64

#### There are no missing values in any columns.

In [47]:
fomc_chunk_new_df[fomc_chunk_new_df["chunk_id"].duplicated(keep=False)] ## To check for any duplicate entries

Empty DataFrame
Columns: [doc_id, meeting_date, release_date, doc_type, chunk_id, section_header, chunked_text, word_count, metadata]
Index: []

#### There are no duplicate entries of chunk_ids.

In [48]:
fomc_chunk_new_df.sort_values(by='word_count')  ## To check number of word counts

,doc_id,meeting_date,release_date,doc_type,chunk_id,section_header,chunked_text,word_count,metadata
8,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_3_e,Special Topic: Balance Sheet Issues,rates had moved sideways since the beginning o...,21,"{'doc_id': 'M_251210', 'meeting_date': '2025-1..."
343,M_230726,2023-07-26,2023-08-16,Minute,M_230726_chunk_6,Christopher J. Waller,"Kelly J. Dubbert and Kathleen O'Neill Paese, I...",21,"{'doc_id': 'M_230726', 'meeting_date': '2023-0..."
2545,S_110809,2011-08-09,2011-08-09,Statement,S_110809_chunk_1_b,Full Statement Doc,continue to describe economic conditions as li...,21,"{'doc_id': 'S_110809', 'meeting_date': '2011-0..."
319,M_230920,2023-09-20,2023-10-11,Minute,M_230920_chunk_6,Lorie K. Logan,Christopher J. Waller\nSusan M. Collins and Je...,21,"{'doc_id': 'M_230920', 'meeting_date': '2023-0..."
275,M_231213,2023-12-13,2024-01-03,Minute,M_231213_chunk_6,Lorie K. Logan,Christopher J. Waller\nSusan M. Collins and Je...,21,"{'doc_id': 'M_231213', 'meeting_date': '2023-1..."
...,...,...,...,...,...,...,...,...,...
39,M_250917,2025-09-17,2025-10-08,Minute,M_250917_chunk_4_a,Committee Policy Actions,In their discussions of monetary policy for th...,500,"{'doc_id': 'M_250917', 'meeting_date': '2025-0..."
44,M_250730,2025-07-30,2025-08-20,Minute,M_250730_chunk_3_a,Developments in Financial Markets and Open Mar...,The manager turned first to a review of financ...,500,"{'doc_id': 'M_250730', 'meeting_date': '2025-0..."
45,M_250730,2025-07-30,2025-08-20,Minute,M_250730_chunk_3_b,Developments in Financial Markets and Open Mar...,June quarter-end; and the rise in net Treasury...,500,"{'doc_id': 'M_250730', 'meeting_date': '2025-0..."
2,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2_b,Developments in Financial Markets and Open Mar...,previous episode of balance sheet runoff. Cons...,500,"{'doc_id': 'M_251210', 'meeting_date': '2025-1..."
1,M_251210,2025-12-10,2025-12-30,Minute,M_251210_chunk_2_a,Developments in Financial Markets and Open Mar...,The manager turned first to an overview of bro...,500,"{'doc_id': 'M_251210', 'meeting_date': '2025-1..."

### Now we have final total 2788 chunks with maximum of 500 word length and minimum of 21 word length.

In [49]:
## Downoad of final version of fomc_chunk dataset
fomc_chunk_new_df.to_pickle("/content/fomc_chunk_new_df.pkl")

### Embedding of Chunked text using Finbert model and storing in Chromadb for retreival.

In [50]:
## Import chromadb for stroing of embedded chunks
!pip install -U -q chromadb
import chromadb
from chromadb.utils import embedding_functions

In [51]:
## To use Finbert Embedding model SentenceTransformerEmbeddingFunction.
# embed_model = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="ProsusAI/finbert")
embed_model=embedding_functions.SentenceTransformerEmbeddingFunction(model_name="mukaj/fin-mpnet-base")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [52]:
# # Using Persistent Client to store Chroma DB in local path drive.
# chroma_drive_path = '/content/drive/MyDrive/FOMC_ChromaDB_Data'
chroma_drive_path1 = '/content/FOMC_ChromaDB_Data_v2'

# ## instantiating PersistentClient of chromadb.
# client = chromadb.PersistentClient(path=chroma_drive_path)
client1 = chromadb.PersistentClient(path=chroma_drive_path1)

# # Defining collection set up in chroma to pass the embedding function for embedding document chunks.
# chroma_collection = client.get_or_create_collection(name='FOMC_Chroma_Client', embedding_function=embed_model)
chroma_collection1 = client1.get_or_create_collection(name='FOMC_Chroma_Client1', embedding_function=embed_model)

In [53]:
## Creating document, ids and metadatas for ingestion into collection.

ids = list(fomc_chunk_new_df['chunk_id'].astype(str))
docs = list(fomc_chunk_new_df['chunked_text'].astype(str))
metadata = list(fomc_chunk_new_df['metadata'])

In [54]:
## Adding ids, docs and metadata list into collection in batches for effective CPU usage and overload.

## using finbert model
# batch=100
# for i in range(0,len(docs),batch):
#   chroma_collection.add(documents= docs[i:i+batch], ids = ids[i:i+batch], metadatas = metadata[i:i+batch])

#using model mukaj/fin-mpnet-base
batch=100
for i in range(0,len(docs),batch):
 chroma_collection1.add(documents= docs[i:i+batch], ids = ids[i:i+batch], metadatas = metadata[i:i+batch])

#### It takes approximately 45 mins to create embeded chunks and indexing into database.

In [55]:
# ## Copying collection database from Google Drive to local path.

!pip install chromadb
import shutil, chromadb, os
from google.colab import drive
drive.mount('/content/drive')


# Copy complete folder to local Colab path
shutil.copytree(
        "/content/FOMC_ChromaDB_Data_v2", "/content/drive/MyDrive/FOMC_ChromaDB_Data_v2",
    )

Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.5)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.2)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.42.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.7.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.6)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

'/content/drive/MyDrive/FOMC_ChromaDB_Data_v2'

In [56]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [57]:
import contextlib
import io
from google.colab import drive
!pip install chromadb
import shutil, chromadb, os

with contextlib.redirect_stdout(io.StringIO()):
    drive.mount('/content/drive')

# # To load chroma database from local path
chroma_drive_path='/content/drive/MyDrive/FOMC_ChromaDB_Data_v2'
# ## instantiating PersistentClient of chromadb.
client = chromadb.PersistentClient(path=chroma_drive_path)

# # Defining collection set up in chroma to pass the embedding function for embedding document chunks.
# chroma_collection = client.get_or_create_collection(name='FOMC_Chroma_Client', embedding_function=embed_model)
chroma_collection = client.get_or_create_collection(name='FOMC_Chroma_Client1', embedding_function=embed_model)

Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.5)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.2)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.42.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.7.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.6)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)

In [58]:
chromadb.__version__

'1.5.5'

In [59]:
chroma_collection.count() ## Check if all chunks are embeded and indexed

2788

In [60]:
## Verifying few embedding entries from collection using get method and including embeddings, documents and metadatas and uris in retrieval.

sample = chroma_collection.get(limit=5, include=["embeddings", "documents", "metadatas"])

for item in sample:
    print(sample['embeddings'].shape)

(5, 768)
(5, 768)
(5, 768)
(5, 768)
(5, 768)
(5, 768)
(5, 768)

In [61]:
sample

{'ids': ['M_251210_chunk_2_a',
  'M_251210_chunk_2_b',
  'M_251210_chunk_2_c',
  'M_251210_chunk_3_a',
  'M_251210_chunk_3_b'],
 'embeddings': array([[-0.00571093,  0.0500219 , -0.0321373 , ..., -0.02260594,
         -0.14643994,  0.0201575 ],
        [ 0.05549336, -0.01209756, -0.02762297, ..., -0.00354427,
         -0.0777295 , -0.00333712],
        [ 0.0608335 , -0.00136805, -0.00170315, ...,  0.03147561,
         -0.03645298,  0.03054258],
        [ 0.01924396, -0.00616677, -0.02502816, ..., -0.00638236,
         -0.08666972,  0.03668779],
        [ 0.06031217, -0.00597217, -0.02933399, ...,  0.01226316,
         -0.06693666,  0.01088226]]),
 'documents': ["The manager turned first to an overview of broad market developments during the intermeeting period. Market participants did not materially change their macroeconomic outlooks and continued to interpret data made available over the intermeeting period as consistent with a resilient economy. Investors' expectations for the path of the policy rate, whether market based or survey based, were little changed, on net, over the period. Market participants and respondents to the Open Market Desk's Survey of Market Expectations (Desk survey) generally expected a 25 basis point reduction in the target range for the federal funds rate at the December FOMC meeting, and the modal outlook from the survey as well as from options pricing implied two additional rate cuts next year. The manager turned next to developments in Treasury markets and market-based measures of inflation compensation. Treasury yields rose a little over the intermeeting period, on net, but remained within recent ranges. Inflation compensation moved lower over the period, particularly for shorter tenors. The manager attributed the decline in inflation compensation at shorter tenors to lower energy prices as well as a reassessment by some market participants of the likely effect of tariffs on near-term inflation. In contrast to market-based measures of inflation compensation, survey- and model- based measures of inflation expectations were little changed over the intermeeting period. Broad equity price indexes were volatile but changed little, on net, over the intermeeting period. Equity prices showed sensitivity to economic data and policymaker communications. Developments regarding artificial intelligence (AI) also contributed to the volatility of the stock prices of the largest technology companies. The manager noted that capital expenditures on equipment and infrastructure related to AI by a set of large technology companies accelerated this year and that these firms were increasingly relying on debt to finance such expenditures. Regarding international developments, the trade-weighted dollar index was little changed over the intermeeting period. Outside forecasters continued to expect that the dollar would depreciate modestly next year. Many of these forecasters expected a larger reduction in policy rates in the U.S. than in other advanced-economy jurisdictions, though their confidence in this view appeared to diminish somewhat in light of the resilience of the U.S. economy. The manager noted that money market conditions continued to tighten over the intermeeting period and that the staff assessed that conditions were consistent with the level of reserves having declined to the ample region. Rates on Treasury repurchase agreements (repo) remained relatively elevated and volatile over the intermeeting period. Investors attributed firmness in repo rates to a decline in available liquidity and continued large Treasury debt issuance. Higher repo rates, along with a lower level of reserves, continued to contribute to upward pressure on the spread between the effective federal funds rate (EFFR) and the interest rate on reserve balances. The manager noted that the correlation between this spread and the level of reserve balances had risen notably over the past couple of months and that the EFFR had moved up faster than it had during the",
  "previous episode of balance sheet runoff. Consistent with elevated repo rates, usage of overnight reverse repo operations remained low, while both the frequency and volume of standing repo operations increased over the intermeeting period. Some other key indicators of reserve ampleness, such as the share of payments by banks occurring later in the day and the share of domestic banks borrowing in the federal funds market, also pointed to ample reserve conditions. The manager next discussed the expected trajectory of key components of the Federal Reserve's balance sheet. Over the next several months, seasonal fluctuations in nonreserve liabilities were projected to lead to significant declines in reserves at the end of December, in late January, and especially in mid-to-late April if securities holdings in the System Open Market Account (SOMA) were to remain unchanged. The manager noted that the projected fall in reserves in April caused by tax inflows to the Treasury General Account (TGA)â\x80\x94which is a Federal Reserve liabilityâ\x80\x94was particularly large and thus judged that reserves were likely to fall below the ample range if the size of the SOMA portfolio were to remain unchanged. In light of this projected decline in reserves as well as recent developments in money markets, the manager recommended that the Committee consider starting reserve management purchases (RMPs) this month to maintain an ample level of reserves on an ongoing basis. Because of the substantial projected decline in reserves in mid-to-late April, the manager judged that it would be prudent to start RMPs soon, maintain a somewhat elevated pace of net purchases until then, and then decrease the monthly pace substantially thereafter. Respondents to the Desk survey expected RMPs to begin soon. Over one-third of respondents expected RMPs to be announced at this meeting and begin by next month, and most respondents anticipated them to begin before the end of the first quarter of 2026. While the estimated size of expected purchases varied considerably across respondents, on average, respondents anticipated net purchases of about $220 billion over the first 12 months of purchases. The manager then turned to a discussion of standing repo operations and the essential role they play in supporting the implementation of monetary policy. While usage of these operations had increased recently, there had been days when a large volume of repo trades occurred well above the operations' minimum bid rate, suggesting reluctance by some potential participants to engage in standing repo operations. Market outreach suggested that this reluctance reflected misperceptions about the intended purpose of standing repo operations and that the effectiveness of these operations could be enhanced by Federal Reserve communications that explicitly clarified that the purpose of the operations is to support monetary policy implementation. Market participants also suggested that reluctance to use standing repo operations reflected in part specific operational features, and they offered a number of suggestions to enhance the effectiveness of the operations, such as allowing them to be centrally cleared and eliminating the aggregate limit of $500 billion per day. Given the importance of",
  "standing repo operations for monetary policy implementation, the manager proposed to clarify their intended role in official communications, convey the expectation that they would be used when economically sensible, and eliminate their aggregate limit. By unanimous vote, the Committee ratified the Desk's domestic transactions over the intermeeting period. There were no intervention operations in foreign currencies for the System's account during the intermeeting period.",
  "Participants discussed developments in money markets and whether starting RMPs was warranted to maintain reserves at levels consistent with the Committee's ample-reserves framework laid out in its 2019 Statement Regarding Monetary Policy Implementation and Balance Sheet Normalization. With the continued increases in the spreads between money market interest rates and administered rates, as well as some other indicators of tightening money market conditions, participants judged that reserve balances had declined to ample levels. Accordingly, participants assessed that it was appropriate to begin RMPs and initiate purchases of shorter-term Treasury securities to maintain an ample supply of reserves over time. The discussion was preceded by staff presentations. The staff emphasized that a range of levels of reserve balances was consistent with ample and presented indicators showing that money market conditions pointed to reserves being within the ample range. In particular, the spreads of the EFFR and of other money market rates to the interest rate on reserve balances had increased relatively quickly since mid-September. Additionally, several other indicators of liquidity in short-term funding markets, including the volatility of repo rates and their sensitivity to Treasury coupon issuance, pointed to reserves being within the ample range. The staff emphasized the role that standing repo operations had played in ensuring that the federal funds rate remained within its target range, even on days of elevated demand for nonreserve liabilities. The staff also noted the implications of reserves varying within the ample range for volatility and market functioning in money markets, the size of the Federal Reserve's balance sheet, and the use of standing repo operations. The staff noted that maintaining ample reserves over time would require the SOMA security portfolio to expand to accommodate trend growth in the demand for reserves and nonreserve liabilities. In addition, under the ample-reserves framework, the size of the SOMA portfolio would need to be sufficient to accommodate significant seasonal variation in the demand for nonreserve liabilities, such as that driven by fluctuations in TGA balances. The staff presented options for how the Desk could structure RMPs to maintain an ample supply of reserves. They noted the benefits of granting the Desk flexibility to adjust the sizes of RMPs in anticipation of or in response to swings in reserve demand and the demand for nonreserve liabilities. The staff also noted that, consistent with the goal of returning to a primarily Treasury portfolio expressed in the Committee's 2022 Principles for Reducing the Size of the Federal Reserve's Balance Sheet and a preference to shift the SOMA portfolio composition toward that of Treasury securities outstanding, RMPs could be conducted primarily in Treasury bills. Participants agreed that recent money market conditions pointed to reserves being within the ample range and that beginning RMPs would be prudent to maintain a supply of ample reserves. A couple of participants remarked that the recent increase in the spread between the EFFR and the interest rate on reserve balances had been faster than during the Federal Reserve's 2017â\x80\x9319 runoff experience, and a couple of participants",
  'observed that triparty repo rates had been averaging somewhat above the interest rate on reserve balances. Participants expressed their preferences for purchases to be in Treasury bills so that the SOMA portfolio composition would begin to shift toward that of Treasury securities outstanding, though no decision was made on the composition of the portfolio in the long run. Policymakers generally emphasized the importance of communicating that RMPs would be made solely to ensure interest rate control and smooth market functioning and had no implications for the stance of monetary policy. Participants generally agreed that providing the Desk flexibility to adjust the size and timing of RMPs was important because of the significant variation in the demand for Federal Reserve liabilities and the uncertainty surrounding projections of this demand. When discussing how to structure RMPs in light of this variation, several participants emphasized that they preferred to front-load purchases so that the total level of reserves supplied to the market would be enough to manage large anticipated seasonal swings in nonreserve liabilities without having to rely on standing repo operations. Some other participants, however, preferred to limit balance sheet size by conducting RMPs closer to periods of elevated demand for nonreserve liabilities and relying more on standing repo operations to damp upward pressure on rates. Several participants noted that aligning variation in SOMA Treasury bill holdings with variation in nonreserve liabilities would insulate reserve supply from TGA changes, citing research by the Federal Reserve staff. Participants also discussed the role of standing repo operations and commented on their importance for interest rate control in the ample-reserves regime. Some participants emphasized their preference that standing repo operations play a more active role in rate control, with material usage during periods of elevated pressures in money markets. A couple of participants added that effective standing repo operations may allow for a smaller balance sheet on average. Several participants preferred to rely more on RMPs to maintain an ample level of reserves. Various participants noted that a more precise definition of "ample" would help clarify the Committee\'s intentions in implementing an ample-reserves framework. A few participants noted the difficulties of aiming to target an appropriate level of reserves because of the potential shifts in reserve demand. Some participants offered a view that an ample-reserves definition should focus on the level of money market rates in relation to the interest rate on reserve balances, with a few of those participants highlighting that such an approach would avoid some of the challenges of targeting a particular level of reserves given potential shifts in reserve demand. A couple of participants expressed the view that a definition of "ample reserves" that resulted in a larger supply of reserves than necessary to implement the Committee\'s framework could lead to excessive risk-taking by leveraged investors. Staff Review of the Economic Situation The information available at the time of the meeting indicated that real gross domestic product (GDP) had expanded moderately over this year. The unemployment rate had edged up and'],
 'uris': None,
 'included': ['embeddings', 'documents', 'metadatas'],
 'data': None,
 'metadatas': [{'doc_type': 'minute',
   'chunk_id': 'M_251210_chunk_2_a',
   'meeting_date': '2025-12-10 00:00:00',
   'meeting_year': 2025,
   'doc_id': 'M_251210',
   'release_date': '2025-12-30 00:00:00'},
  {'release_date': '2025-12-30 00:00:00',
   'doc_id': 'M_251210',
   'chunk_id': 'M_251210_chunk_2_b',
   'meeting_year': 2025,
   'meeting_date': '2025-12-10 00:00:00',
   'doc_type': 'minute'},
  {'meeting_year': 2025,
   'release_date': '2025-12-30 00:00:00',
   'chunk_id': 'M_251210_chunk_2_c',
   'meeting_date': '2025-12-10 00:00:00',
   'doc_id': 'M_251210',
   'doc_type': 'minute'},
  {'doc_type': 'minute',
   'meeting_date': '2025-12-10 00:00:00',
   'release_date': '2025-12-30 00:00:00',
   'chunk_id': 'M_251210_chunk_3_a',
   'meeting_year': 2025,
   'doc_id': 'M_251210'},
  {'meeting_date': '2025-12-10 00:00:00',
   'doc_id': 'M_251210',
   'doc_type': 'minute',
   'chunk_id': 'M_251210_chunk_3_b',
   'meeting_year': 2025,
   'release_date': '2025-12-30 00:00:00'}]}

### Verify the retrieval layer

In [62]:
## ## Taking user query from user for document search and retrieval.
user_query = input("Please enter your query: ")

Please enter your query: views on inflation

In [63]:
## Defining Function for query search in chroma vector DB.

def query_engiene(user_query):

  ## Perform query on choromadb based on user query and retrieve top 15 relevant search from vector db.
  query_results = chroma_collection.query(query_texts=user_query,n_results=15)

  ## Creating Dataframe of query results.

  query_results_df=pd.DataFrame(columns=['Document','Metadatas','Distance'])
  query_results_df['Document']=query_results['documents'][0]
  query_results_df['Metadatas']=query_results['metadatas'][0]
  query_results_df['Distance']=query_results['distances'][0]
  query_results_df['Document_ID']=[i['doc_id'] for i in query_results_df['Metadatas']]
  query_results_df['Chunk_ID']=[i['chunk_id'] for i in query_results_df['Metadatas']]
  query_results_df['Meeting_Date']=[i['meeting_date'] for i in query_results_df['Metadatas']]
  ## Return sorted table on Distance.
  return(query_results_df.sort_values(by='Distance',ascending=True))

In [64]:
## Calling query_engiene function to obtain top 15 similar documents from chroma db.
top_15_similar_document=query_engiene(user_query)
top_15_similar_document.sort_values(by='Distance',ascending=True)

,Document,Metadatas,Distance,Document_ID,Chunk_ID,Meeting_Date
0,to be a bit less pressing than those on the do...,"{'doc_id': 'M_031209', 'doc_type': 'minute', '...",0.509848,M_031209,M_031209_chunk_3_g,2003-12-09 00:00:00
1,"pressures on labor resources. Nonetheless, the...","{'doc_id': 'M_061212', 'meeting_date': '2006-1...",0.545159,M_061212,M_061212_chunk_5_g,2006-12-12 00:00:00
2,indicated that they could support a proposal t...,"{'doc_type': 'minute', 'meeting_date': '2003-0...",0.545661,M_030506,M_030506_chunk_1_g,2003-05-06 00:00:00
3,their domestic operations from foreign competi...,"{'meeting_date': '2003-10-28 00:00:00', 'chunk...",0.548382,M_031028,M_031028_chunk_4_f,2003-10-28 00:00:00
4,warned about the macroeconomic consequences of...,"{'release_date': '2020-01-03 00:00:00', 'doc_i...",0.551839,M_191211,M_191211_chunk_10_c,2019-12-11 00:00:00
5,upside risks continued to cloud the outlook fo...,"{'doc_id': 'M_030916', 'meeting_date': '2003-0...",0.553441,M_030916,M_030916_chunk_4_g,2003-09-16 00:00:00
6,the expansion of potential GDP could be somewh...,"{'chunk_id': 'M_060920_chunk_1_f', 'doc_type':...",0.561726,M_060920,M_060920_chunk_1_f,2006-09-20 00:00:00
7,"will come into better balance over time, easin...","{'release_date': '2023-04-12 00:00:00', 'chunk...",0.567517,M_230322,M_230322_chunk_16_d,2023-03-22 00:00:00
8,The staff projection for economic activity was...,"{'meeting_date': '2025-01-29 00:00:00', 'doc_i...",0.569106,M_250129,M_250129_chunk_17_a,2025-01-29 00:00:00
9,of more widespread contagion. Given their anti...,"{'release_date': '2002-08-15 00:00:00', 'meeti...",0.569363,M_020626,M_020626_chunk_1_g,2002-06-26 00:00:00
10,"prices had run its course, inflation would be ...","{'chunk_id': 'M_120425_chunk_8_e', 'meeting_ye...",0.571650,M_120425,M_120425_chunk_8_e,2012-04-25 00:00:00
11,the next few quarters. Inflation has been elev...,"{'doc_id': 'M_080318', 'release_date': '2008-0...",0.571974,M_080318,M_080318_chunk_1_j,2008-03-18 00:00:00
12,the next few quarters. Inflation has been elev...,"{'doc_id': 'M_080310', 'release_date': '2008-0...",0.571974,M_080310,M_080310_chunk_1_j,2008-03-10 00:00:00
13,"the outlook for inflation were somewhat mixed,...","{'meeting_date': '2001-01-03 00:00:00', 'meeti...",0.572205,M_010103,M_010103_chunk_3_g,2001-01-03 00:00:00
14,"the outlook for inflation were somewhat mixed,...","{'chunk_id': 'M_001219_chunk_3_g', 'doc_id': '...",0.572205,M_001219,M_001219_chunk_3_g,2000-12-19 00:00:00

### First few retrievals are relevant to the query context however there are many chunks that do not add any values as they contains mostly about the board member name who voted on actions.

### Second level re-ranking is required on top 10-20 retrieved chunks for better results. This is where we use cross-encider transmofer model Roberta for reranking.

In [65]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder("cross-encoder/stsb-roberta-large")

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/stsb-roberta-large
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [66]:
## Function generated to return similarity or accuracy score of each document and query pair.

def rerank_top15_document(user_query,top_15_similar_document):

  ## Creating pair of document(top 10 documents obtianed from engiene query) and query list for re-ranking score.
  cross_encoder_sentence_query_pair = [[user_query,x] for x in top_15_similar_document.Document]

  ## Predicting scores of document and query pair.
  score=reranker.predict(cross_encoder_sentence_query_pair)

  ## Normalising score obtained above in range[0-1] by applying sigmoid function.
  score_norm = [round(float(1/(1+np.exp(-scr))),4) for scr in score]

  ## Updating score and normalised score in dataframe.
  top_15_similar_document['Encoder_Norm_score']=score_norm
  top_15_similar_document['Encoder_score']=score

  ## return sorted table by sorting Norm Score in Descending order.
  return(top_15_similar_document.sort_values(by='Encoder_Norm_score',ascending=False))

In [67]:
## Calling re-rank function to get normalised score of top 10 documents for further refine search result.
top_15_doc_reranked_score_df= rerank_top15_document(user_query,top_15_similar_document)

## Cheking score values.
print('Score from Cross-Encoder model :\n ',top_15_doc_reranked_score_df['Encoder_score'].tolist())
print('\nNormalized Score of score from Cross-Encoder model :\n ',top_15_doc_reranked_score_df['Encoder_Norm_score'].tolist())

Score from Cross-Encoder model :
  [0.6575573682785034, 0.5877796411514282, 0.5827152729034424, 0.5705476999282837, 0.5633572936058044, 0.5603565573692322, 0.5479186773300171, 0.526578426361084, 0.5221132040023804, 0.46715572476387024, 0.42996153235435486, 0.42996153235435486, 0.4280036687850952, 0.38446125388145447, 0.38446125388145447]

Normalized Score of score from Cross-Encoder model :
  [0.6587, 0.6429, 0.6417, 0.6389, 0.6372, 0.6365, 0.6337, 0.6287, 0.6276, 0.6147, 0.6059, 0.6059, 0.6054, 0.5949, 0.5949]

In [68]:
## Retrieving top 3 documents based on Encoder score.
top_15_doc_reranked_score_df.sort_values(by='Encoder_Norm_score',ascending=False)[0:3]

,Document,Metadatas,Distance,Document_ID,Chunk_ID,Meeting_Date,Encoder_Norm_score,Encoder_score
4,warned about the macroeconomic consequences of...,"{'release_date': '2020-01-03 00:00:00', 'doc_i...",0.551839,M_191211,M_191211_chunk_10_c,2019-12-11 00:00:00,0.6587,0.657557
0,to be a bit less pressing than those on the do...,"{'doc_id': 'M_031209', 'doc_type': 'minute', '...",0.509848,M_031209,M_031209_chunk_3_g,2003-12-09 00:00:00,0.6429,0.587780
1,"pressures on labor resources. Nonetheless, the...","{'doc_id': 'M_061212', 'meeting_date': '2006-1...",0.545159,M_061212,M_061212_chunk_5_g,2006-12-12 00:00:00,0.6417,0.582715

### Nowe we can see reranking model has performed better in terms of retrieveing most relevant content based on user query.

# <font color = yellow><b> Implementation of retrieval from FRED dataframes as seperate agent for relevant numerical data retrieval to answer user query that needs look up of numerical macroeconomic dataframe

### Step 1: Loading of saved copy of dataframes of GDP, Employment, Inflation and Fed Funds data from local drive

### First manaully load the datasets into colab drive.

In [69]:
from google.colab import files

gdp_fred_data = pd.read_csv("/content/gdp_fred_data.csv")
poppulation_data = pd.read_csv("/content/poppulation_data.csv")
inflation_data = pd.read_csv("/content/inflation_data.csv")
fed_fund_data = pd.read_csv("/content/fed_fund_data.csv")

In [70]:
## To verify all FRED dataframes are successfully loaded.

print('GDP data : Rows =',gdp_fred_data.shape[0])
print('First five records :\n\n',gdp_fred_data.head())
print('\n\nPoppulation data : Rows =',poppulation_data.shape[0])
print('First five records :\n\n',poppulation_data.head())
print('\n\nInflation data : Rows =',inflation_data.shape[0])
print('First five records :\n\n',inflation_data.head())
print('\n\nFed Fund data : Rows =',fed_fund_data.shape[0])
print('First five records :\n\n',fed_fund_data.head())

GDP data : Rows = 101
First five records :

          DATE      GDPC1  yoy_gdp_%
0  2000-10-01  14229.765       4.08
1  2001-01-01  14183.120       3.57
2  2001-04-01  14271.694       2.50
3  2001-07-01  14214.516       1.64
4  2001-10-01  14253.574       0.96


Poppulation data : Rows = 313
First five records :

          DATE  Civilian_Population_16+  Total_Labor_Force  \
0  2000-01-01                 211410.0           142267.0
1  2000-02-01                 211576.0           142456.0
2  2000-03-01                 211772.0           142434.0
3  2000-04-01                 212018.0           142751.0
4  2000-05-01                 212242.0           142388.0

   Employed_Population  Participation_Rate_%  Employment_Rate_%  \
0             136559.0                 67.29              64.59
1             136598.0                 67.33              64.56
2             136701.0                 67.26              64.55
3             137270.0                 67.33              64.74
4             136630.0                 67.09              64.37

   Unemployment_Rate_%
0                 4.01
1                 4.11
2                 4.03
3                 3.84
4                 4.04


Inflation data : Rows = 5797
First five records :

          DATE  Breakdown_Inflation_5_year  Breakdown_Inflation_10_year
0  2003-01-02                        1.30                         1.64
1  2003-01-03                        1.28                         1.62
2  2003-01-06                        1.31                         1.63
3  2003-01-07                        1.28                         1.62
4  2003-01-08                        1.33                         1.71


Fed Fund data : Rows = 301
First five records :

          DATE  Federal_Funds_Rate_%
0  2000-01-01                  5.45
1  2000-02-01                  5.73
2  2000-03-01                  5.85
3  2000-04-01                  6.02
4  2000-05-01                  6.27

#### Step 2: To merge all FRED data into single dataframe by normalizing datasets. <br><br>
### Below are the data frequency of each fred dataset:<br>
gdp - quaterly (total 101 rows from 2000 to 2025)<br>poppulation - monthly (total 313 rows from 2000 to 2026)<br> inflation - daily excluding weekend (total 5797 rows from 2003 to 2026) <br>fed fund - monthly (total 301 rows from 2000 to 2025)

In [71]:
## Merging of FRED datasets to a master dataset for retreival.
## The master dataset will consists of columns Date, economic_indicator_desc, fred_api, frequency_type and rate_value_%.

## Creating new dataframe of GDP with these five columns.

gdp_fred_data_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])
gdp_fred_data_new['Date']=pd.to_datetime(gdp_fred_data['DATE'])
gdp_fred_data_new['economic_indicator_desc']='GDP Growth Rate'
gdp_fred_data_new['fred_api']='GDPC1'
gdp_fred_data_new['frequency_type']='Quarterly'
gdp_fred_data_new['rate_value_%']=gdp_fred_data['yoy_gdp_%']

In [72]:
gdp_fred_data_new.head()

        Date economic_indicator_desc fred_api frequency_type  rate_value_%
0 2000-10-01         GDP Growth Rate    GDPC1      Quarterly          4.08
1 2001-01-01         GDP Growth Rate    GDPC1      Quarterly          3.57
2 2001-04-01         GDP Growth Rate    GDPC1      Quarterly          2.50
3 2001-07-01         GDP Growth Rate    GDPC1      Quarterly          1.64
4 2001-10-01         GDP Growth Rate    GDPC1      Quarterly          0.96

In [73]:
## Creating new dataframe of poppulation particiaption, employment and unemployment rate with these five columns -
## columns Date, economic_indicator_desc, fred_api, frequency_type and rate_value_%.

poppulation_participation_data_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])
poppulation_employment_data_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])
poppulation_unemployment_data_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])

## For participation rate
poppulation_participation_data_new['Date']=pd.to_datetime(poppulation_data['DATE'])
poppulation_participation_data_new['economic_indicator_desc']='Participation Rate'
poppulation_participation_data_new['fred_api']='CLF16OV'
poppulation_participation_data_new['frequency_type']='Monthly'
poppulation_participation_data_new['rate_value_%']=poppulation_data['Participation_Rate_%']
## For Employment Rate
poppulation_employment_data_new['Date']=pd.to_datetime(poppulation_data['DATE'])
poppulation_employment_data_new['economic_indicator_desc']='Employment Rate'
poppulation_employment_data_new['fred_api']='CE16OV'
poppulation_employment_data_new['frequency_type']='Monthly'
poppulation_employment_data_new['rate_value_%']=poppulation_data['Employment_Rate_%']
## For Un-employment Rate
poppulation_unemployment_data_new['Date']=pd.to_datetime(poppulation_data['DATE'])
poppulation_unemployment_data_new['economic_indicator_desc']='Un-employment Rate'
poppulation_unemployment_data_new['fred_api']='CLF16OV and CE16OV'
poppulation_unemployment_data_new['frequency_type']='Monthly'
poppulation_unemployment_data_new['rate_value_%']=poppulation_data['Unemployment_Rate_%']

In [74]:
## To recheck if correctly data loaded

poppulation_participation_data_new.head()

        Date economic_indicator_desc fred_api frequency_type  rate_value_%
0 2000-01-01      Participation Rate  CLF16OV        Monthly         67.29
1 2000-02-01      Participation Rate  CLF16OV        Monthly         67.33
2 2000-03-01      Participation Rate  CLF16OV        Monthly         67.26
3 2000-04-01      Participation Rate  CLF16OV        Monthly         67.33
4 2000-05-01      Participation Rate  CLF16OV        Monthly         67.09

In [75]:
poppulation_employment_data_new.head()

        Date economic_indicator_desc fred_api frequency_type  rate_value_%
0 2000-01-01         Employment Rate   CE16OV        Monthly         64.59
1 2000-02-01         Employment Rate   CE16OV        Monthly         64.56
2 2000-03-01         Employment Rate   CE16OV        Monthly         64.55
3 2000-04-01         Employment Rate   CE16OV        Monthly         64.74
4 2000-05-01         Employment Rate   CE16OV        Monthly         64.37

In [76]:
poppulation_unemployment_data_new.head()

,Date,economic_indicator_desc,fred_api,frequency_type,rate_value_%
0,2000-01-01,Un-employment Rate,CLF16OV and CE16OV,Monthly,4.01
1,2000-02-01,Un-employment Rate,CLF16OV and CE16OV,Monthly,4.11
2,2000-03-01,Un-employment Rate,CLF16OV and CE16OV,Monthly,4.03
3,2000-04-01,Un-employment Rate,CLF16OV and CE16OV,Monthly,3.84
4,2000-05-01,Un-employment Rate,CLF16OV and CE16OV,Monthly,4.04

In [77]:
## Creating new dataframe of inflation rate with these five columns - columns Date, economic_indicator_desc, fred_api, frequency_type and rate_value_%.

inflation_data_5year_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])
inflation_data_10year_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])

## For Inflation expected rate 5-year
inflation_data_5year_new['Date']=pd.to_datetime(inflation_data['DATE'])
inflation_data_5year_new['economic_indicator_desc']='Inflation Rate 5Year'
inflation_data_5year_new['fred_api']='T5YIE'
inflation_data_5year_new['frequency_type']='Daily'
inflation_data_5year_new['rate_value_%']=inflation_data['Breakdown_Inflation_5_year']

## For Inflation expected rate 10-year
inflation_data_10year_new['Date']=pd.to_datetime(inflation_data['DATE'])
inflation_data_10year_new['economic_indicator_desc']='Inflation Rate 10Year'
inflation_data_10year_new['fred_api']='T10YIE'
inflation_data_10year_new['frequency_type']='Daily'
inflation_data_10year_new['rate_value_%']=inflation_data['Breakdown_Inflation_10_year']

In [78]:
## To check if data correctly loaded

inflation_data_5year_new.head()

        Date economic_indicator_desc fred_api frequency_type  rate_value_%
0 2003-01-02    Inflation Rate 5Year    T5YIE          Daily          1.30
1 2003-01-03    Inflation Rate 5Year    T5YIE          Daily          1.28
2 2003-01-06    Inflation Rate 5Year    T5YIE          Daily          1.31
3 2003-01-07    Inflation Rate 5Year    T5YIE          Daily          1.28
4 2003-01-08    Inflation Rate 5Year    T5YIE          Daily          1.33

In [79]:
inflation_data_10year_new.head()

        Date economic_indicator_desc fred_api frequency_type  rate_value_%
0 2003-01-02   Inflation Rate 10Year   T10YIE          Daily          1.64
1 2003-01-03   Inflation Rate 10Year   T10YIE          Daily          1.62
2 2003-01-06   Inflation Rate 10Year   T10YIE          Daily          1.63
3 2003-01-07   Inflation Rate 10Year   T10YIE          Daily          1.62
4 2003-01-08   Inflation Rate 10Year   T10YIE          Daily          1.71

In [80]:
## Creating new dataframe of fed funds rate with these five columns - columns Date, economic_indicator_desc, fred_api, data_frequency and rate_value_%.

fed_fund_data_new=pd.DataFrame(columns=['Date','economic_indicator_desc','fred_api','frequency_type'])

## For Inflation expected rate 5-year
fed_fund_data_new['Date']=pd.to_datetime(fed_fund_data['DATE'])
fed_fund_data_new['economic_indicator_desc']='Federal Funds Rate'
fed_fund_data_new['fred_api']='FEDFUNDS'
fed_fund_data_new['frequency_type']='Monthly'
fed_fund_data_new['rate_value_%']=fed_fund_data['Federal_Funds_Rate_%']

In [81]:
## To check if data is correctly loaded

fed_fund_data_new.head()

        Date economic_indicator_desc  fred_api frequency_type  rate_value_%
0 2000-01-01      Federal Funds Rate  FEDFUNDS        Monthly          5.45
1 2000-02-01      Federal Funds Rate  FEDFUNDS        Monthly          5.73
2 2000-03-01      Federal Funds Rate  FEDFUNDS        Monthly          5.85
3 2000-04-01      Federal Funds Rate  FEDFUNDS        Monthly          6.02
4 2000-05-01      Federal Funds Rate  FEDFUNDS        Monthly          6.27

In [82]:
### To merge all the individual datasets created into one master FRED dataset.

fred_master_df = pd.concat([gdp_fred_data_new, poppulation_participation_data_new, poppulation_employment_data_new\
                            ,poppulation_unemployment_data_new,inflation_data_5year_new, inflation_data_10year_new, fed_fund_data_new]\
                           ,ignore_index=True)
fred_master_df

,Date,economic_indicator_desc,fred_api,frequency_type,rate_value_%
0,2000-10-01,GDP Growth Rate,GDPC1,Quarterly,4.08
1,2001-01-01,GDP Growth Rate,GDPC1,Quarterly,3.57
2,2001-04-01,GDP Growth Rate,GDPC1,Quarterly,2.50
3,2001-07-01,GDP Growth Rate,GDPC1,Quarterly,1.64
4,2001-10-01,GDP Growth Rate,GDPC1,Quarterly,0.96
...,...,...,...,...,...
12930,2024-09-01,Federal Funds Rate,FEDFUNDS,Monthly,5.13
12931,2024-10-01,Federal Funds Rate,FEDFUNDS,Monthly,4.83
12932,2024-11-01,Federal Funds Rate,FEDFUNDS,Monthly,4.64
12933,2024-12-01,Federal Funds Rate,FEDFUNDS,Monthly,4.48
12934,2025-01-01,Federal Funds Rate,FEDFUNDS,Monthly,4.33

## Total number of rows in FRED master dataset is 12935.

In [83]:
## To Verify and check there are no duplicates and data loaded are correct.

fred_master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12935 entries, 0 to 12934
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     12935 non-null  datetime64[ns]
 1   economic_indicator_desc  12935 non-null  object
 2   fred_api                 12935 non-null  object
 3   frequency_type           12935 non-null  object
 4   rate_value_%             12935 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 505.4+ KB

In [84]:
## To update the object datatype to string type.
fred_master_df["economic_indicator_desc"] = fred_master_df["economic_indicator_desc"].astype("string")
fred_master_df["fred_api"] = fred_master_df["fred_api"].astype("string")
fred_master_df["frequency_type"] = fred_master_df["frequency_type"].astype("string")


fred_master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12935 entries, 0 to 12934
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     12935 non-null  datetime64[ns]
 1   economic_indicator_desc  12935 non-null  string
 2   fred_api                 12935 non-null  string
 3   frequency_type           12935 non-null  string
 4   rate_value_%             12935 non-null  float64
dtypes: datetime64[ns](1), float64(1), string(3)
memory usage: 505.4 KB

In [85]:
fred_master_df.groupby('economic_indicator_desc').count()  ## To verify the number of rows of each FRED indicator

                         Date  fred_api  frequency_type  rate_value_%
economic_indicator_desc
Employment Rate           313       313             313           313
Federal Funds Rate        301       301             301           301
GDP Growth Rate           101       101             101           101
Inflation Rate 10Year    5797      5797            5797          5797
Inflation Rate 5Year     5797      5797            5797          5797
Participation Rate        313       313             313           313
Un-employment Rate        313       313             313           313

In [86]:
fred_master_df[fred_master_df.duplicated(subset=["Date", "economic_indicator_desc"])]

Empty DataFrame
Columns: [Date, economic_indicator_desc, fred_api, frequency_type, rate_value_%]
Index: []

In [87]:
## Downloading the FRED master file using pickle to local system.
fred_master_df.to_pickle("/content/fred_master_df.pkl")
fomc_chunk_new_df.to_pickle("/content/fomc_chunk_new_df.pkl")

### There are no duplicate values and FRED data are correctly loaded into master dataframe which can be used for further retrieval.

# <font color = yellow><b># Genertate query parser using LLM to provide query metadata such as query type, economic indicator and time series for future retreival.

In [88]:
## install and import open ai

!pip install openai
import openai
from openai import OpenAI

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.28.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [89]:
## Creating system message and user message for prompt.

def query_parser_prompt_llm(user_query):
  system_message = """ You are an query parser assistant who is expertise in Macroeconomic analysis domain especially with FRED economic indcator and FOMC will help\
  to generate parameters from query in json format. """

  user_message = f"""
  You have knowledge in Economic Domain with FRED and FOMC and your job is to geneerate structured JSON from a given input query.
  You are given the query asked by user in variable <<user_query>> as below:
  <<user_query>> = '{user_query}'
  Your task is to list out the values of paramaters query_type, query_task_type, indicator, aggregation_method, start_dt, end_dt, chart_required from the input query provided in variable <<user_query>> and output these parameter value in JSON format.
  You should only use below values for query_type paramater:
  1. text
  2. numeric
  3. hybrid

  You should only use below values for <<query_task_type>> paramater:
  1. single
  2. timeseries
  3. compare_indicator
  4. compare_period
  5. summary_topic
  6. summary_fomc_statement
  7. summary_fomc_minute
  8. question_answer

   You should only use below values for <<indicator>> paramater:
  1. gdp_rate
  2. employment_rate
  3. unemployment_rate
  4. inflation_5year
  5. inflation_10year
  6. fed_fund_rate

  You should only use below values for <<aggregation_method>> paramater:
  1. Average
  2. Min
  3. Max
  4. Latest
  5. Oldest
  6. Median
  7. standard_deviation
  8. quantile

  You should only use below values for <<chart_required>> paramater:

  You must follow below rules to generate JSON output:
  1. If query can be answered only from FOMC minutes and statements, then 'query_type' parameter value should be 'text'.
  2. If query can be answered only from FRED numeric data, then 'query_type' parameter value should be 'numeric'.
  3. If query needs both FOMC text and FRED numeric, then 'query_type' parameter value should be 'hybrid'.
  4. If the query needs numeric FRED data and asks for a single value at a specific date, then 'query_task_type' should be 'single'.
  5. If the query needs numeric FRED data and ask about trend, pattern, change over timeperiod, then 'query_task_type' should be 'timeseries'.
  6. If the query needs numeric FRED data and asks comparisions between two or more indicators, then 'query_task_type' should be 'compare_indicator'.
  7. If the query needs numeric FRED data and and asks comparisons between different periods of an indicator, then 'query_task_type' should be 'compare_period'.
  8. If the query needs numeric FRED data and ask about separate two or more indicators and there is no word compare, then 'query_task_type' should be 'single'.
  9. If the query needs numeric FRED data and asks for chart or there is a need for chart plot, then 'chart_required' should be 'yes' else it should be 'no'.
  10. If the query needs numeric FRED data and is about gdp growth rate, then 'indicator' should be 'gdp_rate'.
  11. If the query needs numeric FRED data and is about employment growth rate, then 'indicator' should be 'employment_rate'.
  12. If the query needs numeric FRED data and is about unemployment growth rate, then 'indicator' should be 'unemployment_rate'.
  13. If the query needs numeric FRED data and is about the inflation rate in the short term, then 'indicator' should be 'inflation_5year'.
  14. If the query needs numeric FRED data and is about the inflation rate in the long term, then 'indicator' should be 'inflation_10year'.
  15. If the query needs numeric FRED data and is about the federal funds rate, then 'indicator' should be 'fed_fund_rate'.
  16. If the query needs numeric FRED data and asks for more than one indicator, then the 'indicator' parameter should have values in a list containing all the indicators.
  17. If the query needs text FOMC data and asks for a summary, brief, or overview of a topic or indicator, then 'query_task_type' should be 'summary_topic' and you need to identify the indicator and update the indicator in output dictionary item.
      Note that querry is categorised as 'summary' when the output should be a natural language generation  of retrieved data.
  18. If the query needs text FOMC data and asks about a summary, a brief, or an overview of FOMC minutes, then 'query_task_type' should be 'summary_fomc_minute'.
  19. If the query needs text FOMC data and asks about a summary and asks for a summary of FOMC statements, then 'query_task_type' should be 'summary_fomc_statement'.
  20. If the query needs text FOMC data and asks about information of indicators or questions of policy decision or question of facts, then 'query_task_type' should be 'question_answer' and 'indicator' can be empty.
  21. start_dt and end_dt should be in YYYY-MM-DD format.
  22. If start date and end date are not provided in the query, then you must take the last year of data, where start_dt should be "2025-01-01" and end_dt should be "2025-12-31".
  23. If the query needs numeric FRED data and 'query_task_type' is 'compare_period', then identify the start date and end date of both periods and store in start_dt and end_dt as list type.
  24. Do not return values other than those specified in the above list.
  25. For summary_fomc_statement and summary_fomc_minute query_task_type, if period range is not provided then keep start_dt and end_dt as empty.
  26. If the query needs numeric FRED data and asks for a single value at a specific date, then 'query_task_type' should be 'single' and <<aggregation_method>> parameter must be only one of the below:
      a. mean : If the query asks for the average or a general value of an indicator within given specific time period.
      b. min : If the query asks for the minimum or lowest value of an indicator within given specific time period.
      c. max : If the query asks for the maximum value of an indicator within a given specific time period.
      d. latest : If the query asks for the latest value or most recent values of an indicator within given specific time period.
      e. oldest : If the query asks for the oldest or earliest value of an indicator within given specific time period.
      f. median : If the query asks for the median or typical value of an indicator.
      g. standard_deviation : If the query asks for the standard deviation or volatility of an indicator.
      h. quantile : If the query asks about quantile or percentile values of an indicator.
      If nothing is provided in the query then you must use 'mean' as aggregation method.
      Do not generate any other aggregation_method other than mean, min, max, latest, oldest, median, standard_deviation and quantile.
  27. For query type 'numeric' and query_task_type other than 'single', then <<aggregation_method>> parameter must be empty.
  28. For 'text' query type the <<aggregation_method>> parameter must be empty.
  You should double verify that output generated is in below exact JSON format:
  {{"query_type": "value",
  "query_task_type": "value",
  "indicator": list of value,
  "aggregation_method": "value",
  "start_dt": date value or list of date values,
  "end_dt": date value or list of date values,
  "chart_required": "value"}}

  Note that query is provided in {user_query} and you must return a response in valid JSON format only.

  Refer below few shot examples to generate accurate JSON response of input user query:

  Example 1:
  user_query : Give some insights about inflation rate.
  response:
  {{"query_type": "text",
  "query_task_type": "question_answer",
  "indicator": [],
  "start_dt": "2025-01-01",
  "end_dt": "2025-12-31",
  "chart_required": "no"}}

  Example 2:
  user_query : Summarize FOMC meeting conducted in September 2023.
  response:
  {{"query_type": "text",
  "query_task_type": "summary_fomc_minute",
  "indicator": [],
  "start_dt": "2023-09-01",
  "end_dt": "2023-09-30",
  "chart_required": "no"}}

  Example 3:
  user_query :What was gdp rate in 2024.
  response:
  {{"query_type": "numeric",
  "query_task_type": "single",
  "indicator": [gdp_rate],
  "aggregation_method": "Average",
  "start_dt": "2024-01-01",
  "end_dt": "2024-12-31",
  "chart_required": "no"}}

  Example 4:
  User query: Show the trend of inflation in the short term from 2020 to 2023.
  response:
  {{"query_type": "numeric",
  "task_type": "timeseries",
  "indicators": ["inflation_5year"],
  "start_date": "2020-01-01",
  "end_date": "2023-12-31",
  "chart_required": "yes"}}

  Example 4:
  User query: What was the FED's view regarding unemployment?
  response:
  {{"query_type": "text",
  "task_type": "question_answer",
  "indicators": [],
  "start_date": "2025-01-01",
  "end_date": "2025-12-31",
  "chart_required": "no"}}

  Example 5:
  User query: Compare employment and unemployment rate.
  Output:
  {{"query_type": "numeric",
  "task_type": "compare_indicator",
  "indicators": ["employment_rate", "unemployment_rate"],
  "start_date": "2025-01-01",
  "end_date": "2025-12-31",
  "chart_required": "yes"}}

  """
  # Mount Google Drive and set OpenAI API key.
  from google.colab import drive

  with contextlib.redirect_stdout(io.StringIO()):
    drive.mount('/content/drive')

  # Set the API key
  filepath = "/content/drive/MyDrive/Agentic RAG Project/"
  with open(filepath + "OpenAI_API_Key.txt", "r") as f:
   openai.api_key = ' '.join(f.readlines())

  # Initialize client with API key
  client = OpenAI(api_key=openai.api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response.choices[0].message.content

In [90]:
## Calling LLMprompt function to categorize query and parse query.

llm_query_parse_reply = query_parser_prompt_llm(user_query)
llm_query_parse_reply
# user_query

'{"query_type":"text","query_task_type":"question_answer","indicator":[],"aggregation_method":"","start_dt":"2025-01-01","end_dt":"2025-12-31","chart_required":"no"}'

In [91]:
import json

## To convert string to dictionary type
llm_query_parse_dict=json.loads(llm_query_parse_reply)
llm_query_parse_dict

{'query_type': 'text',
 'query_task_type': 'question_answer',
 'indicator': [],
 'aggregation_method': '',
 'start_dt': '2025-01-01',
 'end_dt': '2025-12-31',
 'chart_required': 'no'}

In [92]:
def fred_retrieval(llm_query_parse_dict):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])

  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]
  if llm_query_parse_dict['query_type']=='numeric':
    if llm_query_parse_dict['query_task_type']=='single':
      return(fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].mean())
    elif llm_query_parse_dict['query_task_type']=='timeseries':
      print('Timeseries query')
    else:
      print('Compare query')


qry_res=fred_retrieval(llm_query_parse_dict)
print(qry_res)

None

# <font color = yellow><b> Implementation of query intent identification and define function for each query type

### We have query_parser_prompt_llm(user_query) function that outputs query type and other parameters of query.
### Below are the query type identified by LLM :   1. text 2. numeric 3. hybrid
### Below are the intent of query identified by LLM :   1. single 2. timeseries 3. compare 4. summary 5. question_answer

####<font color = orange><b>Agent A : Query Intent Classification and Parser.

In [93]:
def query_intent_parser(user_query):
  ## Call Parser Prompt via LLM model to obtaain query type details.
  llm_query_parse_reply = query_parser_prompt_llm(user_query)
  ## To convert string to dictionary type
  import json
  llm_query_parse_dict=json.loads(llm_query_parse_reply)
  return(llm_query_parse_dict)

####<font color = orange><b>Agent B : Retrieval of data based on query type through orchestration of the query to different retreival functions.

##### Retrieval function 1 : Numeric and Single query type

In [94]:
## Designing of function for each query intent type.
## Below function is to be used for numeric type of query and with intent of single query.

def numeric_single_query_retreival(llm_query_parse_dict,user_query):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])

  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]
  numeric_single_query_answer_for_llm={}
  numeric_single_query_answer_for_llm['query_type']=llm_query_parse_dict['query_type']
  numeric_single_query_answer_for_llm['query_task_type']=llm_query_parse_dict['query_task_type']
  numeric_single_query_answer_for_llm['start_dt']=str(start_dt.date())
  numeric_single_query_answer_for_llm['end_dt']=str(end_dt.date())
  numeric_single_query_answer_for_llm['indicator']=indicator_label
  numeric_single_query_answer_for_llm['chart_required']='no'
  numeric_single_query_answer_for_llm['user_query']=user_query
  query_result=[]
  # To obtain mean of data.
  if llm_query_parse_dict['aggregation_method'].lower()=='mean':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].mean()
  # To obtain a minimum of data
  elif llm_query_parse_dict['aggregation_method'].lower()=='min':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].min()
   # To obtain a maximum of data
  elif llm_query_parse_dict['aggregation_method'].lower()=='max':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].max()
   # To obtain latest data
  elif llm_query_parse_dict['aggregation_method'].lower()=='latest':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].sort_values(by='Date').tail(1)
   # To obtain oldest data
  elif llm_query_parse_dict['aggregation_method'].lower()=='oldest':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].sort_values(by='Date').head(1)
  # To obtain median of data
  elif llm_query_parse_dict['aggregation_method'].lower()=='median':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].median()
  # To obtain standard deviation of data
  elif llm_query_parse_dict['aggregation_method'].lower()=='standard_deviation':
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].std()
  # To obtain percentile of data
  elif llm_query_parse_dict['aggregation_method'].lower()=='quantile':
    import re
    pattern='(\d+)(th|nd|st|rd)*\s*(percentile|quantile|percent|percentage|%)'
    match=re.search(pattern,user_query.lower())
    if match:
      if int(match.group(1))>=1 and int(match.group(1))<=100:
        value=int(match.group(1))
        val_decimal= round(value/100,2)
        res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].quantile(val_decimal)
        numeric_single_query_answer_for_llm['percentile_value']=value
      else:
          user_query_correct=input("""Please re-type query with correct percentile/quantile value ranging from 1-100, for example '20th percentile', '75 percentile', '90%' etc.
          """)
          match=re.search(pattern,user_query_correct.lower())
          value=int(match.group(1))
          val_decimal= round(value/100,2)
          res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].quantile(val_decimal)
          numeric_single_query_answer_for_llm['percentile_value']=value
          numeric_single_query_answer_for_llm['user_query']=user_query_correct
    else:
        user_query_correct=input("Please provide correct percentile/quantile value, for example '20th percentile', '75 percentile', '90%' etc.")
        match=re.search(pattern,user_query_correct.lower())
        value=int(match.group(1))
        val_decimal= round(value/100,2)
        res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].quantile(val_decimal)
        numeric_single_query_answer_for_llm['percentile_value']=value
        numeric_single_query_answer_for_llm['user_query']=user_query_correct
  # To get average if none provided
  else:
    res=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)].groupby('economic_indicator_desc')['rate_value_%'].mean()


  for i,row in res.reset_index().iterrows():
    query_result.append({'indicator_label':row['economic_indicator_desc'],'rate_value_%':round(row['rate_value_%'],2), 'unit':'percentage'})

  numeric_single_query_answer_for_llm['aggregation_method']=llm_query_parse_dict['aggregation_method']
  numeric_single_query_answer_for_llm['numeric_query_result']=query_result

  return(numeric_single_query_answer_for_llm)

##### Retrieval function 2 : Numeric and Timeseries/trend query type

In [95]:
## Designing of function for each query intent type.
## Below function is to be used for numeric type of query and with intent of trend/timeseries type query.

def numeric_timeseries_query_retreival(llm_query_parse_dict,user_query):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])

  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]

  # To get the list of timeseries data
  timeseries_data=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)][['rate_value_%','Date']]
  # To get the slop of trend/timeseries data
  x = np.arange(len(timeseries_data))
  slope = round(np.polyfit(x, timeseries_data['rate_value_%'], 1)[0],3)
  # to get total peaks(lows and ups) to identoify volatility.
  lows=0
  ups = 0
  for i in range(1,len(timeseries_data)-1):
    if (timeseries_data['rate_value_%'].iloc[i]>timeseries_data['rate_value_%'].iloc[i-1]) & \
      (timeseries_data['rate_value_%'].iloc[i]>timeseries_data['rate_value_%'].iloc[i+1]):
      ups = ups+1
    if (timeseries_data['rate_value_%'].iloc[i]<timeseries_data['rate_value_%'].iloc[i-1]) & \
      (timeseries_data['rate_value_%'].iloc[i]<timeseries_data['rate_value_%'].iloc[i+1]):
      lows = lows+1
  peaks=lows+ups
  peak_ratio = round(peaks/(len(timeseries_data)-2),3)
  # to get coefficient variation to identify volatility.
  cv = np.std(timeseries_data['rate_value_%'])/abs(np.mean(timeseries_data['rate_value_%']))
  # to prepare timeseries data output in dictionary format for llm
  timeseries_values_for_llm={}
  slop_rel=slope/abs(np.mean(timeseries_data['rate_value_%']))
  # To identofy the slope trend
  if  abs(slop_rel)<0.01:
    timeseries_values_for_llm['trend']='Stable'
  elif abs(slop_rel)<0.05:
    if slope>0:
      timeseries_values_for_llm['trend']='Moderate Upward'
    else:
      timeseries_values_for_llm['trend']='Moderate Downward'
  else:
    if slope>0:
      timeseries_values_for_llm['trend']='Strong Upward'
    else:
      timeseries_values_for_llm['trend']='Strong Downward'

  # To identify volatility
  if len(timeseries_data)<3:
    timeseries_values_for_llm['volatility']='Insufficient'
  else:
    if (cv<0.05) & (peak_ratio<0.10):
      timeseries_values_for_llm['volatility']='Low Volatility'
    elif (cv<0.10) & (peak_ratio<0.20):
      timeseries_values_for_llm['volatility']='Moderate Volatility'
    else:
      timeseries_values_for_llm['volatility']='High Volatility'

  # Chart visulaisation is required for facts.
  timeseries_values_for_llm['chart_required']='yes'
  # Add other required information for llm to generate fact data.
  timeseries_values_for_llm['user_query']=user_query
  timeseries_values_for_llm['query_task_type']=llm_query_parse_dict['query_task_type']
  timeseries_values_for_llm['high_value']=timeseries_data['rate_value_%'].max()
  timeseries_values_for_llm['low_value']=timeseries_data['rate_value_%'].min()
  timeseries_values_for_llm['average_value']=float(timeseries_data['rate_value_%'].mean())
  timeseries_values_for_llm['first_value']=float(timeseries_data['rate_value_%'].iloc[0])
  timeseries_values_for_llm['last_value']=float(timeseries_data['rate_value_%'].iloc[-1])
  timeseries_values_for_llm['slope_value']=float(slope)
  timeseries_values_for_llm['start_date']=str(start_dt.date())
  timeseries_values_for_llm['end_date']=str(end_dt.date())
  timeseries_values_for_llm['indicator']=indicator_label

  return timeseries_values_for_llm,timeseries_data

Retrieval function 3 : Numeric and multiple indicator Comparision query type

In [96]:
## Designing of function for each query intent type.
## Below function is to be used for numeric type of query and with intent of comparision between two indicators query.

def numeric_compare_multiindicator_query_retreival(llm_query_parse_dict):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])

  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]

  if len(indicator_label)>1:

  # To get the list of timeseries data of both indicator separately for comparision
    timeseries_data_1=fred_master_df[(fred_master_df['economic_indicator_desc']==(indicator_label[0])) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)][['rate_value_%','Date']]
    timeseries_data_2=fred_master_df[(fred_master_df['economic_indicator_desc']==(indicator_label[1])) & \
                (fred_master_df['Date']>=start_dt)\
                & (fred_master_df['Date']<=end_dt)][['rate_value_%','Date']]
  # To get the slop of both indicator separately for comparision
  x1 = np.arange(len(timeseries_data_1))
  slope1 = round(np.polyfit(x1, timeseries_data_1['rate_value_%'], 1)[0],3)
  x2= np.arange(len(timeseries_data_2))
  slope2 = round(np.polyfit(x2, timeseries_data_2['rate_value_%'], 1)[0],3)
  # to get total peaks(lows and ups) to identoify volatility.
  lows=0
  ups = 0
  for i in range(1,len(timeseries_data_1)-1):
    if (timeseries_data_1['rate_value_%'].iloc[i]>timeseries_data_1['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_1['rate_value_%'].iloc[i]>timeseries_data_1['rate_value_%'].iloc[i+1]):
      ups = ups+1
    if (timeseries_data_1['rate_value_%'].iloc[i]<timeseries_data_1['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_1['rate_value_%'].iloc[i]<timeseries_data_1['rate_value_%'].iloc[i+1]):
      lows = lows+1
  peaks1=lows+ups
  peak_ratio1 = round(peaks1/(len(timeseries_data_1)-2),3)
  lows=0
  ups = 0
  for i in range(1,len(timeseries_data_2)-1):
    if (timeseries_data_2['rate_value_%'].iloc[i]>timeseries_data_2['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_2['rate_value_%'].iloc[i]>timeseries_data_2['rate_value_%'].iloc[i+1]):
      ups = ups+1
    if (timeseries_data_2['rate_value_%'].iloc[i]<timeseries_data_2['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_2['rate_value_%'].iloc[i]<timeseries_data_2['rate_value_%'].iloc[i+1]):
      lows = lows+1
  peaks2=lows+ups
  peak_ratio2 = round(peaks2/(len(timeseries_data_2)-2),3)
  # to get coefficient variation to identify volatility.
  cv1 = np.std(timeseries_data_1['rate_value_%'])/abs(np.mean(timeseries_data_1['rate_value_%']))
  cv2 = np.std(timeseries_data_2['rate_value_%'])/abs(np.mean(timeseries_data_2['rate_value_%']))
  # to prepare timeseries data output in dictionary format for llm
  comparision_values_for_llm={}

  # Add other required information for llm to generate fact data.

  comparision_values_for_llm['type_of_comparision']='multiple_indicator'
  comparision_values_for_llm['indicator_1']={'indicator_label':indicator_label[0],\
                                             'high_value':timeseries_data_1['rate_value_%'].max(),\
                                             'low_value':timeseries_data_1['rate_value_%'].min(),\
                                             'average_value':round(float(timeseries_data_1['rate_value_%'].mean()),2),\
                                             'first_value':float(timeseries_data_1['rate_value_%'].iloc[0]),\
                                             'last_value':float(timeseries_data_1['rate_value_%'].iloc[-1]),\
                                             'slope_value':float(slope1),\
                                             'start_date':str(start_dt.date()),\
                                             'end_date':str(end_dt.date())
                                            }
  comparision_values_for_llm['indicator_2']={'indicator_label':indicator_label[1],\
                                             'high_value':timeseries_data_2['rate_value_%'].max(),\
                                             'low_value':timeseries_data_2['rate_value_%'].min(),\
                                             'average_value':round(float(timeseries_data_2['rate_value_%'].mean()),2),\
                                             'first_value':float(timeseries_data_2['rate_value_%'].iloc[0]),\
                                             'last_value':float(timeseries_data_2['rate_value_%'].iloc[-1]),\
                                             'slope_value':float(slope2),\
                                             'start_date':str(start_dt.date()),\
                                             'end_date':str(end_dt.date())
                                            }
  # Chart visulaisation is required for facts.
  comparision_values_for_llm['chart_required']='yes'

  slop_rel1=slope1/abs(np.mean(timeseries_data_1['rate_value_%']))
  slop_rel2=slope1/abs(np.mean(timeseries_data_2['rate_value_%']))

  # To identify the slope trend for first indicator
  if  abs(slop_rel1)<0.01:
    comparision_values_for_llm['indicator_1']['trend']='Stable'
  elif abs(slop_rel1)<0.05:
    if slope1>0:
      comparision_values_for_llm['indicator_1']['trend']='Moderate Upward'
    else:
      comparision_values_for_llm['indicator_1']['trend']='Moderate Downward'
  else:
    if slope1>0:
      comparision_values_for_llm['indicator_1']['trend']='Strong Upward'
    else:
      comparision_values_for_llm['indicator_1']['trend']='Strong Downward'

    # To identify the slope trend for second indicator
  if  abs(slop_rel2)<0.01:
    comparision_values_for_llm['indicator_2']['trend']='Stable'
  elif abs(slop_rel2)<0.05:
    if slope2>0:
      comparision_values_for_llm['indicator_2']['trend']='Moderate Upward'
    else:
      comparision_values_for_llm['indicator_2']['trend']='Moderate Downward'
  else:
    if slope2>0:
      comparision_values_for_llm['indicator_2']['trend']='Strong Upward'
    else:
      comparision_values_for_llm['indicator_2']['trend']='Strong Downward'

  # To identify volatility for first indicator
  if len(timeseries_data_1)<3:
    comparision_values_for_llm['indicator_1']['volatility']='Insufficient'
  else:
    if (cv1<0.05) & (peak_ratio1<0.10):
      comparision_values_for_llm['indicator_1']['volatility']='Low Volatility'
    elif (cv1<0.10) & (peak_ratio1<0.20):
      comparision_values_for_llm['indicator_1']['volatility']='Moderate Volatility'
    else:
      comparision_values_for_llm['indicator_1']['volatility']='High Volatility'


  # To identify volatility for second indicator
  if len(timeseries_data_2)<3:
    comparision_values_for_llm['indicator_2']['volatility']='Insufficient'
  else:
    if (cv2<0.05) & (peak_ratio2<0.10):
      comparision_values_for_llm['indicator_2']['volatility']='Low Volatility'
    elif (cv2<0.10) & (peak_ratio2<0.20):
      comparision_values_for_llm['indicator_2']['volatility']='Moderate Volatility'
    else:
      comparision_values_for_llm['indicator_2']['volatility']='High Volatility'

  # To identify higher of average values of two indicators for comparision metrix
  if timeseries_data_1['rate_value_%'].mean()>timeseries_data_2['rate_value_%'].mean():
    comparision_values_for_llm['indicator_higher_rate']=indicator_label[0]
    comparision_values_for_llm['difference_of_indicators_average']=round(float((timeseries_data_1['rate_value_%'].mean())-(timeseries_data_2['rate_value_%'].mean())),2)
  else:
    comparision_values_for_llm['indicator_higher_rate']=indicator_label[1]
    comparision_values_for_llm['difference_of_indicators_average']=round(float((timeseries_data_2['rate_value_%'].mean())-(timeseries_data_1['rate_value_%'].mean())),2)

  return comparision_values_for_llm,timeseries_data_1,timeseries_data_2

Retrieval function 4 : Numeric and multi duration Comparision query type

In [97]:
## Designing of function for each query intent type.
## Below function is to be used for numeric type of query and with intent of comparision between two period range query.

def numeric_compare_multiperiod_query_retreival(llm_query_parse_dict):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])

  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]

    # To get the list of timeseries data of both time period separately for comparision
  timeseries_data_1=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt[0])\
                & (fred_master_df['Date']<=end_dt[0])][['rate_value_%','Date']]
  timeseries_data_2=fred_master_df[(fred_master_df['economic_indicator_desc'].isin(indicator_label)) & \
                (fred_master_df['Date']>=start_dt[1])\
                & (fred_master_df['Date']<=end_dt[1])][['rate_value_%','Date']]
  # To get the slop of both duration data separately for comparision
  x1 = np.arange(len(timeseries_data_1))
  slope1 = round(np.polyfit(x1, timeseries_data_1['rate_value_%'], 1)[0],3)
  x2= np.arange(len(timeseries_data_2))
  slope2 = round(np.polyfit(x2, timeseries_data_2['rate_value_%'], 1)[0],3)
  # to get total peaks(lows and ups) to identoify volatility.
  lows=0
  ups = 0
  for i in range(1,len(timeseries_data_1)-1):
    if (timeseries_data_1['rate_value_%'].iloc[i]>timeseries_data_1['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_1['rate_value_%'].iloc[i]>timeseries_data_1['rate_value_%'].iloc[i+1]):
      ups = ups+1
    if (timeseries_data_1['rate_value_%'].iloc[i]<timeseries_data_1['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_1['rate_value_%'].iloc[i]<timeseries_data_1['rate_value_%'].iloc[i+1]):
      lows = lows+1
  peaks1=lows+ups
  peak_ratio1 = round(peaks1/(len(timeseries_data_1)-2),3)
  lows=0
  ups = 0
  for i in range(1,len(timeseries_data_2)-1):
    if (timeseries_data_2['rate_value_%'].iloc[i]>timeseries_data_2['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_2['rate_value_%'].iloc[i]>timeseries_data_2['rate_value_%'].iloc[i+1]):
      ups = ups+1
    if (timeseries_data_2['rate_value_%'].iloc[i]<timeseries_data_2['rate_value_%'].iloc[i-1]) & \
      (timeseries_data_2['rate_value_%'].iloc[i]<timeseries_data_2['rate_value_%'].iloc[i+1]):
      lows = lows+1
  peaks2=lows+ups
  peak_ratio2 = round(peaks2/(len(timeseries_data_2)-2),3)
  # to get coefficient variation to identify volatility.
  cv1 = np.std(timeseries_data_1['rate_value_%'])/abs(np.mean(timeseries_data_1['rate_value_%']))
  cv2 = np.std(timeseries_data_2['rate_value_%'])/abs(np.mean(timeseries_data_2['rate_value_%']))
  # to prepare timeseries data output in dictionary format for llm
  comparision_values_for_llm={}

  # Add other required information for llm to generate fact data.

  comparision_values_for_llm['type_of_comparision']='compare_multiple_time_period'
  comparision_values_for_llm['period_1']={'indicator_label':indicator_label,\
                                             'high_value':timeseries_data_1['rate_value_%'].max(),\
                                             'low_value':timeseries_data_1['rate_value_%'].min(),\
                                             'average_value':round(float(timeseries_data_1['rate_value_%'].mean()),2),\
                                             'first_value':float(timeseries_data_1['rate_value_%'].iloc[0]),\
                                             'last_value':float(timeseries_data_1['rate_value_%'].iloc[-1]),\
                                             'slope_value':float(slope1),\
                                             'period1_range':str(start_dt[0].date())+' to '+str(end_dt[0].date())
                                            }
  comparision_values_for_llm['period_2']={'indicator_label':indicator_label,\
                                             'high_value':timeseries_data_2['rate_value_%'].max(),\
                                             'low_value':timeseries_data_2['rate_value_%'].min(),\
                                             'average_value':round(float(timeseries_data_2['rate_value_%'].mean()),2),\
                                             'first_value':float(timeseries_data_2['rate_value_%'].iloc[0]),\
                                             'last_value':float(timeseries_data_2['rate_value_%'].iloc[-1]),\
                                             'slope_value':float(slope2),\
                                             'period2_range':str(start_dt[1].date())+' to '+str(end_dt[1].date())
                                            }
  # Chart visulaisation is required for facts.
  comparision_values_for_llm['chart_required']='yes'

  slop_rel1=slope1/abs(np.mean(timeseries_data_1['rate_value_%']))
  slop_rel2=slope1/abs(np.mean(timeseries_data_2['rate_value_%']))

  # To identify the slope trend for first indicator
  if  abs(slop_rel1)<0.01:
    comparision_values_for_llm['period_1']['trend']='Stable'
  elif abs(slop_rel1)<0.05:
    if slope1>0:
      comparision_values_for_llm['period_1']['trend']='Moderate Upward'
    else:
      comparision_values_for_llm['period_1']['trend']='Moderate Downward'
  else:
    if slope1>0:
      comparision_values_for_llm['period_1']['trend']='Strong Upward'
    else:
      comparision_values_for_llm['period_1']['trend']='Strong Downward'

    # To identify the slope trend for second indicator
  if  abs(slop_rel2)<0.01:
    comparision_values_for_llm['period_2']['trend']='Stable'
  elif abs(slop_rel2)<0.05:
    if slope2>0:
      comparision_values_for_llm['period_2']['trend']='Moderate Upward'
    else:
      comparision_values_for_llm['period_2']['trend']='Moderate Downward'
  else:
    if slope2>0:
      comparision_values_for_llm['period_2']['trend']='Strong Upward'
    else:
      comparision_values_for_llm['period_2']['trend']='Strong Downward'

  # To identify volatility for first indicator
  if len(timeseries_data_1)<3:
    comparision_values_for_llm['period_1']['volatility']='Insufficient'
  else:
    if (cv1<0.05) & (peak_ratio1<0.10):
      comparision_values_for_llm['period_1']['volatility']='Low Volatility'
    elif (cv1<0.10) & (peak_ratio1<0.20):
      comparision_values_for_llm['period_1']['volatility']='Moderate Volatility'
    else:
      comparision_values_for_llm['period_1']['volatility']='High Volatility'


  # To identify volatility for second indicator
  if len(timeseries_data_2)<3:
    comparision_values_for_llm['period_2']['volatility']='Insufficient'
  else:
    if (cv2<0.05) & (peak_ratio2<0.10):
      comparision_values_for_llm['period_2']['volatility']='Low Volatility'
    elif (cv2<0.10) & (peak_ratio2<0.20):
      comparision_values_for_llm['period_2']['volatility']='Moderate Volatility'
    else:
      comparision_values_for_llm['period_2']['volatility']='High Volatility'

  # To identify higher of average values of two indicators for comparision metrix
  if timeseries_data_1['rate_value_%'].mean()>timeseries_data_2['rate_value_%'].mean():
    comparision_values_for_llm['period_having_higher_rate']=str(start_dt[0].date())+' to '+str(end_dt[0].date())
    comparision_values_for_llm['difference_of_rate_average']=round(float((timeseries_data_1['rate_value_%'].mean())-(timeseries_data_2['rate_value_%'].mean())),2)
  else:
    comparision_values_for_llm['period_having_higher_rate']=str(start_dt[1].date())+' to '+str(end_dt[1].date())
    comparision_values_for_llm['difference_of_rate_average']=round(float((timeseries_data_2['rate_value_%'].mean())-(timeseries_data_1['rate_value_%'].mean())),2)

  # To add inidicator values in both period range for llm
  comparision_values_for_llm['period_1']['indicator_label']=indicator_label
  comparision_values_for_llm['period_2']['indicator_label']=indicator_label

  return comparision_values_for_llm,timeseries_data_1,timeseries_data_2

#### Retrieval function 5 : Text and document summary query type

In [98]:
## Designing of function for each query intent type.
## Below function is to be used for text type of query and with intent of document summarisation query.

def text_document_summary_query_retreival(llm_query_parse_dict):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])
  text_summary_doc_for_llm={}
  text_summary_doc_for_llm['chart_required']='no'
  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]
  if llm_query_parse_dict['query_task_type']=='summary_fomc_minute':
    summary_doc_df = fomc_chunk_new_df[(fomc_chunk_new_df.doc_type=='Minute') & (fomc_chunk_new_df.meeting_date>=start_dt) & \
                                                                              (fomc_chunk_new_df.meeting_date<=end_dt)]
    retreievd_doc_with_timestamp = pd.DataFrame(summary_doc_df.groupby('meeting_date')['chunked_text'].apply(lambda x: "\n\n".join(x)))
    retreievd_doc_with_timestamp.reset_index(inplace=True)
    retreievd_doc_with_timestamp['meeting_date']=pd.to_datetime(retreievd_doc_with_timestamp['meeting_date']).dt.strftime("%Y-%m-%d")
    retreievd_doc_with_timestamp=retreievd_doc_with_timestamp.to_dict(orient="records")
    text_summary_doc_for_llm['document_retreived_for_sumamry']=retreievd_doc_with_timestamp
    text_summary_doc_for_llm['query_type']='document_summary'
    text_summary_doc_for_llm['document_type']='FOMC_minute'
    text_summary_doc_for_llm['start_date']=str(start_dt.date())
    text_summary_doc_for_llm['end_date']=str(end_dt.date())
    return text_summary_doc_for_llm
  elif llm_query_parse_dict['query_task_type']=='summary_fomc_statement':
    summary_doc_df = fomc_chunk_new_df[(fomc_chunk_new_df.doc_type=='Statement') & (fomc_chunk_new_df.meeting_date>=start_dt) & \
                                                                                  (fomc_chunk_new_df.meeting_date<=end_dt)]
    retreievd_doc_with_timestamp = pd.DataFrame(summary_doc_df.groupby('meeting_date')['chunked_text'].apply(lambda x: "\n\n".join(x)))
    retreievd_doc_with_timestamp.reset_index(inplace=True)
    retreievd_doc_with_timestamp['meeting_date']=pd.to_datetime(retreievd_doc_with_timestamp['meeting_date']).dt.strftime("%Y-%m-%d")
    retreievd_doc_with_timestamp=retreievd_doc_with_timestamp.to_dict(orient="records")
    text_summary_doc_for_llm['document_retreived_for_sumamry']=retreievd_doc_with_timestamp
    text_summary_doc_for_llm['query_type']='document_summary'
    text_summary_doc_for_llm['document_type']='FOMC_statement'
    text_summary_doc_for_llm['start_date']=str(start_dt.date())
    text_summary_doc_for_llm['end_date']=str(end_dt.date())
    return text_summary_doc_for_llm

#### Retrieval function 6 : Text and topic wise summary query type

In [99]:
## Designing of function for each query intent type.
## Below function is to be used for text type of query and with intent of topic wise summarisation query.

def text_topic_summary_query_retreival(llm_query_parse_dict,user_query):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])
  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]
  text_summary_item_for_llm={}
  text_summary_item_for_llm['chart_required']='no'
  ## Call query rewriter function to generate efficient query.
  llm_output=query_rewriter_llm(user_query)
  ## Call collection load function for semantic retrieval of text.
  chroma_collection=fomc_collection_load()
  ## Call query engine function to retrieve top 15 semantic chunks from embed collection.
  top_15_similar_document=query_engine(llm_output['rewritten_query'],chroma_collection)
  ## Calling re-rank function to get normalised re-ranked score of top 15 documents for refined search result.
  top_15_doc_reranked_score_df= rerank_top15_document(llm_output['rewritten_query'],top_15_similar_document)
  ## Return top 10 documents based on Encoder score for llm to provide summary of chunks based on user topic.
  document_retreived_for_sumamry = top_15_doc_reranked_score_df.sort_values(by='Encoder_Norm_score',ascending=False)[0:10]
  text_summary_item_for_llm['query_type']='topic_summary'
  text_summary_item_for_llm['original_user_query']=user_query
  text_summary_item_for_llm['rewritten_user_query']=llm_output['rewritten_query']

  metadatas_list = document_retreived_for_sumamry['Metadatas'].tolist()
  documents_list = document_retreived_for_sumamry['Document'].tolist()

  combined_retrieval_list = []

  for meta, doc in zip(metadatas_list, documents_list):
    combined_retrieval_list.append({**meta,"document_text": doc})

  text_summary_item_for_llm['documents_retrieved_for_summary'] = combined_retrieval_list
  return text_summary_item_for_llm

#### Retrieval function 7 : Text and question answer query type

In [100]:
## Designing of function for each query intent type.
## Below function is to be used for text type of query and with intent of qyestion answer type query.

def text_question_answer_query_retreival(llm_query_parse_dict,user_query):

  # Map the parser indicators to actual indicator labels
  indicator_map = {
        "gdp_rate": "GDP Growth Rate",
        "fed_fund_rate": "Federal Funds Rate",
        "employment_rate": "Employment Rate",
        "unemployment_rate": "Un-employment Rate",
        "inflation_5year": "Inflation Rate 5Year",
        "inflation_10year": "Inflation Rate 10Year"}

  start_dt = pd.to_datetime(llm_query_parse_dict['start_dt'])
  end_dt   = pd.to_datetime(llm_query_parse_dict['end_dt'])
  indicator_label=[indicator_map[i] for i in llm_query_parse_dict['indicator']]
  text_question_answer_for_llm={}
  text_question_answer_for_llm['chart_required']='no'
  ## Call query rewriter function to generate efficient query.
  llm_output=query_rewriter_llm(user_query)
  ## Call collection load function for semantic retrieval of text.
  chroma_collection=fomc_collection_load()
  ## Call query engine function to retrieve top 15 semantic chunks from embed collection.
  top_15_similar_document=query_engine(llm_output['rewritten_query'],chroma_collection)
  ## Calling re-rank function to get normalised re-ranked score of top 15 documents for refined search result.
  top_15_doc_reranked_score_df= rerank_top15_document(llm_output['rewritten_query'],top_15_similar_document)
  ## Return top 10 documents based on Encoder score for llm to provide summary of chunks based on user topic.
  document_retreived_for_query = top_15_doc_reranked_score_df.sort_values(by='Encoder_Norm_score',ascending=False)[0:4]
  text_question_answer_for_llm['query_type']=llm_query_parse_dict['query_task_type']
  text_question_answer_for_llm['original_user_query']=user_query
  text_question_answer_for_llm['rewritten_user_query']=llm_output['rewritten_query']

  metadatas_list = document_retreived_for_query['Metadatas'].tolist()
  documents_list = document_retreived_for_query['Document'].tolist()

  combined_retrieval_list = []

  for meta, doc in zip(metadatas_list, documents_list):
    combined_retrieval_list.append({**meta,"document_text": doc})

  text_question_answer_for_llm['documents_retrieved_for_question_answer'] = combined_retrieval_list
  return text_question_answer_for_llm

#### Function to call chroma database collection for semantic retrieval.

In [101]:
## Import chromadb for stroing of embedded chunks
!pip install -U -q chromadb
import chromadb, shutil, os, io, contextlib

from chromadb.utils import embedding_functions

def fomc_collection_load():
  # Mount google drive
  from google.colab import drive
  with contextlib.redirect_stdout(io.StringIO()):
    drive.mount('/content/drive')

  # # Remove any existing chroma db in local path if any.
  # if os.path.exists('/content/FOMC_ChromaDB_Data_v2'):
  #   shutil.rmtree('/content/FOMC_ChromaDB_Data_v2')

  # # Copy complete folder to local Colab path
  # shutil.copytree(
  #   "/content/drive/MyDrive/FOMC_ChromaDB_Data_v2",
  #   "/content/FOMC_ChromaDB_Data_v2"
  #   )

  from chromadb.utils import embedding_functions
  embed_model = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="mukaj/fin-mpnet-base")
  # Local path drive details for chromadb upload.
  chroma_drive_path = "/content/FOMC_ChromaDB_Data_v2"

  # instantiating PersistentClient of chromadb.
  client = chromadb.PersistentClient(path=chroma_drive_path)

  # Defining collection set up in chroma to pass the embedding function for embedding document chunks.
  chroma_collection = client.get_or_create_collection(name='FOMC_Chroma_Client1', embedding_function=embed_model)

  return chroma_collection

### Function to rewrite user query for effective semantic retrieval through llm.

In [102]:
## Function to rewrite user query using claude sonnet llm for generating efficient query.

!pip install anthropic
import anthropic, io, contextlib

def query_rewriter_llm(user_query):
  # Mount Google Drive.
  from google.colab import drive
  with contextlib.redirect_stdout(io.StringIO()):
    drive.mount('/content/drive')

  # Set the anthropic claude API key
  filepath = "/content/drive/MyDrive/Agentic RAG Project/"
  with open(filepath + "claude_anthropic_api_key.txt", "r") as f:
   api_key = ' '.join(f.readlines())
   client = anthropic.Anthropic(api_key=api_key)

  original_query=user_query
  response = client.messages.create(
    model="claude-sonnet-4-6",
    max_tokens=150,
    system="""You are an expert in Federal Reserve communications and monetary policy domain and excel at rewriting original query to generate optimized output query.\
    You should rewrite the user's original query for effective searching in FOMC meeting minutes and policy statements.\
    Your primary aim is to expand relevant financial terminology, provide synonyms, and make the intent explicit.\
     You must return only the rewritten query in the output and do not add any labels, do not provide an explanation, and do not add the original query.""",
    messages=[
        {"role": "user", "content": f"Rewrite this query for better retrieval: {original_query}"}
    ])
  llm_output={"rewritten_query":response.content[0].text, "original_query":original_query}
  return llm_output

Collecting anthropic
  Downloading anthropic-0.86.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->anthropic) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.2)
Downloading anthropic-0.86.0-py3-none-any.whl (469 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.4/469.4 kB 20.5 MB/s eta 0:00:00
Installing collected packages: anthropic
Successfully installed anthropic-0.86.0

#### Function for query search in chroma db collection and retrieval of top 15 semantic chunks.

In [103]:
## Defining Function for query search in chroma vector DB.

def query_engine(user_query,chroma_collection):

  ## Perform query on choromadb based on user query and retrieve top 15 relevant search from vector db.
    query_results = chroma_collection.query(query_texts=user_query,n_results=15)
  ## Creating Dataframe of query results.
    query_results_df=pd.DataFrame(columns=['Document','Metadatas','Distance'])
    query_results_df['Document']=query_results['documents'][0]
    query_results_df['Metadatas']=query_results['metadatas'][0]
    query_results_df['Distance']=query_results['distances'][0]
    query_results_df['Document_ID']=[i['doc_id'] for i in query_results_df['Metadatas']]
    query_results_df['Chunk_ID']=[i['chunk_id'] for i in query_results_df['Metadatas']]
    query_results_df['Meeting_Date']=[i['meeting_date'] for i in query_results_df['Metadatas']]
  ## Return sorted table on Distance.
    top_15_similar_document= query_results_df.sort_values(by='Distance',ascending=True)
    return(top_15_similar_document)

#### Re-ranking function to rerank top 15 chunks retrieved at first instance based on similarity scores for further refinement.

In [104]:
## Re-ranking function using crossencoder model for retrieval of more semantic similar documents from top 15 docuemnts retreievd from chromadb.

from sentence_transformers import CrossEncoder
reranker = CrossEncoder("cross-encoder/stsb-roberta-large")
def rerank_top15_document(user_query,top_15_similar_document):

  ## Creating pair of document(top 10 documents obtianed from engiene query) and query list for re-ranking score.
    cross_encoder_sentence_query_pair = [[user_query,x] for x in top_15_similar_document.Document]

  ## Predicting scores of document and query pair.
    score=reranker.predict(cross_encoder_sentence_query_pair)

  ## Normalising score obtained above in range[0-1] by applying sigmoid function.
    score_norm = [round(float(1/(1+np.exp(-scr))),4) for scr in score]

  ## Updating score and normalised score in dataframe.
    top_15_similar_document['Encoder_Norm_score']=score_norm
    top_15_similar_document['Encoder_score']=score

  ## return sorted table by sorting Norm Score in Descending order.
    return(top_15_similar_document.sort_values(by='Encoder_Norm_score',ascending=False))

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/stsb-roberta-large
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

#### Primary Orchestrator function for retreival from required tool.

In [105]:
### Orchestartion of query to call required functions for retrieval.

def query_orchestrator_for_retreival(llm_query_parse_dict,user_query):
  if llm_query_parse_dict['query_type']=='numeric':   ## Route numeric query type to correct functions for retrieval.
    if llm_query_parse_dict['query_task_type']=='single':
      qry_res=numeric_single_query_retreival(llm_query_parse_dict,user_query)
      return qry_res
    elif llm_query_parse_dict['query_task_type']=='timeseries':
      timeseries_values_for_llm,timeseries_data=numeric_timeseries_query_retreival(llm_query_parse_dict,user_query)
      return timeseries_values_for_llm,timeseries_data
    elif llm_query_parse_dict['query_task_type']=='compare_indicator':
      comparision_values_for_llm,timeseries_data_1,timeseries_data_2=numeric_compare_multiindicator_query_retreival(llm_query_parse_dict)
      return comparision_values_for_llm,timeseries_data_1,timeseries_data_2
    elif llm_query_parse_dict['query_task_type']=='compare_period':
      comparision_values_for_llm,timeseries_data_1,timeseries_data_2=numeric_compare_multiperiod_query_retreival(llm_query_parse_dict)
      return comparision_values_for_llm,timeseries_data_1,timeseries_data_2
  ## Route text query type to correct functions for retrieval
  elif llm_query_parse_dict['query_type']=='text':
      if (llm_query_parse_dict['query_task_type']=='summary_fomc_minute') or (llm_query_parse_dict['query_task_type']=='summary_fomc_statement'):
        if not(llm_query_parse_dict['start_dt']) and not(llm_query_parse_dict['end_dt']):
          time_range=input('Please provide year of document for summary:')
          llm_query_parse_dict=query_intent_parser(user_query+time_range)
          documents_for_llm_summary=text_document_summary_query_retreival(llm_query_parse_dict)
          return documents_for_llm_summary
        else:
          documents_for_llm_summary=text_document_summary_query_retreival(llm_query_parse_dict)
          return documents_for_llm_summary
      elif llm_query_parse_dict['query_task_type']=='summary_topic':
        documents_for_llm_summary=text_topic_summary_query_retreival(llm_query_parse_dict,user_query)
        return documents_for_llm_summary
      elif llm_query_parse_dict['query_task_type']=='question_answer':
        documents_for_llm_summary=text_question_answer_query_retreival(llm_query_parse_dict,user_query)
        return documents_for_llm_summary

In [106]:
## To check all the query type functions are orchestrator function is working as expected.

user_query=input('input your query : ')
query_parse=query_intent_parser(user_query)
query_orchestrator_for_retreival(query_parse,user_query)
# query_parse

input your query : what was gdp rate in 2024

{'query_type': 'numeric',
 'query_task_type': 'single',
 'start_dt': '2024-01-01',
 'end_dt': '2024-12-31',
 'indicator': ['GDP Growth Rate'],
 'chart_required': 'no',
 'user_query': 'what was gdp rate in 2024',
 'aggregation_method': 'Average',
 'numeric_query_result': [{'indicator_label': 'GDP Growth Rate',
   'rate_value_%': 3.01,
   'unit': 'percentage'}]}

# <font color = yellow><b> Implementation of Response generation Agent using LLM prompt

In [107]:
## To mount google drive in colab for api keys load.
import contextlib

import io
from google.colab import drive

with contextlib.redirect_stdout(io.StringIO()):
    drive.mount('/content/drive')
# Set the API key
filepath = "/content/drive/MyDrive/Agentic RAG Project/"
with open(filepath + "OpenAI_API_Key.txt", "r") as f:
 api_key = ' '.join(f.readlines())

#### LLM Prompt 1: For generation of response to numeric and single type of query.

In [108]:
## Creating system message and user message for prompt.

def numeric_single_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic analysis domain especially with FRED economic indcator and FOMC to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC and FRED-based macroeconomic queries.
  You will be provided with structured query details and the computed numeric result in JSON format.
  Your task is to generate a clear, human understandable, natural language response to the user's question using only from the provided inputs.

  You must follow below guidelines before generating the response-
  1. Read and understand the user question from <<user_query>> parameter.
  2. Understand the user question context from below parameter values:
	  a. <<query_task_type>>
	  b. <<start_date>>
	  c. <<end_date>>
	  d. <<indicator>>
	  e. <<aggregation_method>>
  3. Read the final computed answer from <<numeric_query_result>>.
  4. Generate a concise and natural response that directly answers the user question.
  5. Do not calculate or generate any value on your own.
  6. Use only the result values present in <<numeric_query_result>>.
  7. For better response, you must mention the indicator name and unit in the response.
  8. When required mention the <<aggregation_method>> naturally in the response.
  9. If the numeric result is empty, say that no data was found for the requested query period.
  10. Replace the word percentage with '%' when generating direct response to user query after a single space.

 Note that query and response details is provided in {output_json} and you must return a response.
  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 2: For generation of response to numeric and timeseries type of query.

In [109]:
## Creating system message and user message for prompt.

def numeric_timeseries_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic analysis domain especially with FRED economic indcator and FOMC to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC and FRED-based macroeconomic queries.
  You will be provided with structured query details and the computed numeric result in JSON format.
  Your task is to generate a clear, human understandable, natural language response to the user's question using only from the provided inputs.

  You must follow below guidelines before generating the response-
  1. Read and understand the user question from <<user_query>> parameter.
  2. Understand the user question context from below parameter values:
	  a. <<query_task_type>>
	  b. <<start_date>>
	  c. <<end_date>>
	  d. <<indicator>>
	  e. <<high_value>>
	  f. <<low_value>>
    g. <<average_value>>
    h. <<first_value>>
	  i. <<last_value>>
	  j. <<slope_value>>
	  k. <<trend>>
	  l. <<volatility>>
	  m. <<chart_required>>

  3. Generate a concise and natural response that answers the user question directly and naturally.
  4. Do not calculate or generate any value on your own.
  5. You must generate natural language answers that explains the trend of the data in simple language.
  6. When required mention the <<trend>> and <<volatility>> naturally in the response.
  7. If the result is empty or missing, say that no data was found for the requested query period.
  8. Return plain text only and do not format in bold font. Do not use Markdown formatting like **bold** or bullet points.

  Note that query and response details is provided in {output_json} and you must return a response.
  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 3: For generation of response to numeric and indicator comparision type of query.

In [110]:
## Creating system message and user message for prompt.

def numeric_indicator_compare_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic analysis domain especially with FRED economic indcator and FOMC to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC and FRED-based macroeconomic queries.
  You will be provided with structured query details and the computed numeric result in JSON format.
  Your task is to perform comparison analysis between two indicators and generate a clear, human understandable, natural language comparative analysis response to the user's question using only from the provided structured input data.

  You must follow below guidelines before generating the response-
  1. Read and understand the user question from <<user_query>> parameter.
  2. Understand the user question context from <<type_of_comparision>> parameter.
  3. Read and perform comparison analysis between indicators from below parameter values provided for both the indicators:
    a. <<indicator_label>>
    b. <<high_value>>
    c. <<low_value>>
    d. <<average_value>>
    e. <<first_value>>
    f. <<last_value>>
    g. <<slope_value>>
    h. <<start_date>>
    i. <<end_date>>
    j. <<trend>>
    k. <<volatility>>
  4. Read the value of parameter <<'indicator_higher_rate'>> to understand which indicator have higher rate value from the two use this information when generating a comparison summary.
  5. Parameter <<difference_of_indicators_average>> will tell you the value of rate differences between two indicators and use this information when generating a comparison summary.
  6. You must compare the indicators based on their trend, volatility, average value and slope.
  7. If indicator have significantly increased or decreased, then mention the same by highlighting during the response generation.
  8. A chart will be required to visualise the trend and pattern of both indicators in given time range and mention that a visual comparison chart is provided.
  9. Generate a natural language response for explaining the comparison analytically understandable by financial users as well.
  10. Whenever you see any change or movement of values, provide an interpretation of the change in economic terms.
  11. If the result is empty or missing, say that no data was found for the requested query period.
  12. Return plain text only and do not format in bold font. Do not use Markdown formatting like **bold** or bullet points.

  Note that query and response details is provided in {output_json} and you must return a response.

  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 4: For generation of response to numeric and period wise comparision type of query.

In [111]:
## Creating system message and user message for prompt.

def numeric_period_compare_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic analysis domain especially with FRED economic indcator and FOMC to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC and FRED-based macroeconomic queries.
  You will be provided with structured query details and the computed numeric result in JSON format.
  Your task is to perform comparison analysis between two period range data of same indicator and generate a clear, human understandable, natural language comparative analysis response to the user's question using only from the provided structured input data.

  You must follow below guidelines before generating the response-
  1. Read and understand the user question from <<user_query>> parameter.
  2. Understand the user question context from <<type_of_comparision>> parameter.
  3. Read and perform comparison analysis of one indicators between different time range from below parameter values provided for both the period:
    a. <<indicator_label>>
    b. <<high_value>>
    c. <<low_value>>
    d. <<average_value>>
    e. <<first_value>>
    f. <<last_value>>
    g. <<slope_value>>
    h. <<period1_range>>
    i. <<trend>>
    j. <<volatility>>
  4. Read the value of parameter <<'period_having_higher_rate'>> to identify the duration when the indicator have higher rate value from the two diffferent time range period and use this information when generating a comparison summary.
  5. Parameter <<difference_of_rate_average>> will tell you the value of rate differences between two different time period of same indicator and use this information when generating a comparison summary.
  6. You must compare the rate value changes across two different time range of same indicator based on their trend, volatility, average value and slope.
  7. If for a specific time period the rate value have significantly changed, then mention the same by highlighting during the response generation.
  8. A chart will be required to visualise the trend and pattern of both time duration for the indicator and mention that a visual comparison chart is provided.
  9. Generate a natural language response for explaining the comparison analytically understandable by financial users as well.
  10. Whenever you see any change or movement of values, provide an interpretation of the change in economic terms.
  11. If the result is empty or missing, say that no data was found for the requested query period.
  12. Return plain text only and do not format in bold font. Do not use Markdown formatting like **bold** or bullet points.
  13. You need to give more importance in explaining how the indicator evolved/changed between the two time periods rather than repeating raw numbers.
  Note that query and response details is provided in {output_json} and you must return a response.

  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 5: For generation of response to summary type query based on topic/indicator.

In [112]:
## Creating system message and user message for prompt.

def text_summary_topic_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic and policy analysis of FOMC textual data to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC statements and minutes document textual query.
  You will be provided with structured FOMC text related query details in <<User_query>> and the optimized re-written query in <<Rewritten_query>> to obtain context of the query for generating summary based on indicator.
  You will be provided list of relevant chunks of meeting documents that are most relevant to user query in <<Retrieved_documents>>.
  Your task is to generate a comprehensive topic-based summary from retrieved Federal Open Market Committee (FOMC) meeting documents provided in <<Retrieved_documents>>.

  <<User_query>> : <<original_user_query>> parameter from <<output_json>>

  <<Rewritten_query>> : <<rewritten_user_query>> parameter from <<output_json>>

  <<Retrieved_documents>> : <<documents_retrieved_for_summary>> from <<output_json>>


  You must follow below instructions for generating the response:
  1. Identify the main topic requested by the user by analysing the user query in <<User_query>>.
  2. Review all the ten retrieved document excerpts from <<Retrieved_documents>> and identify statements most relevant to the topic.
  3. Extract below key and important economic insights to be included as part of summary.
    a. risk assessments
    b. meeting discussions
    c. economic indicators
    d. committee member participant's views and opinion
    e. policy stance
  4. If any overlapping insights or ideas across multiple documents then combine the information to produce a coherent explanation of the topic.
  5. Use only information provided in the retrieved documents and do not add any information of your own.
  6. You must not discuss indicators not related to topic or policy themes unless they are necessary to explain or provide context or support the explanation of requested topic.
  7. You must write as a professional and economic analyst.
  8. At the end of summary , you must provide citation of the documents that you used for generating summary.
  9. Follow below format for generating summary of the topic
  10. You must use '%' when refering to percentages and instead of writing the word 'percent' provide '%'.
      Example: 2% instead of 2 percent.

  Note that query and response details is provided in {output_json} and you must return a response.
  Output Format:

  Summary of topic:

  Write a concise analytical summary of 7–9 sentences explaining the topic discussed in FOMC documents.

  Key Insights:

  • Insight 1
  • Insight 2
  • Insight 3
  • Insight 4

  Citation Evidence:

  Mention the meeting dates referenced in the retrieved documents in format yyyy-mm-dd along with the source type as Minutes (M) or Statement(S) based on value provided in 'doc_type' parameter of <<documents_retrieved_for_summary>>.
  List all document citations using the STRICT format below:
  Document Date - YYYY-MM-DD , Source Type - Minutes
  Document Date - YYYY-MM-DD , Source Type - Statement
  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 6: For generation of response to summary type query based on FOMC Statement document type.

In [113]:
## Creating system message and user message for prompt.

def text_summary_fomc_statement_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic and policy analysis of FOMC textual data to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC statements only document textual query.
  You will be provided list of relevant chunks of FOMC statement documents for a specific period for generating comprehensive summary.
  Your task is to generate a comprehensive FOMC statement document summary from retrieved Federal Open Market Committee (FOMC) meeting documents provided in <<document_retreived_for_sumamry>>.

  <<document_retreived_for_sumamry>> from <<output_json>>

  You must follow below instructions for generating the summary response:
  1. Read and understand all the relevant documents excerpts from <<document_retreived_for_sumamry>>.
  2. Extract below key and important economic insights to be included as part of summary.
    a. risk assessments
    b. meeting discussions
    c. impact of economic indicators on policy
    d. committee member participant's views and opinion
    e. policy stance
  3. If any overlapping insights or ideas across multiple documents then combine the information to produce a coherent explanation of the topic.
  4. Use only information provided in the retrieved documents and do not add any information of your own.
  5. You must write as a professional and economic analyst.
  6. At the end of summary , you must provide citation of the documents that you used for generating summary.
  7. You must use '%' when refering to percentages and instead of writing the word 'percent' provide '%'.
      Example: 2% instead of 2 percent.

  Note that query type, document type, start date, emd date and relevant documents details are provided in {output_json} and you must return a response.
  <<start_date>> parameter value indicates the start date of FOMC statement.
  <<end_date>> parameter value indicates the end date of FOMC statement.

  Follow below format for generating summary of the topic
  Output Format:

  Summary of FOMC statement from <<start_date>> to <<end_date>>:

  Write a concise analytical summary of 7–9 sentences explaining the topic discussed in FOMC documents but do not exceed more than 200 words. Try to fit the first layer of summary in 200 words.

  Key Insights:

  • Insight 1
  • Insight 2
  • Insight 3
  • Insight 4

  Citation Evidence:

  Mention the meeting dates referenced in the retrieved documents in format yyyy-mm-dd and also provide citation link for each document.
  List all document citations using the STRICT format below:
  Document Date - YYYY-MM-DD , https://www.federalreserve.gov/newsevents/pressreleases/monetaryYYYYMMDDa.htm
  Document Date - YYYY-MM-DD , https://www.federalreserve.gov/newsevents/pressreleases/monetaryYYYYMMDDa.htm

  Replace YYYYMMDD in the link 'https://www.federalreserve.gov/newsevents/pressreleases/monetaryYYYYMMDDa.htm' with values present in document timestamp of document in <<document_retreived_for_sumamry>>.
  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 7: For generation of response to summary type query based on FOMC Minute document type.

In [114]:
## Creating system message and user message for prompt.

def text_summary_fomc_minute_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic and policy analysis of FOMC textual data to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC minutes only document textual query.
  You will be provided list of relevant chunks of FOMC minute documents for a specific period for generating comprehensive summary.
  Your task is to generate a comprehensive FOMC minute document summary from retrieved Federal Open Market Committee (FOMC) meeting documents provided in <<document_retreived_for_sumamry>>.

  <<document_retreived_for_sumamry>> from <<output_json>>

  You must follow below instructions for generating the summary response:
  1. Read and understand all the relevant documents excerpts from <<document_retreived_for_sumamry>>.
  2. Extract below key and important economic insights to be included as part of summary.
    a. risk assessments
    b. meeting discussions
    c. impact of economic indicators on policy
    d. committee member participant's views and opinion
    e. policy stance
  3. If any overlapping insights or ideas across multiple documents then combine the information to produce a coherent explanation of the topic.
  4. Use only information provided in the retrieved documents and do not add any information of your own.
  5. You must write as a professional and economic analyst.
  6. At the end of summary , you must provide citation of the documents that you used for generating summary.
  7. You must use '%' when refering to percentages and instead of writing the word 'percent' provide '%'.
      Example:3% instead of 3 percent.

  Note that query type, document type, start date, emd date and relevant documents details are provided in {output_json} and you must return a response.
  <<start_date>> parameter value indicates the start date of FOMC minute.
  <<end_date>> parameter value indicates the end date of FOMC minute.

  Follow below format for generating summary of the topic
  Output Format:

  Summary of FOMC minute from <<start_date>> to <<end_date>>:

  Write a concise analytical summary of 7–9 sentences explaining the topic discussed in FOMC minute documents but do not exceed more than 200 words. Try to fit the first layer of summary in 200 words.

  Key Insights:

  • Insight 1
  • Insight 2
  • Insight 3
  • Insight 4

  Citation Evidence:

  Mention the meeting dates referenced in the retrieved documents in format yyyy-mm-dd and also provide citation link for each document.
  List all document citations using the STRICT format below:
  Document Date - YYYY-MM-DD , https://www.federalreserve.gov/monetarypolicy/fomcminutesYYYYMMDD.htm
  Document Date - YYYY-MM-DD , https://www.federalreserve.gov/monetarypolicy/fomcminutesYYYYMMDD.htm

  Replace YYYYMMDD in the link 'https://www.federalreserve.gov/monetarypolicy/fomcminutesYYYYMMDD.htm' with values present in document timestamp of document in <<document_retreived_for_sumamry>>.
  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

#### LLM Prompt 8: For generation of response to question answer textual type query from FOMC documents.

In [115]:
## Creating system message and user message for prompt.

def text_question_answer_query_response_llm(output_json,api_key):
  system_message = """ You are an expert financial analysis assistant who is expertise in Macroeconomic and policy analysis of FOMC textual data to generate human understandable response from user query. """

  user_message = f"""
  You are an expert financial analysis assistant for FOMC minutes and statements document textual query.
  You will be provided list of relevant chunks of FOMC documents including both statement and minute type for a specific period.
  Your task is to generate answer to original user query related to FOMC communication documents from retrieved Federal Open Market Committee (FOMC) documents provided in <<documents_retrieved_for_question_answer>>.

  <<documents_retrieved_for_question_answer>> from <<output_json>>

  You must follow below instructions for generating the summary response:
  1. Read and understand all the relevant documents excerpts from <<documents_retrieved_for_question_answer>>.
  2. Read and understand the context of user original query from <<original_user_query>> parameter from <<output_json>>
  3. If any overlapping insights or ideas across multiple documents then combine the information to generate answer to user original query.
  4. Use only information provided in the retrieved documents and do not add any information of your own. The explanation in your answer must be simple, clear, concise, and factually grounded.
  5. You must not assume facts that are not present in the context and clearly mention in response if the answer generated from context document is partial.
  6. Whenever possible, mention the economic condition and policy stance.
  7. Write a direct answer to the user original question in 120–180 words and do not exceed more than 200 words. If required, you can use bullet points to explain the supporting information from documents.
  8. You must write as a professional and economic analyst.
  9. You must use '%' when refering to percentages and instead of writing the word 'percent' provide '%'.
      Example:3% instead of 3 percent.
  10. At the end of response, you must provide citation of the documents that you used for generating answer to user original query.

  Note that query type, original user query, meeting date and relevant documents details are provided in {output_json} and you must return a response.

  Citation Evidence:

  Mention the meeting dates referenced in the retrieved documents in format yyyy-mm-dd and also provide citation link for each document.
  You must ensure that for FOMC statement documents, the url link is 'https://www.federalreserve.gov/newsevents/pressreleases/monetaryYYYYMMDDa.htm'
  and for FOMC minute document url link is 'https://www.federalreserve.gov/monetarypolicy/fomcminutesYYYYMMDD.htm'
  You must use doicument type value based on 'doc_type' patrameter of <<documents_retrieved_for_question_answer>>.
  List all document citations using the STRICT format below:
  Document Date - YYYY-MM-DD , https://www.federalreserve.gov/monetarypolicy/fomcminutesYYYYMMDD.htm or https://www.federalreserve.gov/newsevents/pressreleases/monetaryYYYYMMDDa.htm based on document type.
  Document Date - YYYY-MM-DD , https://www.federalreserve.gov/monetarypolicy/fomcminutesYYYYMMDD.htm or https://www.federalreserve.gov/newsevents/pressreleases/monetaryYYYYMMDDa.htm based on document type.

  Replace YYYYMMDD in the url link  with values present in document timestamp of document in <<documents_retrieved_for_question_answer>>.

  """
  # Initialize client with API key
  client = OpenAI(api_key=api_key)

  ## Call LLM model GPT-5.4 to generate query parser in JSON response. We arere using chat gpt model GPT-4o Realtime(gpt-4.5-preview).

  llm_response_generation = openai.chat.completions.create( model="gpt-5.4",
                  messages=[{"role":"system", "content":system_message},
                             {"role":"user","content":user_message}], temperature=0
                  )
  return llm_response_generation.choices[0].message.content

# <font color = yellow><b> Chart Visualisation Agent :  To return plot of chart when user query demands for the plot of an indicator.

In [116]:
from overrides import final
from rich import print
import json, time
import matplotlib.dates as mdates

############################ Chart plot for trend of an indicator for timeseries type of query  #########################################

def chart_plot_of_trend_for_timeseries(data,summ):
  ## Set Date column as index.
  data.set_index('Date',inplace=True)
  ## To add trend in graph as liner straight line to understand the rise/fall in rate from 2000.
  x=np.arange(len(data.index))
  y=data['rate_value_%'].values
  coef=np.polyfit(x,y,1)    ## polyfit() function is to find best value of m(slope) and c(intercept) given value of x and y.
  trend=[]
  for i in x:
    trend.append(float(round(coef[0]*i+coef[1],2)))   ## first element in 'coef' is value of m(slope of line) and /
                                                    ##second element in 'coef' is value of c(intercept of linbe).
  ## Plot of trend
  plt.figure(figsize=(7,5))
  plt.plot(data.index, y, marker='o', linewidth=2.5, label='Actual')
  plt.plot(data.index,trend, linestyle='--', linewidth=2, label='Linear Trend')
  plt.title(f"{summ['indicator'][0]} trend/pattern in year {summ['start_date'][:4]}")
  plt.xlabel("Date (yyyy-mm-dd)")
  plt.ylabel(f"{summ['indicator'][0]} in %")
  plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
  plt.xticks(data.index,rotation=45)
  plt.grid(alpha=0.5)
  plt.legend()
  plt.show()

########################### Chart plot for trend of an indicator for comparision type of query ##########################################

def chart_plot_of_trend_for_comparision(data1,data2,summ):
  ## Plot for indicator_1
  ## Set Date column as index.
  data1.set_index('Date',inplace=True)
  ## To add trend in graph as liner straight line to understand the rise/fall in rate from 2000.
  x=np.arange(len(data1.index))
  y=data1['rate_value_%'].values
  coef=np.polyfit(x,y,1)    ## polyfit() function is to find best value of m(slope) and c(intercept) given value of x and y.
  trend=[]
  for i in x:
    trend.append(float(round(coef[0]*i+coef[1],2)))   ## first element in 'coef' is value of m(slope of line) and /
                                                    ##second element in 'coef' is value of c(intercept of linbe).
  ## Plot of trend
  plt.figure(figsize=(7,5))
  plt.plot(data1.index, y, marker='o', linewidth=2.5, label='Actual')
  plt.plot(data1.index,trend, linestyle='--', linewidth=2, label='Linear Trend')

  plt.title(f"{summ['indicator_1']['indicator_label']} trend/pattern in year {summ['indicator_1']['start_date'][:4]}")
  plt.xlabel("Date (yyyy-mm-dd)")
  plt.ylabel(f"{summ['indicator_1']['indicator_label']} in %")
  plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
  plt.xticks(data1.index,rotation=45)
  plt.grid(alpha=0.5)
  plt.legend()
  plt.show()
  print('\n\n')

  ## Plot for indicator_2
  ## Set Date column as index.
  data2.set_index('Date',inplace=True)
  ## To add trend in graph as liner straight line to understand the rise/fall in rate from 2000.
  x=np.arange(len(data2.index))
  y=data2['rate_value_%'].values
  coef=np.polyfit(x,y,1)    ## polyfit() function is to find best value of m(slope) and c(intercept) given value of x and y.
  trend=[]
  for i in x:
    trend.append(float(round(coef[0]*i+coef[1],2)))   ## first element in 'coef' is value of m(slope of line) and /
                                                    ##second element in 'coef' is value of c(intercept of linbe).
  ## Plot of trend
  plt.figure(figsize=(7,5))
  plt.plot(data2.index, y, marker='o', linewidth=2.5, label='Actual')
  plt.plot(data2.index,trend, linestyle='--', linewidth=2, label='Linear Trend')

  plt.title(f"{summ['indicator_2']['indicator_label']} trend/pattern in year {summ['indicator_2']['start_date'][:4]}")
  plt.xlabel("Date (yyyy-mm-dd)")
  plt.ylabel(f"{summ['indicator_2']['indicator_label']} in %")
  plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
  plt.xticks(data1.index,rotation=45)
  plt.grid(alpha=0.5)
  plt.legend()
  plt.show()

########################### Chart plot for trend of an indicator for comparision between two period ##########################################

def chart_plot_of_trend_for_period_comparision(data1,data2,summ):
  ## Plot for period_1
  ## Set Date column as index.
  data1.set_index('Date',inplace=True)
  ## To add trend in graph as liner straight line to understand the rise/fall in rate from 2000.
  x=np.arange(len(data1.index))
  y=data1['rate_value_%'].values
  coef=np.polyfit(x,y,1)    ## polyfit() function is to find best value of m(slope) and c(intercept) given value of x and y.
  trend=[]
  for i in x:
    trend.append(float(round(coef[0]*i+coef[1],2)))   ## first element in 'coef' is value of m(slope of line) and /
                                                    ##second element in 'coef' is value of c(intercept of linbe).
  ## Plot of trend
  plt.figure(figsize=(7,5))
  plt.plot(data1.index, y, marker='o', linewidth=2.5, label='Actual')
  plt.plot(data1.index,trend, linestyle='--', linewidth=2, label='Linear Trend')

  plt.title(f"{summ['period_1']['indicator_label'][0]} trend/pattern from {summ['period_1']['period1_range']}")
  plt.xlabel("Date (yyyy-mm-dd)")
  plt.ylabel(f"{summ['period_1']['indicator_label'][0]} in %")
  plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
  plt.grid(alpha=0.5)
  plt.gcf().autofmt_xdate()
  plt.legend()
  plt.show()
  print('\n\n')

  # Plot for period 2
  ## Set Date column as index.
  data2.set_index('Date',inplace=True)
  ## To add trend in graph as liner straight line to understand the rise/fall in rate from 2000.
  x=np.arange(len(data2.index))
  y=data2['rate_value_%'].values
  coef=np.polyfit(x,y,1)    ## polyfit() function is to find best value of m(slope) and c(intercept) given value of x and y.
  trend=[]
  for i in x:
    trend.append(float(round(coef[0]*i+coef[1],2)))   ## first element in 'coef' is value of m(slope of line) and /
                                                    ##second element in 'coef' is value of c(intercept of linbe).
  ## Plot of trend
  plt.figure(figsize=(7,5))
  plt.plot(data2.index, y, marker='o', linewidth=2.5, label='Actual')
  plt.plot(data2.index,trend, linestyle='--', linewidth=2, label='Linear Trend')
  plt.title(f"{summ['period_2']['indicator_label'][0]} trend/pattern from {summ['period_2']['period2_range']}")
  plt.xlabel("Date (yyyy-mm-dd)")
  plt.ylabel(f"{summ['period_2']['indicator_label'][0]} in %")
  plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
  plt.grid(alpha=0.5)
  plt.gcf().autofmt_xdate()
  plt.legend()
  plt.show()

### Initiate conversation with user for an interactive chatbot.

In [117]:
## user conversation chat bot function.

def initialize_conv():
    ## Start conversation with user.
    print('[bright_cyan]AI Assistant : Hello User, Please ask your question related to FOMC policy and FRED macroeconomic indicator. If you do not have any other query then please type "exit"[/bright_cyan]')
    retrieve_generate_time = [] ## To add time taken for model to retrieve and generate reply.
    while True:
      print('\n\nUser : ')
      user_query=input()
      if user_query.lower()=='exit':
        print('\n\n[bright_cyan]AI Assistant : Thank you for reaching us. Hope all your queries are resolved !![/bright_cyan]')
        break
      else:
        query_parse=query_intent_parser(user_query)
        strt=time.time()

        if query_parse['query_type']=='numeric' and query_parse['query_task_type']=='single':
          summ=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(summ, indent=1)
          final_response=numeric_single_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='numeric' and query_parse['query_task_type']=='timeseries':
          summ,data=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(summ, indent=1)
          final_response=numeric_timeseries_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='numeric' and query_parse['query_task_type']=='compare_indicator':
          summ,data1,data2=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(summ, indent=1)
          final_response=numeric_indicator_compare_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='numeric' and query_parse['query_task_type']=='compare_period':
          summ,data1,data2=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(summ, indent=1)
          final_response=numeric_period_compare_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='text' and query_parse['query_task_type']=='summary_topic':
          text_data=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(text_data, indent=1)
          final_response=text_summary_topic_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='text' and query_parse['query_task_type']=='summary_fomc_statement':
          text_data=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(text_data, indent=1)
          final_response=text_summary_fomc_statement_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='text' and query_parse['query_task_type']=='summary_fomc_minute':
          text_data=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(text_data, indent=1)
          final_response=text_summary_fomc_minute_query_response_llm(output_json,api_key)

        elif query_parse['query_type']=='text' and query_parse['query_task_type']=='question_answer':
          text_data=query_orchestrator_for_retreival(query_parse,user_query)
          output_json=json.dumps(text_data, indent=1)
          final_response=text_question_answer_query_response_llm(output_json,api_key)

        end=time.time()
        # Calculate total time taken.
        retrieve_generate_time.append(round(end-strt,4))

        # Print response generated
        print(f'\n\n[bright_cyan]AI Assistant : [/bright_cyan]\n[bright_green]{final_response}[/bright_green]')

        # Display chart for timeseries and compare query type
        if query_parse['query_type']=='numeric' and query_parse['query_task_type']=='timeseries':
          print(f'\n\n[bright_green]Please find below plot of {summ['indicator'][0]} for visualisation :-[/bright_green]\n\n')
          chart_plot_of_trend_for_timeseries(data,summ)

        elif query_parse['query_type']=='numeric' and query_parse['query_task_type']=='compare_indicator':
          print(f'\n\n[bright_green]Please find below plot of {summ['indicator_1']['indicator_label']} and {summ['indicator_2']['indicator_label']} for visual comparision :-[/bright_green]\n\n')
          chart_plot_of_trend_for_comparision(data1,data2,summ)

        elif query_parse['query_type']=='numeric' and query_parse['query_task_type']=='compare_period':
          print(f'\n\n[bright_green]Please find below plot of {summ['period_1']['indicator_label'][0]} between two different period for visual comparision :-[/bright_green]\n\n')
          chart_plot_of_trend_for_period_comparision(data1,data2,summ)

        # Print time taken to generate answer to user
        print(f'\n\n[bright_cyan]Time Taken: {round(end-strt,4)} seconds[/bright_cyan]')
        print('\n\n[bright_cyan]AI Assistant : Please ask your next question related to Insurance Policies. If you do not have any other query then please type "exit"[/bright_cyan]')
    return retrieve_generate_time  ## Return individual time taken for questions.

In [119]:
time_taken=initialize_conv()  ## Call function to initiate chat conversation with user.

AI Assistant : Hello User, Please ask your question related to FOMC policy and FRED macroeconomic indicator. If you
do not have any other query then please type "exit"

User :

what was inflation rate in 2025?

AI Assistant :
The Average Inflation Rate 5Year in 2025 was 2.41 %.

Time Taken: 0.8939 seconds

AI Assistant : Please ask your next question related to Insurance Policies. If you do not have any other query then
please type "exit"

User :

summarise gdp growth

AI Assistant :
Summary of topic:

FOMC documents describe real GDP growth as generally moderate to solid over the period covered, though with several
episodes of temporary weakness followed by expected rebounds. In 2014, staff repeatedly marked down first-half real
GDP growth because of weaker readings on consumer spending, residential construction, business investment, net
exports, inventories, health-care outlays, and construction, while also judging that severe winter weather
explained part, but not all, of the softness. Even so, both staff and participants generally expected growth to
strengthen in the second half of 2014 and over subsequent years, supported by reduced fiscal restraint, improving
credit availability and financial conditions, stronger consumer and business confidence, and firmer foreign growth.
Several 2014 discussions also noted that weaker GDP alongside lower unemployment led staff to reduce estimates of
potential output growth, implying somewhat narrower resource slack than previously assumed. Risk assessments around
GDP in 2014 were typically viewed as tilted a little to the downside, largely because policy was seen as not well
positioned to offset adverse shocks while the federal funds rate remained at the effective lower bound, although by
July those risks were judged more nearly balanced. Earlier, in 2012 and late 2013, participants characterized the
economy as expanding moderately and expected GDP growth to accelerate gradually, with accommodative monetary
policy, easing credit conditions, improved household balance sheets, and diminished fiscal restraint supporting the
outlook. By 2017, participants judged that hurricane-related disruptions would temporarily restrain third-quarter
GDP growth but would likely not materially alter the medium-term national outlook, with growth expected to rebound
as rebuilding progressed. In 2018, participants assessed economic activity as rising at a solid rate and indicated
that second-quarter GDP growth had strengthened, supported by strong labor markets, stimulative federal tax and
spending policies, accommodative financial conditions, and high household and business confidence, while also
flagging tariffs and trade restrictions as a possible risk to future investment and growth. Across these documents,
the policy stance was consistently framed as accommodative or gradually tightening in a way intended to sustain
expansion, strong labor market conditions, and inflation near the 2% objective.

Key Insights:

• In 2014, GDP growth was repeatedly revised down for the first half of the year, but the weakness was largely
viewed as temporary and followed by expectations of a stronger rebound in later quarters.
• Staff and participants linked the medium-term GDP outlook to support from accommodative monetary policy, less
fiscal drag, better credit conditions, stronger confidence, and improved foreign growth.
• Risk assessments for GDP were often slightly downside-tilted in 2014, while later documents showed more balanced
risks, though hurricanes in 2017 and trade concerns in 2018 were identified as notable threats to growth.
• Committee discussions consistently connected GDP growth with labor market improvement, narrowing resource slack,
and an appropriate policy path designed to preserve the expansion and keep inflation moving toward 2%.

Citation Evidence:

Document Date - 2012-04-25 , Source Type - Minutes
Document Date - 2013-12-18 , Source Type - Minutes
Document Date - 2014-03-04 , Source Type - Minutes
Document Date - 2014-03-19 , Source Type - Minutes
Document Date - 2014-04-30 , Source Type - Minutes
Document Date - 2014-06-18 , Source Type - Minutes
Document Date - 2014-07-30 , Source Type - Minutes
Document Date - 2017-09-20 , Source Type - Minutes
Document Date - 2018-06-13 , Source Type - Minutes

Time Taken: 28.7339 seconds

AI Assistant : Please ask your next question related to Insurance Policies. If you do not have any other query then
please type "exit"

User :

exit

AI Assistant : Thank you for reaching us. Hope all your queries are resolved !!